#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Mad_Libs
#c# 2018-08-18 <RC
#p# OK
#=# RC pipe: he\nOscar\ngiraffe\n

use strict;
use warnings;
my $result;

#my $template = shift;
#open my $IN, '<', $template or die $!;
#my $story = do { local $/ ; <$IN> };

my $story = '<name> went for a walk in the park. <he or she> found a <noun>. <name> decided to take it home.';

my %blanks;
undef $blanks{$_} for $story =~ m/<(.*?)>/g;

for my $blank (sort keys %blanks) {
    print "$blank: ";
    chomp (my $replacement = <>);
    $blanks{$blank} = $replacement;
}

$story =~ s/<(.*?)>/$blanks{$1}/g;
print "$story\n"; 

$result = 'Oscar went for a walk in the park. he found a giraffe. Oscar decided to take it home.';

use Test::More;
is ($result, $story);
done_testing;
