#!/usr/local/bin/perl
#u# https://rosettacode.org/wiki/Magic_numbers
#t# inprogress
#c# 2023-05-xx >RC
#p# OK

my @res;

use v5.36;

use bigint;
#use Lingua::EN::Numbers qw(num2en);
#use List::Categorize 'categorize';

my %M; 
my @magic = 0..9;

my $d = 1;
while () {
    last; # if/unless 
}

if (0) {
push @magic, 113456789;
push @magic, 123456789;
push @magic, 234567891;
push @magic, 987654321;
push @magic, 1234567890;
push @magic, 1203456789;
push @magic, 3608528850368400786036725;
push @magic, 3608528850368400786036725;
}

$M{length $_}++ for @magic;
#my %M =  categorize { length "$_" } @magic;

push @res, sprintf "There are %d magic numbers in total.\n", scalar @magic;
#push @res, sprintf "There are:";
for my $k (sort keys %M) {
    push @res, sprintf " %6d with %3d digit%s",  $M{$k}, $k, $k>1?'s':'';
}

push @res, "\nThe largest is $magic[-1].\n";
#push @res, sprintf "\nThe largest is %s (%s)", $x, num2en($x);

for my $i (1,0) {
    my $digits = join '', $i..9;
    push @res, "All magic numbers that are pan-digital in $i through 9 with no repeats: " . scalar 
        grep { length($_) == 10-$i and $digits eq join '', sort split '', $_ } @magic;
}

say my $result = join "\n", @res;
exit;

my $ref = <<'END';
There are 20457 magic numbers in total.

The largest is 3608528850368400786036725.

There are:
  10 with  1 digit
  45 with  2 digits
 150 with  3 digits
 375 with  4 digits
 750 with  5 digits
1200 with  6 digits
1713 with  7 digits
2227 with  8 digits
2492 with  9 digits
2492 with 10 digits
2225 with 11 digits
2041 with 12 digits
1575 with 13 digits
1132 with 14 digits
 770 with 15 digits
 571 with 16 digits
 335 with 17 digits
 180 with 18 digits
  90 with 19 digits
  44 with 20 digits
  18 with 21 digits
  12 with 22 digits
   6 with 23 digits
   3 with 24 digits
   1 with 25 digits

All magic numbers that are pan-digital in 1 through 9 with no repeats: 381654729
All magic numbers that are pan-digital in 0 through 9 with no repeats: 3816547290
END

__END__

#my \Δ = $ = 1;
my @magic = flat 0, [1..9], {last if .not; ++Δ; [(.flat X~ 0..9).grep: * %% Δ]}…*;



use Test::More;
chomp $ref;
is($result, $ref);
#is(($result =~ s/\s//gr), ($ref =~ s/\s//gr));
done_testing();

__END__

=={{header|Perl}}==
<syntaxhighlight lang="perl" line>
</syntaxhighlight>
{{out}}
<pre>
</pre>
