#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Magic_squares_of_odd_order
#t# skiptest
#c# 2019-05-04 >RC
#p# OK
#n# See Magic squares/Perl for a general magic square generator.

use Test::More;
ok 1 == 1;
done_testing;
