#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Magic_squares/Perl
#t# skiptest
#n# cf ~/perl6/Rosetta-Code/M/Magic_sqares_Perl_6-debug
#n# https://stackoverflow.com/questions/55994128/

use feature 'say';

# wrong
$n = 3; $i = 1; $x = $n/2; $y = 0;
for (0 .. -1 + $n**2) {
    $sq[($i%$n ? $y-- : $y++) % $n][($i%$n ? $x++ : $x) % $n] = $i++;
}
say join ' ', @$_ for @sq; say '';

# correct
$n = 3; $i = 1; $x = $n/2; $y = 0;
for (0 .. $n**2-1) {
    $sq[$y%$n][$x%$n] = $i;
    $i%$n ? $y-- : $y++;
    $x++ if $i%$n;
    $i++;
}
say join ' ', @$_ for @sq; 
