#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Magic_magics/Perl
#t# skiptest
#n# cf ~/perl6/Rosetta-Code/M/Magic_squares_Perl_6-debug
use feature 'say';

# wrong
$n = 3; $i = 1; $x = $n/2; $y = 0;
$sq1[($i%$n ? $y-- : $y++) % $n][($i%$n ? $x++ : $x) % $n] = $i++ for 0 .. -1 + $n**2;
say join ' ', @$_ for @sq1; say '';

# correct
$n = 3; $i = 1; $x = $n/2; $y = 0;
for (0 .. $n**2-1) {
    $sq2[($i%$n ? $y-- : $y++) % $n][($i%$n ? $x++ : $x) % $n] = $i;
    $i++;
}
say join ' ', @$_ for @sq2; say '';

# correct
$n = 3; $i = 1; $x = $n/2; $y = 0;
for (0 .. $n**2-1) {
    $sq3[$y%$n][$x%$n] = $i;
    $i%$n ? $y-- : $y++;
    $x++ if $i%$n;
    $i++;
}
say join ' ', @$_ for @sq3; say '';
