#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Man_or_boy_test
#c# 2018-08-18 <RC
#p# OK
#n# really gobbles memory for larger values of k

my @res;

use feature 'say';

sub A {
    my ($k, $x1, $x2, $x3, $x4, $x5) = @_;
    my($B);
    $B = sub { A(--$k, $B, $x1, $x2, $x3, $x4) };
    $k <= 0 ? &$x4 + &$x5 : &$B;
}

push @res, "k = $_: " . A($_, sub{1}, sub {-1}, sub{-1}, sub{1}, sub{0} ) for 10..18;

say my $result = join "\n", @res;

my $ref = <<'END';
k = 10: -67
k = 11: -138
k = 12: -291
k = 13: -642
k = 14: -1446
k = 15: -3250
k = 16: -7244
k = 17: -16065
k = 18: -35601
END

use Test::More;
chomp $ref;
is ($result, $ref);
done_testing();
