#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Matrix_with_two_diagonals
#c# 2022-02-17 <RC
#p# OK
#n# mangling tybalt89's version here, which technically meet the task requirements ('draws a square matrix'...)
#n# But "c'mon man!", this was not matrix, in the same way a picture of an egg is not nutritious!

my @res;

use strict;
use warnings;
use feature 'say';

sub diagonal {
  my $n =  shift() - 1;
  local $_ = 1 . 0 x ($n - 1) . 2 . "\n" . (0 . 0 x $n . "\n") x $n;
  1 while s/(?<=1...{$n})0/1/s or s/(?<=2.{$n})[01]/2/s;
  map { [ split ' ', $_ ] } split /\n/, tr/2/1/r =~ s/\B/ /gr; # DH convert string to array, for crying out loud
}

for (<4 5>) { 
    push @res, join ' ', @$_ for diagonal($_);
}

say my $result = join "\n", @res;

my $ref = <<'EOD';
1 0 0 1
0 1 1 0
0 1 1 0
1 0 0 1

1 0 0 0 1
0 1 0 1 0
0 0 1 0 0
0 1 0 1 0
1 0 0 0 1

EOD

use Test::More;
chomp $ref;
is ($result, $ref);
done_testing();
