#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Menu
#c# 2018-08-18 <RC
#p# OK
#=# RC pipe: 1

use strict;
use warnings;
use feature 'say';

sub menu
{
        my ($prompt,@array) = @_;
        return '' unless @array;

        print "  $_: $array[$_]\n" for(0..$#array);
        print $prompt;
        my $n = <>;
        return $array[$n] if $n =~ /^\d+$/ and defined $array[$n];
        return &menu($prompt,@array);
}

my @a = ('fee fie', 'huff and puff', 'mirror mirror', 'tick tock');
my $prompt = 'Which is from the three pigs: ';

my $a = &menu($prompt,@a);

say "You chose: $a";

use Test::More;
is $a, 'huff and puff';
done_testing();
