#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Menu
#c# 2018-08-18 <RC
#p# OK
#=# RC pipe: 1

sub menu
{
        my ($prompt,@array) = @_;
        return '' unless @array;

        print "  $_: $array[$_]\n" for(0..$#array);
        print $prompt;
        $n = <>;
        return $array[$n] if $n =~ /^\d+$/ and defined $array[$n];
        return &menu($prompt,@array);
}

@a = ('fee fie', 'huff and puff', 'mirror mirror', 'tick tock');
$prompt = 'Which is from the three pigs: ';

$a = &menu($prompt,@a);

print "You chose: $a\n";

use Test::More;
is $a, 'huff and puff';
done_testing();
