#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Modified_random_distribution
#c# 2021-03-01 >RC
#p# OK
#n# using Perl's quick & dirty 'named parameters' hack

srand 123456;

my @res;

use strict;
use warnings;
use feature 'say';
no strict 'refs';

use List::Util 'max';

sub modified_random_distribution {
    my %param = ( function => \&{scalar sub {return .5}}, sample_size => 1e5, @_);
   #my %param = ( function => 'modifier_uniform', sample_size => 1e5, @_);
    my @values;
    do {
        my ($r1, $r2) = (rand, rand);
        push @values, $r1 if &{$param{function}}($r1) > $r2;
    } until @values == $param{sample_size};
    @values
}

#sub modifier_uniform { return 0.5 } 

sub modifier_notch {
    my($x) = @_;
    return 2 * ( $x < 1/2 ? ( 1/2 - $x  )
                          : ( $x  - 1/2 ) );
} 

# Assumes minimum of zero
sub print_histogram {
    our %param = ( n_bins => 10, width => 80, @_);
    my %counts;
    $counts{ int( $_ * $param{n_bins} ) / $param{n_bins} }++ for @{$param{data}};
    our $max_value = max values %counts;
    #say ' Bin, Counts: Histogram';
    push @res, sprintf "%4.2f %6d: %s\n", $_, $counts{$_}, hist($counts{$_}) for sort keys %counts;
    sub hist { scalar ('■') x ( $param{width} * $_[0] / $max_value ) }
}

# use all defaults
#my @z = modified_random_distribution();
#print_histogram( data => \@z);
#push @res, "\n\n";

my @d = modified_random_distribution( function => \&modifier_notch, sample_size => 50_000);
print_histogram( data => \@d, n_bins => 20, width => 64);

say my $result = join '', @res;

my $ref = <<'END';
0.00   4772: ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
0.05   4329: ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
0.10   3728: ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
0.15   3249: ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
0.20   2749: ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
0.25   2163: ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
0.30   1735: ■■■■■■■■■■■■■■■■■■■■■■■
0.35   1317: ■■■■■■■■■■■■■■■■■
0.40    764: ■■■■■■■■■■
0.45    259: ■■■
0.50    231: ■■■
0.55    721: ■■■■■■■■■
0.60   1255: ■■■■■■■■■■■■■■■■
0.65   1730: ■■■■■■■■■■■■■■■■■■■■■■■
0.70   2282: ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
0.75   2720: ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
0.80   3302: ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
0.85   3712: ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
0.90   4219: ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
0.95   4763: ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
END

use Test::More;
is($result, $ref);
done_testing();
