#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Modular_arithmetic
#c# 2018-08-18 <RC
#p# OK

use strict;
no warnings;        # because of overloading
use feature 'say';

use Math::ModInt 'mod';
sub f { my $x = shift; $x**100 + $x + 1 };

say 'rewrites as: ' .  f mod(10, 13);
say 'evaluates as: ' . (my $result = f('mod(10, 13)'));

use Test::More;
is ($result, '1');
done_testing;
