#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Morse_code
#c# 2019-01-22
#p# OK
#n# not on RC, no sound (and ignoring the code actually on RC)
#n# doesn't do well with strict/warnings

my %m =(' ', '_ ',
qw<
    !	---.
    "	.-..-.
    $	...-..-
    '	.----.
    (	-.--.
    )	-.--.-
    +	.-.-.
    ,	--..--
    -	-....-
    .	.-.-.-
    /	-..-.
    :	---...
    ;	-.-.-.
    =	-...-
    ?	..--..
    @	.--.-.
    [	-.--.
    ]	-.--.-
    _	..--.-
    0	-----
    1	.----
    2	..---
    3	...--
    4	....-
    5	.....
    6	-....
    7	--...
    8	---..
    9	----.
    A	.-
    B	-...
    C	-.-.
    D	-..
    E	.
    F	..-.
    G	--.
    H	....
    I	..
    J	.---
    K	-.-
    L	.-..
    M	--
    N	-.
    O	---
    P	.--.
    Q	--.-
    R	.-.
    S	...
    T	-
    U	..-
    V	...-
    W	.--
    X	-..-
    Y	-.--
    Z	--..
>);

for (keys %m) {
    $m{$_} =~ s/-/dash /g;
    $m{$_} =~ s/\./dot /g;
    $m{$_} .= '_ ';
}

$result .= $m{$_} for split '', uc 'Is this thing on?';
print "$result\n";

my $ref = <<'EOD';
dot dot _ dot dot dot _ _ _ dash _ dot dot dot dot _ dot dot _ dot dot dot _ _ _ dash _ dot dot dot dot _ dot dot _ dash dot _ dash dash dot _ _ _ dash dash dash _ dash dot _ dot dot dash dash dot dot _ 
EOD

use Test::More;
chomp $ref;
is($result, $ref);
done_testing();
