#!/usr/local/bin/perl # do-not-check
#u# http://rosettacode.org/wiki/Mouse_position
#t# interactive
#c# 2018-11-12 <RC
#p# OK
#n# sort-of works, hangs sometimes (best to keep mouse inside terminal window?)

#Library: Perl/SDL[edit]
#The following code will use the SDL module, a wrapper for the libSDL C-library.
#When you move the mouse over the created window,
#the mouse position get printed and the program terminates.

use SDL;
use SDL::Events;
use SDLx::App;

my $app = SDLx::App->new;
$app->add_event_handler( sub {
	my $event = shift;
	if( $event->type == SDL_MOUSEMOTION ) {
		printf( "x=%d y=%d\n", $event->motion_x, $event->motion_y );
		$app->stop
	}
} );
$app->run;

#Output:
#x=15 y=304

use Test::More;
#is ($result, $ref);
#done_testing;
