#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Multiplicative_order
#c# 2018-08-19 <RC
#p# OK

use ntheory qw/znorder/;
my $result = znorder(54, 100001) . "\n";
use bigint; 
$result .= znorder(11, 1 + 10**100) . "\n";

# or
#use Math::Pari qw/znorder Mod/;
#say znorder(Mod(54, 100001));
#say znorder(Mod(11, 1 + Math::Pari::PARI(10)**100));

print "$result\n"; 

my $ref = <<'EOD';
9090
2583496112724752500580158969425549088007844580826869433740066152289289764829816356800
EOD

use Test::More;
is ($result, $ref);
done_testing;
