#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Balanced_brackets
#c# 2018-07-16 <RC, 2023-07-08 >RC
#p# OK
#n# for v5.36 and above switch to subroutine interface

my $result;

srand 123456;

use strict;
use warnings;
use feature 'say';

#use Regexp::Common 'balanced';
#my $re = qr/^$RE{balanced}{-parens=>'[]'}$/; # not sure how to handle in v5.36 (multidimensional array error)
#sub balanced {
#   return shift =~ $re;
#}

use Regexp::Common 'RE_balanced';
sub balanced {
    return shift =~ RE_balanced(-parens=>'[]')
}

sub generate {
    my $n = shift;
    my $str = '[' x $n;
    substr($str, rand($n + $_), 0) = ']' for 1..$n;
    return $str;
}

for (0..8) {
    my $input = generate($_);
    $result .= (sprintf balanced($input) ? " ok:" : "bad:") . " '$input'\n";
}

say $result;

my $ref = <<'END';
bad: ''
 ok: '[]'
 ok: '[[]]'
bad: ']]][[['
 ok: '[][][[]]'
 ok: ']][]]][[[['
 ok: '[][][[]][[]]'
 ok: '[[[]][[][[]]]]'
 ok: ']][][[[]]]][[[[]'
END

use Test::More;
is ($result, $ref);
done_testing;
