#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Best_shuffle
#c# 2018-07-16 <RC, 2023-04-03 >RC
#p# OK

my $result;

srand 123456;

use strict;
use warnings;
use feature 'say';

use feature 'bitwise';

use List::Util 'shuffle';

best_shuffle($_) for <abracadabra seesaw elk grrrrrr up a>;

sub best_shuffle {
	my ($original_word) = @_;

	my @s = split //, $original_word;
	my @t = shuffle @s;

	for my $i ( 0 .. $#s ) {
		for my $j ( 0 .. $#s ) {
			next if $j == $i or
				$t[$i] eq $s[$j] or
				$t[$j] eq $s[$i];
			@t[$i,$j] = @t[$j,$i];
			last;
		}
	}
	
	my $word = join '', @t;

	my $score = ($original_word ^. $word) =~ tr/\x00//;
	$result .= sprintf "$original_word, $word, $score\n";
}


say $result;

my $ref = <<'END';
abracadabra, daararacabb, 0
seesaw, ewsesa, 0
elk, lke, 0
grrrrrr, rgrrrrr, 5
up, pu, 0
a, a, 1
END

use Test::More;
is ($result, $ref);
done_testing;
