#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Bilinear_interpolation
#c# 2019-10-13 >RC
#p# OK
#f# RC file: color_wheel_interpolated.png
#n# 2022-06-27 warning wth v5.36: 
#n#            Use of uninitialized value $pkg in concatenation (.) or string at /usr/local/lib/perl5/5.36.0/Symbol.pm line 131.

use strict;
use warnings;

use GD;
local $SIG{__WARN__} = sub { };

my $image = GD::Image->newFromPng('ref/color_wheel.png');

$image->interpolationMethod( ['GD_BILINEAR_FIXED'] );
my($width,$height) = $image->getBounds();
my $image2 = $image->copyScaleInterpolated( 1.6*$width, 1.6*$height );

$image2->_file('run/color_wheel_interpolated.png') || die 'That did not go well...';
