#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Bilinear_interpolation
#c# 2019-10-13 >RC
#p# OK
#f# RC File: color_wheel_interpolated.png

use strict;
use warnings;

use GD;

my $file = 'ref/color_wheel.png';
my $image = GD::Image->newFromPng($file);

$image->interpolationMethod( ['GD_BILINEAR_FIXED'] );
my($width,$height) = $image->getBounds();
my $image2 = $image->copyScaleInterpolated( 1.6*$width, 1.6*$height );

$image2->_file('run/color_wheel_interpolated.png') || die 'That did not go well...';

__END__

my $png_data = $image->png;
open (DISPLAY,"| display -") || die;
binmode DISPLAY;
print DISPLAY $png_data;
close DISPLAY;


=={{header|Perl}}==
<lang perl></lang>
[https://github.com/SqrtNegInf/Rosettacode-Perl5-Smoke/blob/master/ref/XXX XXX]
