#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Binary_search
#c# 2018-07-16 <RC
#p# OK
#n# was producing bogus answer, changed to numeric input

use strict;
use warnings;
use feature 'say';
my $result;

sub binary_search {
    my ($array_ref, $value, $left, $right) = @_;
    return -1 if ($right < $left);
    my $middle = int(($right + $left) >> 1);
    if    ($value == $array_ref->[$middle]) { return $middle                                              }
    elsif ($value <  $array_ref->[$middle]) { binary_search($array_ref, $value, $left,       $middle - 1) }
    else                                    { binary_search($array_ref, $value, $middle + 1, $right     ) }
}

my @data = (1..100);
say $result = binary_search(\@data, 42, 0, -1 + scalar @data);

use Test::More;
is ($result, 41);
done_testing;
