#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Binary_search
#c# 2018-07-16 <RC, 2019-12-03 <RC
#p# OK
#n# was producing bogus answer, changed tests to be for strings (eg, lt)

use strict;
use warnings;
use feature 'say';
my $result;

sub binary_search1 {
    my ($array_ref, $value, $left, $right) = @_;
    while ($left <= $right) {
        my $middle = int(($right + $left) >> 1);
        if ($value eq $array_ref->[$middle]) {
            return $middle;
        }
        elsif ($value lt $array_ref->[$middle]) {
            $right = $middle - 1;
        }
        else {
            $left = $middle + 1;
        }
    }
    return -1;
}

sub binary_search2 {
    my ($array_ref, $value, $left, $right) = @_;
    while ($left <= $right) {
 
#print "$cicle\n";
    my $middle = int(($right + $left) >> 1);
 
        if ($value eq $$array_ref[$middle]) {
            return $middle;
        }
        elsif ($value lt $$array_ref[$middle]) {
#   print $value.'<'.$$array_ref[$middle]."\n";
            $right = $middle - 1;
        }
        else {
#       print $value.'<'.$$array_ref[$middle]."\n";
            $left = $middle + 1;
        }
    }
    return -1;
}
my @data = ('aa'..'zz');
say $result = binary_search2(\@data, 'qq', 0, -1 + scalar @data);

use Test::More;
is ($result, 432);
done_testing();
