#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Birthday_problem
#c# 2019-09-xx >RC
#p# OK

use List::Util qw(max min uniq);
use Math::Random qw(random_uniform_integer);

use strict;
use warnings;
use feature 'say';

my @res;

srand 123456;

my $debug = 1;

sub simulation {
    my($c) = shift;
    my $max_trials =   240_000;
    my $min_trials =     5_000;

my $n = int 47 * ($c-1.5)**1.5; # OEIS/A050256: 16 86 185 307
my $N = min $max_trials, max $min_trials, 1000 * sqrt $n;

say "starting with n = $n and N = $N" if $debug;

    while (1) {
        my $no = 0;
        for (1..$N) {
            my @bdays = random_uniform_integer($n, 1, 365);
            $no++ if $n == scalar uniq @bdays;
        }
        my $p = 1 - $no/$N;

# $p = $N R/ elems grep { .elems > 0 }, ((grep { $_>=$c }, values bag (^365).roll($n)) xx $N) 

        return($n, $p) if $p > 0.5;
        $N = min $max_trials, max $min_trials, int 1000/(0.5-$p)**2.0;
        say "n: $n  p: $p  next N: $N" if $debug;
        $n++;
    }
}

for (2..2) {
    my($n,$p) = simulation($_);
    printf "$_ people in a group of %s share a common birthday. (%.3f)\n", $n, $p;
    push @res, $n;
}

use Test::More;
#chomp $ref;
is(@res[0], 23);
done_testing();

__END__

my $ref = qq:to/END/;
2 people in a group of 23 share a common birthday. (0.506)
END
#3 people in a group of 88 share a common birthday. (0.511)
#4 people in a group of 187 share a common birthday. (0.503)
#5 people in a group of 313 share a common birthday. (0.501)

say my $result = join "\n", @res;
my $ref = <<'END';
END

__END__

=={{header|Perl}}==
{{trans|Perl 6}}
<lang perl></lang>
{{out}}
<pre style="height:20ex"></pre>
[https://github.com/SqrtNegInf/Rosettacode-Perl5-Smoke/blob/master/ref/XXX XXX]
