#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Averages/Mode
#c# 2018-07-15 <RC
#p# OK

use feature 'say';
my $result;

use strict;
use List::Util qw(max);
 
sub mode
{
    my %c;
    foreach my $e ( @_ ) {
        $c{$e}++;
    }
    my $best = max(values %c);
    return grep { $c{$_} == $best } keys %c;
}
$result .= "$_ " foreach mode(1, 3, 6, 6, 6, 6, 7, 7, 12, 12, 17);
$result .= "\n";
#$result .= "$_ " foreach mode(1, 1, 2, 4, 4); # flaps between '1 4' and '4 1'
#$result .= "\n";

say $result;

my $ref = <<EOD;
6 
EOD
#1 4 

use Test::More;
is ($result, $ref);
done_testing();
