#!/usr/bin/env perl
#u# http://rosettacode.org/wiki/Average_loop_length
#t# skiptest
#c# 2018-08-01 >RC
#p# BROKEN

srand 123456;

use feature 'say';
use strict;
use warnings;

use List::Util qw(sum);

use constant MAX_N  => 20;
use constant TRIALS => 100;

say " N    empiric      theoric      (error)";
say "===  =========  ============  =========";

__END__
my @res;
for my $N (1 .. MAX_N) {
    my $empiric = 1/ (TRIALS / (sum find_loop(random_mapping($N)).elems xx TRIALS );
    my $theoric = [+] map -> $k { $N ** ($k + 1) R/ [*] flat $k**2, $N - $k + 1 .. $N }, 1 .. $N;
 
    push @res, sprintf "%3d  %9.4f  %12.4f    (%4.2f%%)",
            $N,  $empiric,
                        $theoric, 100 * abs($theoric - $empiric) / $theoric;
}

sub random_mapping ($n) { 
    my %temp = random_mapping_orig($n);
    my %pair := array_hash();
    %pair{$_} = %temp{$_} for sort %temp.keys;
    return %pair;
}

sub random_mapping_orig { hash .list Z=> .roll(^$^size) given (^$^size) }

sub find_loop { 0, | %^mapping{*} ...^ { (%){$_}++ } }

for (@res) { say $_ }

my $ref = <<'END';
  1     1.0000        1.0000    (0.00%)
  2     1.5400        1.5000    (2.67%)
  3     2.0800        1.8889    (10.12%)
  4     2.4700        2.2188    (11.32%)
  5     2.4900        2.5104    (0.81%)
  6     2.8100        2.7747    (1.27%)
  7     3.1100        3.0181    (3.04%)
  8     3.2500        3.2450    (0.15%)
  9     3.8100        3.4583    (10.17%)
 10     3.6900        3.6602    (0.81%)
 11     3.8400        3.8524    (0.32%)
 12     3.7200        4.0361    (7.83%)
 13     4.2900        4.2123    (1.84%)
 14     4.1800        4.3820    (4.61%)
 15     4.5700        4.5458    (0.53%)
 16     4.6500        4.7043    (1.15%)
 17     4.9800        4.8579    (2.51%)
 18     4.8400        5.0071    (3.34%)
 19     5.3100        5.1522    (3.06%)
 20     5.6600        5.2936    (6.92%)
END

use Test::More;
#is @res.join("\n"), chomp $ref;
