#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Averages/Mode
#c# 2018-07-15 <RC
#p# OK

use feature 'say';

use strict;
use List::Util qw(max);
 
sub mode
{
    my %c;
    foreach my $e ( @_ ) {
        $c{$e}++;
    }
    my $best = max(values %c);
    return grep { $c{$_} == $best } keys %c;
}

#$result .= "$_ " foreach mode(1, 3, 6, 6, 6, 6, 7, 7, 12, 12, 17);
#$result .= "\n";

my @res;
push @res, $_ foreach mode(1, 1, 2, 4, 4);

say my $result = join ' ', sort @res;

my $ref = <<EOD;
1 4
EOD

use Test::More;
chop $ref;
is ($result, $ref);
done_testing();
