#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Check_input_device_is_a_terminal
#c# 2018-07-22 <RC
#p# OK

use feature 'say';
my $result;

use strict;
use warnings;
use 5.010;
if (-t) {
    say $result = "Input comes from tty.";
}
else {
    say $result = "Input doesn't come from tty.";
}

# $ perl istty.pl
# Input comes from tty.
# $ true | perl istty.pl
# Input doesn't come from tty.

use Test::More;
is ($result, 'Input comes from tty.');
done_testing();
