#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Detect_division_by_zero
#c# 2018-07-28 <RC
#p# OK

use feature 'say';
my $result;


# This function returns true iff its second argument is zero.

sub div_check
 {local $@;
  eval {$_[0] / $_[1]};
  $@ and $@ =~ /division by zero/;}

say $result = div_check(1, 0);

use Test::More;
is ($result, 1);
done_testing();
