#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Literals/Integer
#c# 2018-08-15 <RC
#p# OK

use feature 'say';
my $result;

say $result = "bingo" if 
                  ( 727 == 0x2d7 && 
                    727 == 01327 &&
                    727 == 0b1011010111 &&
                    12345 == 12_345   # underscores are ignored; useful for keeping track of places
                  );

use Test::More;
is ($result, 'bingo');
done_testing();
