#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Man_or_boy_test
#c# 2018-08-18 <RC
#p# OK

use feature 'say';
my $result;

sub A {
    my ($k, $x1, $x2, $x3, $x4, $x5) = @_;
    my($B);
    $B = sub { A(--$k, $B, $x1, $x2, $x3, $x4) };
    $k <= 0 ? &$x4 + &$x5 : &$B;
}

say $result = A(10, sub{1}, sub {-1}, sub{-1}, sub{1}, sub{0} ); #. "\n";

use Test::More;
is ($result, -67);
done_testing();
