#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Secure_temporary_file
#t# skiptest
#c# 2018-08-18 <RC
#p# OK

use feature 'say';
my $result;

#function interface:

use File::Temp qw(tempfile);
$fh = tempfile();
($fh2, $filename) = tempfile(); # this file stays around by default
print "$filename\n";
close $fh;
close $fh2;

#object-oriented interface:

use File::Temp;
$fh = new File::Temp;
print $fh->filename, "\n";
close $fh;

say $result; 
my $ref = <<'EOD';
EOD

use Test::More;
#is ($result, $ref);
#done_testing();
