#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Set_consolidation
#c# 2018-08-17 <RC
#p# OK

use feature 'say';
my $result;


# We implement the key data structure, a set of sets, as an array containing references to arrays of scalars.

use strict;
use English;
use Smart::Comments;
use Data::Dumper;

my @ex1 = consolidate( (['A', 'B'], ['C', 'D']) );
### Example 1: @ex1
my @ex2 = consolidate( (['A', 'B'], ['B', 'D']) );
### Example 2: @ex2
my @ex3 = consolidate( (['A', 'B'], ['C', 'D'], ['D', 'B']) );
### Example 3: @ex3
my @ex4 = consolidate( (['H', 'I', 'K'], ['A', 'B'], ['C', 'D'], ['D', 'B'], ['F', 'G', 'H']) );
### Example 4: @ex4

$Data::Dumper::Sortkeys = 1;
$result .= "Example 1:\n"; $result .= Dumper @ex1;
$result .= "Example 2:\n"; $result .= Dumper @ex2;
$result .= "Example 3:\n"; $result .= Dumper @ex3;
$result .= "Example 4:\n"; $result .= Dumper @ex4;

sub consolidate {
    scalar(@ARG) >= 2 or return @ARG;
    my @result = ( shift(@ARG) );
    my @recursion = consolidate(@ARG);
    foreach my $r (@recursion) {
        if (set_intersection($result[0], $r)) {
            $result[0] = [ set_union($result[0], $r) ];
        }
        else {
            push @result, $r;
        }
    }
    return @result;
}

sub set_union {
    my ($a, $b) = @ARG;
    my %union;
    foreach my $a_elt (@{$a}) { $union{$a_elt}++; }
    foreach my $b_elt (@{$b}) { $union{$b_elt}++; }
    return keys(%union);
}

sub set_intersection {
    my ($a, $b) = @ARG;
    my %a_hash;
    foreach my $a_elt (@{$a}) { $a_hash{$a_elt}++; }
    my @result;
    foreach my $b_elt (@{$b}) {
        push(@result, $b_elt) if exists($a_hash{$b_elt});
    }
    return @result;
}

say $result;
my $ref = <<'EOD';
Example 1:
$VAR1 = [
          'A',
          'B'
        ];
$VAR2 = [
          'C',
          'D'
        ];
Example 2:
$VAR1 = [
          'A',
          'D',
          'B'
        ];
Example 3:
$VAR1 = [
          'B',
          'D',
          'A',
          'C'
        ];
Example 4:
$VAR1 = [
          'G',
          'H',
          'I',
          'K',
          'F'
        ];
$VAR2 = [
          'C',
          'A',
          'D',
          'B'
        ];
EOD

use Test::More;
is ($result, $ref);
done_testing();
