#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Shoelace_formula_for_polygonal_area
#c# 2018-09-27 >RC
#p# OK

use feature 'say';

sub area_by_shoelace1 {
    local *p = shift;
    $a += $p[$_][0] * $p[($_+1)%@p][1] for 0 .. @p-1;
    $a -= $p[$_][1] * $p[($_+1)%@p][0] for 0 .. @p-1;
    return abs $a/2;
}

sub area_by_shoelace2 {
    local *p = shift;
    $a += $p[$_-1][0] * $p[($_)%@p][1] - $p[$_-1][1] * $p[($_)%@p][0] for 1 .. @p;
    return abs $a/2;
}
 
say my $result1 = area_by_shoelace1( [ [3,4], [5,11], [12,8], [9,5], [5,6] ] );
 
my @a = ( [3,4], [5,11], [12,8], [9,5], [5,6] );
say my $result2 = area_by_shoelace2(@a);

use Test::More;
is($result1, 30);
is($result2, 30);
done_testing();
