#!/usr/local/bin/perl
## xxx
#  David H.  2018-08-15

for $i (1..3) {
system ("Sorting_algorithms_Bead_sort; Sorting_algorithms_Bogosort; Sorting_algorithms_Bubble_sort; Sorting_algorithms_Cocktail_sort; Sorting_algorithms_Comb_sort; Sorting_algorithms_Counting_sort; Sorting_algorithms_Cycle_sort; Sorting_algorithms_Gnome_sort; Sorting_algorithms_Heapsort; Sorting_algorithms_Insertion_sort; Sorting_algorithms_Merge_sort; Sorting_algorithms_Pancake_sort; Sorting_algorithms_Patience_sort; Sorting_algorithms_Permutation_sort; Sorting_algorithms_Quicksort; Sorting_algorithms_Radix_sort; Sorting_algorithms_Selection_sort; Sorting_algorithms_Shell_sort; Sorting_algorithms_Sleep_sort; Sorting_algorithms_Stooge_sort;
Sorting_algorithms_Strand_sort");
}
