#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Spinning_rod_animation/Text
#c# 2018-10-01 >RC
#p# OK
#f# RC file: spinner.dat

$|= 1;

open F, ">run/spinner.dat" || die;

for (1..3) {
    for (qw[ | / - \ ]) {
        select undef, undef, undef, 0.25;
        printf F "\r ($_)";
    }
}
