#!/usr/local/bin/perl
## xxx
#  David H.  2019-02-12

use feature 'say';
use strict;

my @a = 1 .. 5;
my @b = 1 .. 5;
my @c = 1 .. 5;

push @b, @a[2];
push @c, $a[2];
say join ' ', @b;
say join ' ', @c;
