#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Terminal_control/Hiding_the_cursor
#t# interactive
#c# 2018-09-04 >RC
#p# OK

print "\e[?25l"; # hide the cursor
print "Enter anything, press RETURN: ";
$input = <>;
print "\e[0H\e[0J\e[?25h"; # reset
print "You entered: $input\n";

__END__

=={{header|Perl}}==
<lang perl>print "\e[?25l"; # hide the cursor
print "Enter anything, press RETURN: ";
$input = <>;
print "\e[0H\e[0J\e[?25h"; # reset
print "You entered: $input\n";</lang>
