#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Terminal_control_Unicode_output
#t# interactive
#c# 2018-09-04 >RC
#p# OK

die "Terminal can't handle UTF-8" unless
    $ENV{LC_ALL} =~ /utf-8/i or $ENV{LC_CTYPE} =~ /utf-8/i or $ENV{LANG} =~ /utf-8/i;

print "△ \n";
