#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Unix/ls
#c# 2018-08-07 <RC
#p# OK

use feature 'say';
my $result;

opendir my $handle, 'ref/test' or die "Couldnt open current directory: $!";
while (readdir $handle) {
    $result .= "$_\n";
}
closedir $handle;

# Alternatively, using glob:
#print "$_\n" for glob '*';
#print "$_\n" for glob '* .*';  # If you want to include dot files


say $result; 
my $ref = <<'EOD';
.
..
dir1
dir2
dir3
not-in-kansas.txt
reverse_words.txt
sample.txt
EOD

use Test::More;
is ($result, $ref);
done_testing();
