#!/usr/bin/env perl
#u# http://rosettacode.org/wiki/Word_count
#c# 2018-08-07 >RC
#p# OK

# {{trans|Perl 6}}

use feature 'say';

$filename = 'ref/word-count.txt';
$top = 10;

open $fh, "<", $filename;
($text = join '', <$fh>) =~ tr/A-Z/a-z/;

@matcher = (
    qr/[a-z]+/,                         # simple 7-bit ASCII
    qr/\w+/,                            # word characters with underscore
    qr/[a-z0-9]+/,                      # word characters without underscore
);
#    qr/([a-z0-9]+['"\-]?[a-z0-9]+)*/   # word characters without underscore but with hyphens and contractions '
#   rx/ <[\w]-[_]>+[["'"|'-'|"'-"]<[\w]-[_]>+]* / 


@res;
for $reg (@matcher) {
    push @res, "\nTop $top using regex: " . $reg;
    @matches = $text =~ /$reg/g;
    my %words;
    for $w (@matches) { $words{$w}++ };
    $c = 0;
    for $w ( sort { $words{$b} <=> $words{$a} } keys %words ) {
        push @res, sprintf "%-7s %6d", $w, $words{$w};
        last if ++$c >= $top;
    }
}

say $result = join "\n", @res;

my $ref = <<'END';

Top 10 using regex: (?^:[a-z]+)
the      41089
of       19949
and      14942
a        14608
to       13951
in       11214
he        9648
was       8621
that      7924
it        6661

Top 10 using regex: (?^:\w+)
the      41036
of       19946
and      14940
a        14589
to       13939
in       11204
he        9645
was       8619
that      7922
it        6659

Top 10 using regex: (?^:[a-z0-9]+)
the      41089
of       19949
and      14942
a        14608
to       13951
in       11214
he        9648
was       8621
that      7924
it        6661
END

use Test::More;
chop $ref;
is($result,$ref);
done_testing();
