#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Ackermann_function
#c# 2018-07-10 <RC
#p# OK

use strict;
use warnings;
use feature 'say';
my $result;

sub A {
  my ($m, $n) = @_;
  $m == 0 ? $n + 1 :
  $n == 0 ? A($m - 1, 1) :
            A($m - 1, A($m, $n - 1))
}

say $result = A(3,2);

use Test::More;
is ($result, 29);
done_testing;

