#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Active_Directory/Search_for_a_user
#c# 2021-03-07 <RC
#p# BROKEN

my @res;

use strict;
use warnings;
use feature 'say';

use Net::LDAP;

my $ldap = Net::LDAP->new( 'ldap://ldap.forumsys.com' )  or  die "$@";

my $mesg = $ldap->bind( "cn=read-only-admin,dc=example,dc=com",
                        password => "password"                  );

$mesg->code and die $mesg->error;

my $srch = $ldap->search( base   => "dc=example,dc=com",
                          filter => "(|(uid=gauss))"     );

$srch->code and die $srch->error;

my $result;
foreach my $entry ($srch->entries) { #$entry->dump } # how to capture this output?
    say $result = $$entry{asn}{attributes}[4]{vals}[0]
}

$mesg = $ldap->unbind;

my $ref = <<'EOD';
------------------------------------------------------------------------
dn:uid=gauss,dc=example,dc=com

objectClass: inetOrgPerson
             organizationalPerson
             person
             top
         cn: Carl Friedrich Gauss
         sn: Gauss
        uid: gauss
       mail: gauss@ldap.forumsys.com


EOD

use Test::More;
is ($result, 'gauss@ldap.forumsys.com');
done_testing();
