#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Add_a_variable_to_a_class_instance_at_runtime
#c# 2018-07-11 <RC
#p# OK

use strict;
use warnings;
use feature 'say';

# Works with: Perl version 5.x
package Empty;
 
# Constructor. Object is hash.
sub new { return bless {}, shift; }
 
package main;
 
# Object.
my $o = Empty->new;
 
# Set runtime variable (key => value).
$o->{'foo'} = 42;

say $o->{'foo'};

use Test::More;
is($o->{'foo'},42);
done_testing;
