#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Anagrams
#c# 2018-07-13 <RC, 2019-04-09 >RC
#p# OK

my($result,@res);

use strict;
no warnings 'uninitialized';
use feature 'say';

my(%anagram,$max);

my @words = split("\n", `cat ref/unixdict.txt`);
push @{$anagram{ join '' => sort split '' }}, $_ for @words;

$max > @$_  or  $max = @$_    for values %anagram;
@$_ == $max and push @res, "@$_\n" for values %anagram;

$result .= $_ for sort @res;
say $result;

my $ref = <<END;
abel able bale bela elba
alger glare lager large regal
angel angle galen glean lange
caret carte cater crate trace
elan lane lean lena neal
evil levi live veil vile
END

use Test::More;
is ($result, $ref);
done_testing();
