#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Anagrams
#c# 2018-07-13 <RC, 2019-04-09 >RC
#p# OK

use strict;
use warnings;
use feature 'say';
my($result,@res);

use List::Util 'max';

#my @words = split "\n", do { local( @ARGV, $/ ) = ( 'ref/unixdict.txt' ); <> };
my @words = split("\n", `cat ref/unixdict.txt`);
my %anagram;
for my $word (@words) {
    push @{ $anagram{join '', sort split '', $word} }, $word;
}

my $count = max(map {scalar @$_} values %anagram);
for my $ana (sort values %anagram) {
    push @res, "@$ana\n" if @$ana == $count;
}

$result .= $_ for sort @res;
say $result;

my $ref = <<'END';
abel able bale bela elba
alger glare lager large regal
angel angle galen glean lange
caret carte cater crate trace
elan lane lean lena neal
evil levi live veil vile
END

use Test::More;
is ($result, $ref);
done_testing;
