#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Anonymous_recursion
#c# 2018-07-13 <RC
#p# OK

use strict;
use warnings;
use feature 'say';
my $result;

sub fib {
	my ($n) = @_;
	die "negative arg $n" if $n < 0;
	# put anon sub on stack and do a magic goto to it
	@_ = ($n, sub {
		my ($n, $f) = @_;
		# anon sub recurs with the sub ref on stack
		$n < 2 ? $n : $f->($n - 1, $f) + $f->($n - 2, $f)
	});
	goto $_[1];
}

$result .= (fib($_). " ") for (0 .. 10);
say $result;

use Test::More;
is ($result, '0 1 1 2 3 5 8 13 21 34 55 ');
done_testing;
