#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Anonymous_recursion
#c# 2018-07-13 <RC
#p# OK
#n# but fib(0) incorrect, not that it matters...

my $result;

use strict;
use warnings;
use feature 'say';

sub recur :prototype(&@) {
    my $f = shift;
    local *recurse = $f;
    $f->(@_);
}

sub fibo {
    my $n = shift;
    $n < 0 and die 'Negative argument';
    recur {
        my $m = shift;
        $m < 3 ? 1 : recurse($m - 1) + recurse($m - 2);
    } $n;
}

$result .= (fibo($_). " ") for (0 .. 10);

say $result;

use Test::More;
is ($result, '1 1 1 2 3 5 8 13 21 34 55 ');
done_testing;
