#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Append_numbers_at_same_position_in_strings
#c# 2021-11-10 >RC
#p# OK

my($result1,$result2);

use strict;
use warnings;

my @a = < 1  2  3  4  5  6  7  8  9>; 
my @b = <10 11 12 13 14 15 16 17 18>; 
my @c = <19 20 21 22 23 24 25 26 27>;
my @d = <1  2  2  2  2  2  2  2  2 >;
my @e = < 9  0  1  2  3  4  5  6  7>;
my @f = (\@a, \@b, \@d, \@e);
#my @f = ([@a], [@b], [@d], [@e]);

print $a[$_] . $b[$_] . $c[$_] . ' ' for 0..$#a; print "\n";

$result1 .=  $a[$_] . $b[$_] . $c[$_] . ' ' for 0..$#a;

for my $i (0 .. $#{$f[0]}) {
   #map { $result2 .= $f[$_][$i] } 0 .. $#f and $result2 .= ' '
    $result2 .= $f[$_][$i] for 0 .. $#f;
    $result2 .= ' '
}

my $ref = '11019 21120 31221 41322 51423 61524 71625 81726 91827 ';

use Test::More;
is($result1, $ref);
is($result2, $ref);
done_testing;
