#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Arithmetic/Integer
#c# 2018-07-15 <RC
#p# OK

use strict;
use warnings;
use feature 'say';
my $result;

# Works with: Perl version 5.x
my $a = 2;
my $b = 5;
 
$result = sprintf
    "sum:              ". ($a + $b). "\n".
    "difference:       ". ($a - $b). "\n".
    "product:          ". ($a * $b). "\n".
    "integer quotient: ". int($a / $b). "\n".
    "remainder:        ". ($a % $b). "\n".
    "exponent:         ". ($a ** $b). "\n"
    ;


my $ref = <<'EOD';
sum:              7
difference:       -3
product:          10
integer quotient: 0
remainder:        2
exponent:         32
EOD

use Test::More;
is ($result, $ref);
done_testing;
