#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Arithmetic-geometric_mean
#c# 2018-07-15 <RC
#p# OK

use strict;
use warnings;
use feature 'say';
my $result;
 
my ($a0, $g0, $a1, $g1);
 
sub agm($$) {
    $a0 = shift;
    $g0 = shift;
    do { 
        $a1 = ($a0 + $g0)/2; 
        $g1 = sqrt($a0 * $g0); 
        $a0 = ($a1 + $g1)/2; 
        $g0 = sqrt($a1 * $g1); 
    } while ($a0 != $a1); 
    return $a0;
}
 
say $result = agm(1, 1/sqrt(2)) . "\n";

my $ref = <<EOD;
0.847213084793979
EOD

use Test::More;
is ($result, $ref);
done_testing();
