#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Arithmetic-geometric_mean/Calculate_Pi
#c# 2018-07-15 <RC
#p# OK

use strict;
use warnings;
use feature 'say';

use Math::BigFloat try => "GMP,Pari";

Math::BigFloat->div_scale(100);
 
my $a = my $n = 1;
my $g = 1 / sqrt(Math::BigFloat->new(2));
my $z = 0.25;
for( 0 .. 17 ) {
	my $x = [ ($a + $g) * 0.5, sqrt($a * $g) ];
	my $var = $x->[0] - $a;
	$z -= $var * $var * $n;
	$n += $n;
	($a, $g) = @$x;
}
say my $result = ($a * $a / $z);


my $ref = '3.141592653589793238462643383279502884197169399375105820974944592307816406286208998628034825342117067';

use Test::More;
is ($result, $ref);
done_testing;
