#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Array_concatenation
#c# 2018-07-14 <RC
#p# OK

use strict;
use warnings;
use feature 'say';

use Test::More;

# In Perl, arrays placed into list context are flattened:

my @arr1 = (1, 2, 3);
my @arr2 = (4, 5, 6, 7);
my @arr3 = (@arr1, @arr2);
is (+@arr3, 7);

# The push function appends elements onto an existing array:

@arr1 = (1, 2, 3);
@arr2 = (4, 5, 6);
push @arr1, @arr2;
say my $result = "@arr1";

is ($result, '1 2 3 4 5 6');
done_testing;
