#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/AudioAlarm
#t# skiptest
#c# 2019-09-22 NOT ON RC
#p# OK

use strict;
use warnings;

use Audio::Play::MPG123;

#my ($delay,$file);
#if ($ARGV[0]) { $delay = shift } else { print 'How long? ';  $delay = <>; chomp $delay }
#if ($ARGV[0]) { $file  = shift } else { print 'Which MP3? '; $file  = <>; chomp $file  }
#$file =~ s/\.mp3$//;
 
#sleep $delay;

my $player = Audio::Play::MPG123->new;
$player->load("$ENV{HOME}/Music/iTunes/iTunes\ Media/Music/Dixie\ Chicks/Fly/Ready\ to\ Run.mp3");
$player->poll(1) until $player->state == 0;
