#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Averages/Root_mean_square
#c# 2018-07-15 <RC
#p# OK

use strict;
use warnings;
use feature 'say';

sub rms {
        my $r = 0;
        $r += $_**2 for @_;
        sqrt( $r/@_ );
}
 
say my $result = rms(1..10);

use Test::More;
is ($result, '6.20483682299543');
done_testing;
