#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Averages/Arithmetic_mean
#c# 2018-07-15 <>RC
#p# OK
#n# removed example with non-existent module Data::Average

use strict;
use warnings;
use feature 'say';

sub avg {
  @_ or return 0;
  my $sum;
  $sum += $_ for @_;
  return $sum/@_;
}
 
say my $result = avg(<3 1 4 1 5 9>);

use Test::More;
is ($result, '3.83333333333333');
done_testing;
