#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Identity_matrix
#c# 2018-08-13 <RC
#p# OK

my @res;

use strict;
use warnings;
use feature 'say';

sub identity_matrix { 
    my($n) = shift() - 1; 
    map { [ (0) x $_, 1, (0) x ($n - $_) ] } 0..$n
}

for (<4 5 6>) {
  push @res, "\n$_:";
  push @res, join ' ', @$_ for identity_matrix $_;
}

say my $result = join "\n", @res;

my $ref = <<'EOD';

4:
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1

5:
1 0 0 0 0
0 1 0 0 0
0 0 1 0 0
0 0 0 1 0
0 0 0 0 1

6:
1 0 0 0 0 0
0 1 0 0 0 0
0 0 1 0 0 0
0 0 0 1 0 0
0 0 0 0 1 0
0 0 0 0 0 1
EOD

use Test::More;
chomp $ref;
is ($result, $ref);
done_testing;
