#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Idiomatically_determine_all_the_lowercase_and_uppercase_letters
#c# 2018-09-15 >RC
#p# OK

use strict;
use warnings;
use feature 'say';

my($lower,$upper);

for my $i (0..2**8-1) {
    my $c = chr($i);
    $lower .= $c if $c =~ /[[:lower:]]/;
    $upper .= $c if $c =~ /[[:upper:]]/;
}

say $lower;
say $upper;

use Test::More;
is ($lower, 'abcdefghijklmnopqrstuvwxyz');
is ($upper, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ');
done_testing();
