#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Increment_a_numerical_string
#c# 2018-08-13 <RC
#p# OK

use feature 'say';

my $s = "12345";
say $s++;

use Test::More;
is ($s, 12346);
done_testing;
