#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Input/Output_for_Lines_of_Text
#c# 2018-09-10 >RC
#p# OK
#i# RC cli: ref/lines_of_text.txt

use strict;
use warnings;

my $n = scalar <>; 

do_stuff(scalar <>) for 1..$n;

sub do_stuff { print $_[0] }

use Test::More;
is($n, "3\n");
done_testing;
