#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Integer_long_division
#c# 2021-09-21 >RC, 2021-09-22 >RC
#p# OK
#n# cosmetic upgrade

my @res;

use strict;
use warnings;
use feature 'say';

use utf8;
binmode(STDOUT, ':utf8');

sub long_division {
    my($n, $d) = @_;
    my %seen;

    my$cnt;
    my($numerator,$denominator) = (abs $n, abs $d);
    #my $negative = $n < 0 ^ $d < 0 ? '-' : '';
    my $negative = ($n < 0 xor $d < 0) ? '-' : '';

    my $fraction = sprintf '%d.', $numerator / $denominator;
    my $position = length $fraction;
    $numerator %= $denominator;
    while (!$seen{$numerator}) {
        return 0, $fraction =~ s/\.$//r unless $numerator;
        $cnt++;
        $seen{$numerator} = $position;
        $fraction  .= int 10 * $numerator / $denominator;
        $numerator  =     10 * $numerator % $denominator;
        $position++;
    }

    my $period = length($fraction) - $seen{$numerator};
    substr $fraction, $seen{$numerator}+(2*$_)+1, 0, "\N{COMBINING OVERLINE}" for 0 .. $period-1;
    $period, $negative . $fraction  # "$negative$fraction}"
}

push @res, sprintf  "%35s Period is %5d : %s", $_, long_division split '/', $_
    for <0/1 1/1 1/5 1/3 -1/3 1/7 -83/60 1/17 10/13 3227/555 476837158203125/9223372036854775808 1/149>; # aka 5**21/2**63

say my $result = join "\n", @res;

my $ref = <<'END';
                                0/1 Period is     0 : 0
                                1/1 Period is     0 : 1
                                1/5 Period is     0 : 0.2
                                1/3 Period is     1 : 0.3̅
                               -1/3 Period is     1 : -0.3̅
                                1/7 Period is     6 : 0.1̅4̅2̅8̅5̅7̅
                             -83/60 Period is     1 : -1.383̅
                               1/17 Period is    16 : 0.0̅5̅8̅8̅2̅3̅5̅2̅9̅4̅1̅1̅7̅6̅4̅7̅
                              10/13 Period is     6 : 0.7̅6̅9̅2̅3̅0̅
                           3227/555 Period is     3 : 5.81̅4̅4̅
476837158203125/9223372036854775808 Period is     0 : 0.0000516987882845642321427703791414387524127960205078125
                              1/149 Period is   148 : 0.0̅0̅6̅7̅1̅1̅4̅0̅9̅3̅9̅5̅9̅7̅3̅1̅5̅4̅3̅6̅2̅4̅1̅6̅1̅0̅7̅3̅8̅2̅5̅5̅0̅3̅3̅5̅5̅7̅0̅4̅6̅9̅7̅9̅8̅6̅5̅7̅7̅1̅8̅1̅2̅0̅8̅0̅5̅3̅6̅9̅1̅2̅7̅5̅1̅6̅7̅7̅8̅5̅2̅3̅4̅8̅9̅9̅3̅2̅8̅8̅5̅9̅0̅6̅0̅4̅0̅2̅6̅8̅4̅5̅6̅3̅7̅5̅8̅3̅8̅9̅2̅6̅1̅7̅4̅4̅9̅6̅6̅4̅4̅2̅9̅5̅3̅0̅2̅0̅1̅3̅4̅2̅2̅8̅1̅8̅7̅9̅1̅9̅4̅6̅3̅0̅8̅7̅2̅4̅8̅3̅2̅2̅1̅4̅7̅6̅5̅1̅
END

use Test::More;
chomp $ref;
is($result, $ref);
done_testing();
