#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Interactive_programming
#n# nocode
#c# 2018-08-13 <RC
#p# OK

# Perl doesn't have an interpreter, but there is an interactive debugger:
# 
# $ perl -de1
# 
# Loading DB routines from perl5db.pl version 1.3
# Editor support available.
# 
# Enter h or `h h' for help, or `man perldebug' for more help.
# 
# main::(-e:1):   1
#   DB<1> sub f {my ($s1, $s2, $sep) = @_; $s1 . $sep . $sep . $s2}
# 
#   DB<2> p f('Rosetta', 'Code', ':')
# Rosetta::Code
#   DB<3> q
# Alternative way:
# 
# $ perl
# # Write the script here and press Ctrl+D plus ENTER when finished (^D means Ctrl+D):
# sub f {my ($s1, $s2, $sep) = @_; $s1 . $sep . $sep . $s2};
# print f('Rosetta', 'Code', ':');
# ^D
# Rosetta::Code
# $
# Another:
# 
# $ perl -lpe '$_=eval||$@'
# sub f { join '' => @_[0, 2, 2, 1] }
# 
# f qw/Rosetta Code :/
# Rosetta::Code
