#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Palindromic_primes_in_base_16
#c# 2021-06-26 >RC
#p# OK

my $result;

use strict;
use warnings;

my $h;

    (1 x $_ ) !~ /^(11+)\1+$/  # test if prime
and $h = sprintf "%x", $_      # convert to hex
and $h eq reverse $h           # palindromic?
and $result .= "$h "
    for 1..500;

#(1 x $_ ) !~ /^(11+)\1+$/ and $h = sprintf("%x", $_) and $h eq reverse $h and $result .= "$h " for 1..500;

print "$result\n";

my $ref = '1 2 3 5 7 b d 11 101 151 161 191 1b1 1c1 ';

use Test::More;
chomp $ref;
is ($result, $ref);
done_testing;
