#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Palindromic_primes_of_distinct_two_digits
#c# 2021-12-10 NOT ON RC
#p# OK
#n# a(ba){1,} : why not 7/1, 7/6?  Just need to scan more candidates, or is there a Profound Mathematical Reason?
#n# or in degenerate case of a=b, one digit, for lengths: 19, 23, 317, 1031 (which are themselves primes)
#n# to-do: instead of listing, build table of generator-pair frequencies

my @res;

use strict;
use warnings;
use feature 'say';

$| = 1;

use Math::Prime::Util qw/is_prime/;

my $lo = 3; my $hi = 10;
#my $lo = 3; my $hi = 10_000;

for my $d ($lo..$hi) {
    my @pr = ();
    for my $a (<1 3 7 9>) {              # never 5
        for my $b (1..9) {               # never 0
            my $p = $a . "$b$a" x ($d-1);
            push @pr, [$a, $b] if is_prime $p
        }
    }
    printf "%d %s\n", 1+2*($d-1), join ' ', @{$pr[$_]} for 0..$#pr;
    push @res, sprintf "%d %s", 1+2*($d-1), join ' ', @{$pr[$_]} for 0..$#pr;
}

exit unless $hi == 10;
my $result = join "\n", @res;

my $ref = <<'EOD';
5 1 8
5 3 2
5 3 5
5 7 2
5 7 4
5 7 8
5 9 4
5 9 5
7 1 2
7 1 6
9 3 2
9 3 8
9 7 2
9 9 1
9 9 2
9 9 7
9 9 8
11 1 2
11 1 4
11 3 2
11 9 1
15 1 5
15 3 8
15 7 3
17 3 8
17 7 2
17 7 4
17 7 5
17 9 1
17 9 4
17 9 5
19 1 1
EOD

use Test::More;
chomp $ref;
is ($result, $ref);
done_testing();
