#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Pandigital_prime
#c# 2021-09-05, 2021-09-12 >RC
#p# OK
#n# my version, optional portion of task on RC

use strict;
use warnings;
use feature 'say';

use ntheory <is_prime forperm vecmax>;

my @p;

# as one-liner, but less clear (e.g. double use of topic var.)
# Raku: max (1..9).map: -> $size { |(1..$size).permutations».join.grep(&is-prime) }
# Perl:       forperm { my $n = join '', map { 1 + $_ } @_; push @p, $n if is_prime($n); } @{[1..$_]} for (4,7)
# Perl: map { forperm { my $n = join '', map { 1 + $_ } @_; push @p, $n if is_prime($n); } @{[1..$_]} }   (4,7)

#for my $c (1..9) {
for my $c (4,7) {
    forperm {
        my $n = join '', map { 1 + $_ } @_;
        push @p, $n if is_prime($n); 
    } @{[1..$c]};
}
say my $result1 = vecmax @p;

# optional
@p = ();
for my $c (0..7) {
    forperm {
        my $n = join '', @_;
        push @p, $n if $n !~ /^0/ and is_prime($n); 
    } @{[0..$c]};
}
say my $result2 = vecmax @p;

use Test::More;
is($result1,  7652413);
is($result2, 76540231);
done_testing;
