#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Parsing/RPN_calculator_algorithm
#c# 2018-08-20 <RC
#p# OK

use feature 'say';
my $result;

# RPN calculator
# Nigel Galloway April 2nd., 2012

$WSb = '(?:^|\s+)';
$WSa = '(?:\s+|$)';
$num = '([+-/]?(?:\.\d+|\d+(?:\.\d*)?))';
$op = '([-+*/^])';
sub myE {
  my $a = '('.$1.')'.$3.'('.$2.')';
  $a =~ s/\^/**/;
  return eval($a);
}
while ($_ = <DATA>)  {
  while (s/$WSb$num\s+$num\s+$op$WSa/' '.myE().' '/e)  {}
  $result .= ($_);
}

say $result; 

use Test::More;
is ($result, ' 3.0001220703125 ');
done_testing();

__END__
3 4 2 * 1 5 - 2 3 ^ ^ / +
