#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Pascal%27s_triangle
#c# 2018-08-20 <RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

# Here is a non-obvious version using bignum, which is limited to the first 23 rows because of the algorithm used:

use bignum;
sub pascal_line { $_[0] ? unpack "A(A6)*", 1000001**$_[0] : 1 }
sub pascal { $result .= "@{[map -+-$_, pascal_line $_]}\n" for 0..$_[0]-1 }

pascal(12);

say $result;

my $ref = <<'EOD';
1
1 1
1 2 1
1 3 3 1
1 4 6 4 1
1 5 10 10 5 1
1 6 15 20 15 6 1
1 7 21 35 35 21 7 1
1 8 28 56 70 56 28 8 1
1 9 36 84 126 126 84 36 9 1
1 10 45 120 210 252 210 120 45 10 1
1 11 55 165 330 462 462 330 165 55 11 1
EOD

use Test::More;
is ($result, $ref);
done_testing;
