#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Percentage_difference_between_images
#c# 2018-12-RC >RC
#p# OK

use Image::Imlib2;

my $img1 = Image::Imlib2->load('ref/Lenna50.jpg');
my $img2 = Image::Imlib2->load('ref/Lenna100.jpg');

$w = $img1->width;
$h = $img1->height;

for $x (0..$w-1) {
    for $y (0..$h-1) {
        my ($r1, $g1, $b1) = $img1->query_pixel($x, $y);
        my ($r2, $g2, $b2) = $img2->query_pixel($x, $y);
        $sum += abs($r1-$r2) + abs($g1-$g2) + abs($b1-$b2);
    }
}

printf "%% difference = %.4f\n", my $result = 100 * $sum / ($w * $h * 3 * 255);

use Test::More;
is($result, '1.77469091477737');
done_testing();

__END__

=={{header|Perl}}==
<lang perl>use Image::Imlib2;

my $img1 = Image::Imlib2->load('Lenna50.jpg') || die;
my $img2 = Image::Imlib2->load('Lenna100.jpg') || die;

$w = $img1->width;
$h = $img1->height;

for $x (0..$w) {
    for $y (0..$h) {
        my ($r1, $g1, $b1) = $img1->query_pixel($x, $y);
        my ($r2, $g2, $b2) = $img2->query_pixel($x, $y);
        $sum += abs($r1-$r2) + abs($g1-$g2) + abs($b1-$b2);
    }
}

printf "%% difference = %.4f\n", 100 * $sum / ($w * $h * 3 * 255);
</lang>
{{out}}
<pre>% difference = 1.7747</pre>
