#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Peripheral_drift_illusion
#c# 2021-09-20 NOT ON RC
#p# BROKEN
#f# RC file: peripheral-drift-2.svg
#n# close but not quite, 'defs' not enclosing 'block' group

use strict;
use warnings;

use SVG;

my $svg = SVG->new(width=>1200, height=>822);
$svg->rect(width=>"100%", height=>"100%", style=>{'fill'=>"#d3d004"});

#my $tag = $svg->defs(id => 'first and only');
#$tag->group(id => 'block');
my $tag = $svg->group(id => 'block');
$tag->polygon(points=>"-25,-25,-25,25,25,25", fill=>"white");
$tag->polygon(points=>"25,25,25,-25,-25,-25", fill=>"black");
$tag->rect(x=>"-20", y=>"-20", width=>"40", height=>"40", fill=>"#3250ff");

for my $X (1..15) {
    for my $Y (1..10) {
        my $r = int(($X + $Y) / 2) % 4 * 90;
        my $x = $X * 75;
        my $y = $Y * 75;
        my $a = $r > 0 ? "rotate($r,$x,$y) " : '';
        $tag->use( '-href' => qq{#block" transform="$a translate($x,$y)}); # outer quotes get added automatically
  }
}

open my $fh, '>', 'run/peripheral-drift-2.svg';
print $fh $svg->xmlify(-namespace=>'svg');
close $fh;
