#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Permutations_with_repetitions
#c# 2018-08-21 <RC
#p# OK

use feature 'say';
my $result;

use Algorithm::Combinatorics qw/tuples_with_repetition/;
$result .= join(' ', map { "[@$_]" } tuples_with_repetition([qw/A B C/],2)). "\n";

# Solving the crack problem:
use Algorithm::Combinatorics qw/tuples_with_repetition/;
my $iter = tuples_with_repetition([qw/A C K R/], 5);
my $tries = 0;
while (my $p = $iter->next) {
  $tries++;
  if (join('',@$p) eq 'CRACK') {
    $result .= "Found the combination after $tries tries!\n" ;
    last;
  }
  #die "Found the combination after $tries tries!\n" if join("",@$p) eq "CRACK";
}

say $result; 

my $ref = <<'EOD';
[A A] [A B] [A C] [B A] [B B] [B C] [C A] [C B] [C C]
Found the combination after 455 tries!
EOD

use Test::More;
is ($result, $ref);
done_testing();
