#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Pig_the_dice_game
#c# 2018-08-20 <RC
#p# OK
#=# RC pipe: R\nR\nR\nH\nR
#n# limiting to one player for automated testing

srand 123456;

use strict;
use warnings;
use feature 'say';
my $result;

# You can have as many players as you want, simply provide their names on the command line.

use Test::More;

#my @players = @ARGV;
my @players = qw(David);
my @scores = (0) x @players;
while( 1 ) {
	PLAYER: for my $i ( 0 .. $#players ) {
		my $name = $players[$i];
		my $score = $scores[$i];
		my $roundscore = 1 + int rand 6;
		print "$name, your score so far is $score.\n";
		print "You rolled a $roundscore.\n";
		next PLAYER if $roundscore == 1;
		while($score + $roundscore < 20) {
			print "Roll again, or hold [r/h]: ";
			my $answer = <>;
			$answer = 'h' unless defined $answer;
			if( $answer =~ /^h/i ) {
				$score += $roundscore;
				$scores[$i] = $score;
				print "Your score is now $score.\n";
				next PLAYER;
			} elsif( $answer =~ /^r/i ) {
				my $die = 1 + int rand 6;
				print "$name, you rolled a $die.\n";
				next PLAYER if $die == 1;
				$roundscore += $die;
				print "Your score for the round is now $roundscore.\n";
			} else {
				print "I did not understand that.\n";
			}
		}
		$score += $roundscore;
		print "With that, your score became $score.\n";
		print "You won!\n";
        ok $score == 21;
        done_testing;
        exit;
	}
}

