#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Pisano_period
#c# 2020-03-05 >RC
#p# OK
#n# getting a little golf-ish
#n# table hack, like Raku: ».fmt/batch/join

use strict;
use warnings;
use feature 'say';

use ntheory qw(primes factor_exp lcm);

my @res;

sub pisano_period_pp {
    my($a, $b, $n, $k) = (0, 1, $_[0]**$_[1]);
    while (++$k) {
        ($a, $b) = ($b, ($a+$b) % $n);
        return $k if $a == 0 and $b == 1;
    }
}

sub pisano_period {
    (lcm map { pisano_period_pp($$_[0],$$_[1]) } factor_exp($_[0])) or 1;  # factor_exp returns empty list for an arg. of 1
}

sub display { (sprintf "@{['%5d' x @_]}", @_) =~ s/(.{75})/$1\n/gr }

push @res, "Pisano periods for squares of primes p <= 50:";
push @res, display map { pisano_period_pp($_, 2) } @{primes(1,50)};
 
push @res, "Pisano periods for primes p <= 180:";
push @res, display map { pisano_period_pp($_, 1) } @{primes(1,180)};
 
push @res, "\nPisano periods for integers n from 1 to 180:";
push @res, display map { pisano_period($_) } 1..180;

#say "Pisano periods for squares of primes p <= 50:\n", display( map { pisano_period_pp($_, 2) } @{primes(1,  50)} ),
#  "\nPisano periods for primes p <= 180:\n",           display( map { pisano_period_pp($_, 1) } @{primes(1, 180)} ),
#"\n\nPisano periods for integers n from 1 to 180:\n",  display( map { pisano_period   ($_   ) }          1..180   );

say my $result = join "\n", @res;

my $ref = <<'END';
Pisano periods for squares of primes p <= 50:
    6   24  100  112  110  364  612  342 1104  406  930 2812 1640 3784 1504

Pisano periods for primes p <= 180:
    3    8   20   16   10   28   36   18   48   14   30   76   40   88   32
  108   58   60  136   70  148   78  168   44  196   50  208   72  108   76
  256  130  276   46  148   50  316  328  336  348  178

Pisano periods for integers n from 1 to 180:
    1    3    8    6   20   24   16   12   24   60   10   24   28   48   40
   24   36   24   18   60   16   30   48   24  100   84   72   48   14  120
   30   48   40   36   80   24   76   18   56   60   40   48   88   30  120
   48   32   24  112  300   72   84  108   72   20   48   72   42   58  120
   60   30   48   96  140  120  136   36   48  240   70   24  148  228  200
   18   80  168   78  120  216  120  168   48  180  264   56   60   44  120
  112   48  120   96  180   48  196  336  120  300   50   72  208   84   80
  108   72   72  108   60  152   48   76   72  240   42  168  174  144  120
  110   60   40   30  500   48  256  192   88  420  130  120  144  408  360
   36  276   48   46  240   32  210  140   24  140  444  112  228  148  600
   50   36   72  240   60  168  316   78  216  240   48  216  328  120   40
  168  336   48  364  180   72  264  348  168  400  120  232  132  178  120

END

use Test::More;
chomp $ref;
is($result, $ref);
done_testing;
