#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Polynomial_derivative
#c# 2021-11-xx >RC
#p# OK

my @res;

use strict;
use warnings;
use feature 'say';

for ([5], [4,-3], [-1,3,-2,1], [-1,6,5], [1,1,0,-1,-1]) {
    my @poly = @$_;
    push @res, 'Polynomial: ' . join ', ', @poly;
    $poly[$_] *= $_ for 0 .. $#poly;
    shift @poly;
    push @res, 'Derivative: ' . (@poly ? join', ', @poly : 0);
    push @res, '';
}

say my $result = join "\n", @res;

my $ref = <<'END';
Polynomial: 5
Derivative: 0

Polynomial: 4, -3
Derivative: -3

Polynomial: -1, 3, -2, 1
Derivative: 3, -4, 3

Polynomial: -1, 6, 5
Derivative: 6, 10

Polynomial: 1, 1, 0, -1, -1
Derivative: 1, 0, -3, -4
END

use Test::More;
is($result, $ref);
done_testing();

__END__

=={{header|Perl}}==
{{trans|xx}}
{{libheader|ntheory}}
<lang perl>
</lang>
{{out}}
<pre>
</pre>
