#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Power_set
#c# 2018-08-20 <RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

use Set::Object qw(set);

sub powerset {
    my $p = Set::Object->new( set() );
    foreach my $i (shift->elements) {
        $p->insert( map { set($_->elements, $i) } $p->elements );
    }
    return $p;
}

my $set = set(1, 2, 3);
my $powerset = powerset($set);

say $result = $powerset->as_string;

my $ref = 'Set::Object(Set::Object() Set::Object(1 2 3) Set::Object(1 2) Set::Object(1 3) Set::Object(1) Set::Object(2 3) Set::Object(2) Set::Object(3))';

use Test::More;
is ($result, $ref);
done_testing();
