#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Power_set
#c# 2018-08-20 <RC
#p# OK

use feature 'say';
my $result;

use ntheory "vecextract";
my @S = qw/a b c/;
my @PS = map { "[".join(" ",vecextract(\@S,$_))."]" } 0..2**scalar(@S)-1;
say $result = join("  ",@PS);

use Test::More;
is ($result, '[]  [a]  [b]  [a b]  [c]  [a c]  [b c]  [a b c]');
done_testing();
