#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Power_set
#c# 2018-08-20 <RC
#p# OK

use strict;
use warnings;
use feature 'say';

my @powerset;

sub powerset {
    @_ ? map { $_, [$_[0], @$_] } powerset(@_[1..$#_]) : [];
}

sub set_to_string {
    "{" . join(", ", map { ref $_ ? set_to_string(@$_) : $_ } @_) . "}"
}

@powerset = powerset(<1 2 3>);

say my $result = set_to_string(@powerset); #, "\n";

use Test::More;
is ($result, '{{}, {1}, {2}, {1, 2}, {3}, {1, 3}, {2, 3}, {1, 2, 3}}');
done_testing;
