#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Power_set
#c# 2018-08-20 <RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

use ntheory "forcomb";
my @S = qw/a b c/;
forcomb { $result .=  "[@S[@_]]  " } scalar(@S);

say $result;

use Test::More;
is ($result, '[]  [a]  [b]  [c]  [a b]  [a c]  [b c]  [a b c]  ');
done_testing;
