#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Power_set
#c# 2018-08-20 <RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

use ntheory "forcomb";
my @S = qw/a b c/;
for my $k (0..@S) {
  # Iterate over each $#S+1,$k combination.
  forcomb { $result .= "[@S[@_]]  " } @S,$k;
}

say $result;

use Test::More;
is ($result, '[]  [a]  [b]  [c]  [a b]  [a c]  [b c]  [a b c]  ');
done_testing();
