#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Power_set
#c# 2018-08-20 <RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

use Algorithm::Combinatorics "subsets";
my @S = ("a","b","c");
my @PS;
my $iter = subsets(\@S);
while (my $p = $iter->next) {
  push @PS, "[@$p]"
}
say $result = join("  ",@PS);

use Test::More;
is ($result, '[a b c]  [b c]  [a c]  [c]  [a b]  [b]  [a]  []');
done_testing;
