#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Prime_decomposition
#c# 2018-08-20 <RC
#p# OK

use strict;
use warnings;
use feature 'say';

sub prime_factors {
	my ($n, $d, @out) = (shift, 1);
	while ($n > 1 and $d++) {
		$n /= $d, push @out, $d until $n % $d;
	}
	@out
}

#say $result = "@{[prime_factors(1001)]}";
say my $result = join ' ', prime_factors(1001);

use Test::More;
is ($result, '7 11 13');
done_testing;
