#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Primes_with_digits_in_nondecreasing_order
#c# 2021-07-24 <RC
#p# OK

use strict;
use warnings;
use ntheory qw( primes );

my @want = grep ! /(.)(.)(??{$1 > $2 ? '' : '(*FAIL)'})/, @{ primes(1000) };
print my $result = "@want" =~ s/.{50}\K /\n/gr . "\n\ncount: " . @want . "\n";

my $ref = <<'EOD';
2 3 5 7 11 13 17 19 23 29 37 47 59 67 79 89 113 127
137 139 149 157 167 179 199 223 227 229 233 239 257
269 277 337 347 349 359 367 379 389 449 457 467 479
499 557 569 577 599 677

count: 50
EOD

use Test::More;
is ($result, $ref);
done_testing();
