#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Primalty_by_Wilson%27s_theorem
#c# 2020-01-05 >RC
#p# OK

use strict;
use warnings;
use feature 'say';

use ntheory qw(factorial);

my($ends_in_7, $ends_in_3);

sub is_wilson_prime {
    my($n) = @_;
    $n > 1 or return 0;
    (factorial($n-1) % $n) == ($n-1) ? 1 : 0;
}

for (0..50) { 
    my $m = 3 + 10*$_; 
    $ends_in_3 .= "$m " if is_wilson_prime($m);
    my $n = 7 + 10*$_; 
    $ends_in_7 .= "$n " if is_wilson_prime($n);
}

say $ends_in_3;
say $ends_in_7;

my $ref1 = '3 13 23 43 53 73 83 103 113 163 173 193 223 233 263 283 293 313 353 373 383 433 443 463 503 ';
my $ref2 = '7 17 37 47 67 97 107 127 137 157 167 197 227 257 277 307 317 337 347 367 397 457 467 487 ';

use Test::More;
is($ends_in_3, $ref1);
is($ends_in_7, $ref2);
done_testing;
