#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Priority_queue
#c# 2018-08-20 <RC
#p# OK

use feature 'say';
my $result;
# my @res;


# There are a few implementations on CPAN. Following uses Heap::Priority[1]

use 5.10.0;
use strict;
use Heap::Priority;

my $h = new Heap::Priority;

$h->highest_first(); # higher or lower number is more important
$h->add(@$_) for ["Clear drains",   3],
     ["Feed cat",     4],
     ["Make tea",     5],
     ["Solve RC tasks", 1],
     ["Tax return",     2];

$result .= "$_\n" while ($_ = $h->pop);

say $result; 
my $ref = <<'EOD';
Make tea
Feed cat
Clear drains
Tax return
Solve RC tasks
EOD

use Test::More;
is ($result, $ref);
done_testing();
