#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Priority_queue
#c# 2018-08-20 <RC
#p# OK

use strict;
use warnings;
use feature 'say';

use Heap::Priority;

my $h = new Heap::Priority;

$h->highest_first(); # higher or lower number is more important
$h->add(@$_) for ["Clear drains",   3],
     ["Feed cat",     4],
     ["Make tea",     5],
     ["Solve RC tasks", 1],
     ["Tax return",     2];

my $result;
$result .= "$_\n" while ($_ = $h->pop);
say $result;

my $ref = <<'EOD';
Make tea
Feed cat
Clear drains
Tax return
Solve RC tasks
EOD

use Test::More;
is ($result, $ref);
done_testing();
