#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Program_name
#c# 2018-08-20 <RC
#p# OK

use feature 'say';
my $result;

use strict;
use warnings;

sub main {
	my $program = $0;
	$result = "Program: $program";
}

unless(caller) { main; }

# $0 includes the full path if a script is run as say perl /some/dir/foo.pl. The FindBin module can give just the basename. This can be good for printing in diagnostics etc.
use FindBin;
print "Program name $FindBin::Script\n";

use Test::More;
is ($result, 'Program: P/Program_name');
done_testing;
