#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Pseudo-random_numbers/PCG32
#c# 2021-01-12 >RC
#p# OK

use strict;
use warnings;
use feature 'say';
#use bigint;
use Math::AnyNum qw(:overload);

my @res;

{ package PCG32;

    our($state,$incr);
    use constant mask32 => 2**32 - 1;
    use constant mask64 => 2**64 - 1;
    use constant const  => 6364136223846793005;

    sub new {
        my($seed, $iincr) = ($_[2], $_[4]);
        $seed  //= 1;
        $iincr //= 2;
        $incr  = $iincr << 1 | 1 & mask64;
        $state = (($incr + $seed) * const + $incr) & mask64;
    }

    sub next_int {
        my $shift  = ($state >> 18 ^ $state) >> 27 & mask32;
        my $rotate =  $state >> 59 & mask32;
        $state     = ($state * const + $incr) & mask64;
        ($shift >> $rotate) | $shift << (32 - $rotate) & mask32
    }
}

push @res, 'Seed: 1234567, first 5 values:';
my $rng = PCG32->new(seed => 42, incr => 54);
push @res, PCG32->next_int($rng) for 1..5;

my %h;
push @res, "\nSeed: 987654321, values histogram:";
$rng = PCG32->new( seed => 987654321, incr => 1 );
$h{int 5 * PCG32->next_int($rng)/2**32}++ for 1..100_000;
push @res, "$_ $h{$_}" for sort keys %h;

say my $result = join "\n", @res;

my $ref = <<'END';
Seed: 1234567, first 5 values:
2707161783
2068313097
3122475824
2211639955
3215226955

Seed: 987654321, values histogram:
0 20049
1 20022
2 20115
3 19809
4 20005
END

use Test::More;
chomp $ref;
is($result, $ref);
done_testing();
