#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/QR_decomposition
#c# 2019-02-10 >RC
#p# OK

use Math::GSL::Matrix qw/:all/;
use Math::GSL::Linalg qw/:all/;
#     use Math::GSL::Permutation qw/:all/;

my $Matrix = gsl_matrix_alloc(4,4);
#     map { gsl_matrix_set($Matrix, 0, $_, $_+1) } (0..3);

gsl_matrix_set($Matrix,1, 0, 2);
gsl_matrix_set($Matrix, 1, 1, 3);
gsl_matrix_set($Matrix, 1, 2, 4);
gsl_matrix_set($Matrix, 1, 3, 1);

__END__

   my Array @A = (
      [12, -51,   4],
      [ 6, 167, -68],
      [-4,  24, -41],
      [-1,   1,   0],
      [ 2,   0,   3]
   );

     my $permutation = gsl_permutation_alloc(4);
     gsl_permutation_init($permutation);
     my ($result, $signum) = gsl_linalg_LU_decomp($Matrix, $permutation);
     my $det = gsl_linalg_LU_det($Matrix, $signum);
     print "The value of the determinant of the matrix is $det \n";
