#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/QR_decomposition
#c# 2019-02-10 >RC
#p# OK

use Math::GSL::Matrix qw/:all/;
use Math::GSL::Linalg qw/:all/;

my $A = gsl_matrix_alloc(4,4);
#     map { gsl_matrix_set($Matrix, 0, $_, $_+1) } (0..3);

gsl_matrix_set($A,  12, -51,   4);
gsl_matrix_set($A,   6, 167, -68);
gsl_matrix_set($A,  -4,  24, -41);
gsl_matrix_set($A,  -1,   1,   0);
gsl_matrix_set($A,   2,   0,   3);

__END__

     my ($result, $signum) = gsl_linalg_LU_decomp($Matrix, $permutation);
     my $det = gsl_linalg_LU_det($Matrix, $signum);
     print "The value of the determinant of the matrix is $det \n";

   my $Q = householder(@A);
   $Q = transpose($Q);
   print-mat($Q, 'Q');
   # after householder, @A is now @R
   print-mat(@A, 'R');
   print-mat(multiply($Q, @A), 'check Q x R = A');

   my @x = [^11];
   my @y = [1, 6, 17, 34, 57, 86, 121, 162, 209, 262, 321];

   my @coef = polyfit(@x, @y, 2);

   say my $result =
      "\npolyfit:\n"~
      <constant X X^2>.fmt("%12s")~
      "\n"~
      @coef.fmt("%12.6f");

