#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Queue/Usage
#c# 2018-08-20 <RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

# Perl has built-in support to these operations:

my @queue = (); # we will simulate a queue in a array

push @queue, (1..5); # enqueue numbers from 1 to 5

$result .= (shift @queue) . "\n"; # dequeue

$result .= "array is empty\n" unless @queue; # is empty ?

my $n;
$result .= $n while($n = shift @queue); # dequeue all
$result .= "\n";
$result .= "array is empty\n" unless @queue; # is empty ?

say $result; 

my $ref = <<'EOD';
1
2345
array is empty
EOD

use Test::More;
is ($result, $ref);
done_testing();
