#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Words_from_neighbour_ones
#c# 2021-02-20 <RC
#p# OK

my @res;

use strict;
use warnings;
use feature 'say';

@ARGV = 'ref/unixdict.txt';
my $skew = join '', map { s/^.{9}\K.+//r } my @words = grep length() > 9, <>;
my %dict = map { $_ => 1 } grep length == 10, @words;
my %seen;
my $nextch = '.{10}(\\w)' x 8;
while( $skew =~ /^(\w)(?=$nextch)/gms ) {
    my $new = join '', @{^CAPTURE}, "\n";
    $dict{$new} and !$seen{$new}++ and push @res, $new;
}

say my $result = join '', @res;

my $ref = <<'EOD';
applicate
architect
astronomy
christine
christoph
committee
composite
constrict
construct
different
extensive
greenwood
implement
improvise
intercept
interpret
interrupt
philosoph
prescript
receptive
telephone
transcend
transport
transpose
EOD

use Test::More;
is ($result, $ref);
done_testing();
