#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/World_Cup_group_stage
#c# 2018-09-20 >RC
#p# OK

use strict;
use warnings;
use feature 'say';
my $result;

use Math::Cartesian::Product;

my(@histo,@aoa);
my @scoring = (0, 1, 3);
push @histo, [(0) x 10] for 1..4;
push @aoa,    [(0,1,2)] for 1..6;

for my $results (cartesian {@_} @aoa) {
    my @s;
    my @g = ([0,1],[0,2],[0,3],[1,2],[1,3],[2,3]);
    for (0..$#g) {
        my $r = $results->[$_]; # @$results[$_] more 6-like
        $s[$g[$_][0]] += $scoring[$r];
        $s[$g[$_][1]] += $scoring[2 - $r];
    }

    my @ss = sort @s;
    $histo[$_][$ss[$_]]++ for 0..$#s;
}

my $fmt = ('%3d ') x 10 . "\n";
$result .= sprintf $fmt, @$_ for reverse @histo;

say $result;

my $ref = <<'EOD';
  0   0   0   1  14 148 152 306   0 108 
  0   0   4  33 338 172 164  18   0   0 
  0  18 136 273 290   4   8   0   0   0 
108 306 184 125   6   0   0   0   0   0 
EOD

use Test::More;
is ($result, $ref);
done_testing;
