#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Write_language_name_in_3D_ASCII
#c# 2018-08-01 <RC
#p# OK

use feature 'say';
my $result;

use strict;
use warnings;
 
for my $tuple ([" ", 2], ["_", 1], [" ", 1], ["\\", 1], [" ", 11], ["|", 1], ["\n", 1],
               [" ", 1], ["|", 1], [" ", 3], ["|", 1],  [" ", 1],  ["_", 1], [" ", 1], ["\\", 1], [" ", 2], ["_", 2], ["|", 1], [" ", 1], ["|", 1], ["\n", 1],
               [" ", 1], ["_", 3], ["/", 1], [" ", 2],  ["_", 2],  ["/", 1], [" ", 1], ["|", 1],  [" ", 4], ["|", 1], ["\n", 1],
               ["_", 1], ["|", 1], [" ", 3], ["\\", 1], ["_", 3],  ["|", 1], ["_", 1], ["|", 1],  [" ", 3], ["_", 1], ["|", 1], ["\n", 1]
              ) {
    $result .= $tuple->[0] x $tuple->[1];
}

say $result; 
my $ref = <<'EOD';
  _ \           |
 |   | _ \  __| |
 ___/  __/ |    |
_|   \___|_|   _|
EOD
#Font taken from http://www.network-science.de/ascii/.

use Test::More;
is ($result, $ref);
done_testing;
