#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Write_float_arrays_to_a_text_file
#c# 2018-08-01 <RC
#p# OK
#f# RC file: sqrt-1.dat

use strict;
use warnings;
use feature 'say';
my $result;

sub writedat {
    my ($filename, $x, $y, $xprecision, $yprecision) = @_;
 
    open my $fh, ">", $filename;
 
    for my $i (0 .. $#$x) {
        printf $fh "%.*g\t%.*g\n", $xprecision||3, $x->[$i], $yprecision||5, $y->[$i];
    }
 
    close $fh;
}
 
my @x = (1, 2, 3, 1e11);
my @y = map sqrt, @x;
 
writedat("run/sqrt-1.dat", \@x, \@y);
