#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Calculating_the_value_of_e
#c# 2018-08-23
#p# OK

use strict;
use warnings;
use feature 'say';
my $sum;

use bignum;

sub factorial { my $r = 1; $r *= $_ for 1..shift; $r }

for my $n (0..35) { $sum += 1/factorial($n); } 
my $str = substr $sum, 0, 42;

say '2.71828182845904523536028747135266249775724709 ... (real e)';
print "$sum (unfiltered)\n";
print "$str (truncated)\n";

use Test::More;
is($str, '2.7182818284590452353602874713526624977572');
done_testing;
