#!/usr/local/bin/perl
#u# https://rosettacode.org/wiki/Calmo_numbers
#c# 2023-06-14 >RC
#p# OK

my @res;

use v5.36;

use List::Util 'all';
use experimental 'for_list';
use ntheory<is_prime divisors>;

sub c_divisors ($n) { my @d = divisors $n; pop @d; shift @d; @d }

for (2..1000) {
    my @d = c_divisors $_;
    next unless @d and 0 == @d%3;
    my @sums;
    for my($a,$b,$c) (@d) { push @sums, $a+$b+$c }
    push @res, $_ if all { is_prime $_ } @sums;
}

say my $result = join ' ', @res;

my $ref = '165 273 385 399 561 595 665 715 957';

use Test::More;
chomp $ref;
is($result, $ref);
done_testing;
