#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Canonicalize_CIDR
#c# 2020-07-09 <RC
#p# OK

use strict;
use warnings;
use feature 'say';

use Socket qw(inet_aton inet_ntoa);

# canonicalize a CIDR block: make sure none of the host bits are set
# if (!@ARGV) {
#   chomp(@ARGV = <>);
# }
#

$_ = '87.70.141.1/22';

#for (@ARGV) {

  # dotted-decimal / bits in network part
  my ($dotted, $size) = split m#/#;

  # get IP as binary string
  my $binary = sprintf "%032b", unpack('N', inet_aton $dotted);

  # Replace the host part with all zeroes
  substr($binary, $size) = 0 x (32 - $size);

  # Convert back to dotted-decimal
  $dotted = inet_ntoa(pack 'B32', $binary);

  # And output
  say my $result = "$dotted/$size";

#}

my $ref = '87.70.140.0/22';

use Test::More;
is ($result, $ref);
done_testing();
