#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Case-sensitivity_of_identifiers
#c# 2018-07-21 <RC
#p# OK

use strict;
use warnings;

# These variables are all different
my $dog='Benjamin';
my $Dog='Samba';
my $DOG='Bernie';
print (my $result = "The three dogs are named $dog, $Dog, and $DOG"); print "\n";

use Test::More;
is ($result, 'The three dogs are named Benjamin, Samba, and Bernie');
done_testing();
