#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Catamorphism
#c# 2018-07-22 <RC
#p# OK

use strict;
use warnings;
use feature 'say';
my $result;


# Perl's reduce function is in a standard package.

use List::Util 'reduce';
 
# note the use of the odd $a and $b globals
$result .= sprintf +(reduce {$a + $b} 1 .. 10). "\n";
 
# first argument is really an anon function; you could also do this:
sub func { $b & 1 ? "$a $b" : "$b $a" }
$result .= sprintf +(reduce \&func, 1 .. 10). "\n";


say $result; 
my $ref = <<'EOD';
55
10 8 6 4 2 1 3 5 7 9
EOD

use Test::More;
is ($result, $ref);
done_testing;
