#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Chaocipher
#c# 2018-08-28 >RC
#p# OK

use v5.36;

{ 

our(@left,@right); # global

sub init {
    @left  = split '', 'HXUCZVAMDSLKPEFJRIGTWOBNYQ';
    @right = split '', 'PTLNBQDEOYSFAVZKGJRIHWXUMC';
}

sub encode($letter) {
    my $index = index join('', @right), $letter;
    my $enc   = $left[$index];
    left_permute($index);
    right_permute($index);
    $enc
}

sub decode($letter) {
    my $index = index join('', @left), $letter;
    my $dec   = $right[$index];
    left_permute($index);
    right_permute($index);
    $dec
}

sub right_permute ($index) {
    rotate(\@right, $index + 1);
    rotate(\@right, 1, 2, 13);
}

sub left_permute ($index) {
    rotate(\@left, $index);
    rotate(\@left, 1, 1, 13);
}

sub rotate ($list, $n, $s = 0, $e = 0) {
    my @list = @{ $list };
    $s ? @list[0..$s-1, $s+$n..$e+$n-1, $s..$s+$n-1, $e+1..$#list]
         : @list[$n..$#list, 0..$n-1]
}

}

my($emsg,$dmsg);
init; $emsg .= encode($_) for split '', 'WELLDONEISBETTERTHANWELLSAID';
init; $dmsg .= decode($_) for split '', $emsg;

say my $result = "$emsg\n$dmsg\n";

my $ref = <<'EOD';
OMUUADCMTLZMXXMGXWPCOMUULPTA
WELLDONEISBETTERTHANWELLSAID
EOD

use Test::More;
is ($result, $ref);
done_testing;
