#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Collect_and_sort_square_numbers_in_ascending_order_from_three_lists
#c# 2021-12-10 <RC
#p# OK

use strict;
use warnings;
use feature 'say';

use List::Util qw( sum );
use ntheory qw( is_square );

my @lists = (
  [3,4,34,25,9,12,36,56,36],
  [2,8,81,169,34,55,76,49,7],
  [75,121,75,144,35,16,46,35]
);

my $sum = sum my @squares = grep is_square($_), sort { $a <=> $b } map @$_, @lists;
say my $result = "sum $sum  -  @squares";

my $ref = 'sum 690  -  4 9 16 25 36 36 49 81 121 144 169';

use Test::More;
is ($result, $ref);
done_testing;
