#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Combinations
#c# 2018-07-23 <RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

use Algorithm::Combinatorics qw/combinations/;
my @c = combinations( [0..4], 3 );
$result .= "@$_\n" for @c;

say $result;

my $ref = <<'END';
0 1 2
0 1 3
0 1 4
0 2 3
0 2 4
0 3 4
1 2 3
1 2 4
1 3 4
2 3 4
END

use Test::More;
is ($result, $ref);
done_testing();
