#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Combinations_with_repetitions
#c# 2018-07-23 <RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

use Algorithm::Combinatorics qw<combinations_with_repetition>;
my $iter = combinations_with_repetition([<iced jam plain>], 2);
while (my $p = $iter->next) {
  $result .= "@$p\n";
}

# Not an efficient way: generates them all in an array!
my $count =()= combinations_with_repetition([1..10],7);
$result .= "There are $count ways to pick 7 out of 10\n";

say $result;

my $ref = <<'END';
iced iced
iced jam
iced plain
jam jam
jam plain
plain plain
There are 11440 ways to pick 7 out of 10
END

use Test::More;
is ($result, $ref);
done_testing;
