#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Command-line_arguments
#c# 2019-09-21 <RC
#p# OK
#i# RC cli: ref/lines_of_numbers.txt mode=frobnicate iterations=42

my @res;

use strict;
use warnings;
use feature 'say';

# @ARGV is the array containing all command line parameters

push @res, join ':', @ARGV;
push @res, scalar @ARGV; 
push @res, $ARGV[1];
push @res, $ARGV[2];

#If you don't mind importing a module:
#use Getopt::Long;
#GetOptions ( 
#    'help|h'     => \my $help,
#    'verbose|v'  => \my $verbose,
#);

say my $result = join "\n", @res;

my $ref = <<'EOD';
ref/lines_of_numbers.txt:mode=frobnicate:iterations=42
3
mode=frobnicate
iterations=42
EOD

use Test::More;
chomp $ref;
is ($result, $ref);
done_testing();
