#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Comma_quibbling
#c# 2018-07-23 <RC
#p# OK

#use 5.01;

use strict;
use warnings;
use feature 'say';

my @res;
my $result;

sub comma_quibbling{
  my $last = pop // '';
  return '{'. (@_ ? (join ', ', @_).' and '.$last : $last).'}';
}

push @res, $_ for map {comma_quibbling(@$_)}
  [], [qw<ABC>], [<ABC DEF>], [<ABC DEF G H>];

say $result = join "\n", @res;

my $ref = <<'END';
{}
{ABC}
{ABC and DEF}
{ABC, DEF, G and H}
END

use Test::More;
chop $ref;
is ($result, $ref);
done_testing();
