#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Comma_quibbling
#c# 2018-07-23 <RC
#p# OK

use feature 'say';
my @result;
my $result;

use 5.01;
sub comma_quibbling{
  my $last = pop // '';
  return '{'. (@_ ? (join ', ', @_).' and '.$last : $last).'}';
}

push @result, $_ for map {comma_quibbling(@$_)}
  [], [qw(ABC)], [qw(ABC DEF)], [qw(ABC DEF G H)];

say $result = join "\n", @result;

my $ref = <<'END';
{}
{ABC}
{ABC and DEF}
{ABC, DEF, G and H}
END

use Test::More;
chop $ref;
is ($result, $ref);
done_testing();
