#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Common_list_elements
#c# 2021-02-25 >RC
#p# OK

use strict;
use warnings;
use feature 'say';

my %c;
my @nums = ([2,5,1,3,8,9,4,6], [3,5,6,2,9,8,4], [1,3,7,6,9]);
map { $c{$_}++ } @$_ for @nums;
say my $result = join ' ', grep { $c{$_} == @nums } sort keys %c;

# or as a one-liner
# map { print "$_ " if @nums == ++$c{$_} } @$_ for @nums

use Test::More;
is($result, '3 6 9');
done_testing();
