#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Comments
#t# nocode
#c# 2018-07-24 <RC
#p# OK

# Works with: Perl version 5.x
# Single line comment

# this is commented
# These may also be at the end of a line

my $var = 1; # this is the comment part
# Multi-line comments for inline documentation (Plain Old Documentation, or POD in Perl parlance) follow the format:

=pod

Here are my comments
this is multi-line

=cut
# Note that technically, both of the lines beginning with the equals sign must be surrounded on either side for compatibility with all "POD" parsers.
# Note also that any string beginning with an equals sign, and that appears in the initial column of a line, begins a multi-line comment. It does not have to be a POD "command:" the following are all valid:

=head1
=head4
=over 4
=Any Old String
# Such blocks always end in =cut.
# For more info, type at a command prompt (or into a search engine): "perldoc perlpod"
