#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Compound_data_type
#c# 2018-07-24 <RC
#p# OK
#n# re-write with more up-to-date Perl OO, or Moose?

use strict;
use warnings;
use feature 'say';

# Array
my @point1 = (3, 8);

# Hash
my %point2 = (
   x => 3,
   y => 8
);

# Class instance
package Point;
 
use Class::Struct;
struct(
    x => '$',
    y => '$',
);
 
my $point = Point->new(x => 3, y => 8);

use Test::More;
ok $point1[0] == 3 && $point1[1] == 8;
ok $point->x == 3 && $point->y == 8;
ok $point2{'y'} == 8;
ok $point2{'x'} == 3;
done_testing;
