#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Concurrent_computing
#t# skiptest
#c# 2018-07-24 <RC
#p# OK
#n# unsure how to test

srand 123456;

use strict;
use warnings;
use feature 'say';

use threads;
use Time::HiRes 'sleep';
 
$_->join for map {
    threads->create(sub {
        sleep rand; 
        print shift, "\n";
    }, $_)
} <Enjoy Rosetta Code>;

__END__

use Test::More;
is (length($result), 19);
like  ($result, qr/Enjoy/);
like  ($result, qr/Rosetta/);
like  ($result, qr/Code/);
done_testing;
