#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Concurrent_computing
#c# 2018-07-24 <RC
#p# OK

my @res;

use strict;
use warnings;
use feature 'say';

use Coro;
use Coro::Timer 'sleep';
 
$_->join for map {
    async {
        sleep rand; 
        push @res, @_;
    } $_
} <Enjoy Rosetta Code>;
 
say my $result = join ":", @res; 

use Test::More;
is (18, length $result);
like  ($result, qr/Enjoy/);
like  ($result, qr/Rosetta/);
like  ($result, qr/Code/);
done_testing;
