#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Constrained_random_points_on_a_circle
#c# 2018-12-03 >RC
#p# OK

srand 123456;

use strict;
use warnings;
use feature 'say';
my $result;
my(@points,@sample,@matrix);

my @range = -15..16;

for my $x (@range) {
    for my $y (@range) {
        my $radius = sqrt $x**2 + $y**2;
        push @points, [$x,$y] if 10 <= $radius and $radius <= 15
    }
}

push @sample, @points[int rand @points] for 1..100;
push @matrix, ' ' x @range for 1..@range;
substr $matrix[15+$$_[1]], 15+$$_[0], 1, '*' for @sample;
$result .= join(' ', split '', $_) . "\n" for @matrix;

say $result;

my $ref = <<'EOD';
                                                               
                                  *   * *                      
                              *     *   *                      
                        *     *   *                            
                                  *   *                        
          *                 * *               *                
                *                         *                    
      *       * *                                 *            
    *                                             * *          
          *   *                                                
  *                                                       *    
      *   *                                       * * * * *    
                                                      *        
                                                               
        *                                         * *          
      *                                                        
  *                                                 *   * *    
                                                        * *    
    * *                                           *            
  *                                                     * *    
  * *     *                                             *      
        * *   *                                                
        *                                     *   *     *      
                *                         *                    
              *                             *                  
                              *         *       *   *          
          * *       *       *           *                      
            *   *     *                   *   *                
                  *       *                                    
                          *                                    
                                                               
                                                               
EOD

use Test::More;
is($result, $ref);
done_testing;
