#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Coprimes
#c# 2021-04-23 >RC
#p# OK

my @res;

use strict;
use warnings;
use feature 'say';

use  ntheory 'gcd';

#push @res, sprintf "%7s %s", (gcd(@$_) == 1 ? 'Coprime' : ''), join ', ', @$_ 
push @res, sprintf "%7s %s", (1 == gcd @$_ and 'Coprime'), join ', ', @$_ 
     for [21,15], [17,23], [36,12], [18,29], [60,15], [21,22,25,31,143];

say my $result = join "\n", @res;

my $ref = <<'END';
        21, 15
Coprime 17, 23
        36, 12
Coprime 18, 29
        60, 15
Coprime 21, 22, 25, 31, 143
END

use Test::More;
chomp $ref;
is($result, $ref);
done_testing;
