#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Count_occurrences_of_a_substring
#c# 2018-07-25 <RC
#p# OK

use strict;
use warnings;
use feature 'say';
my $result;

sub countSubstring {
  my $str = shift;
  my $sub = quotemeta(shift);
  my $count = () = $str =~ /$sub/g;
  return $count;
#  or return scalar( () = $str =~ /$sub/g );
}
 
$result .= countSubstring("the three truths","th"). "\n";
$result .= countSubstring("ababababab","abab").     "\n";

say $result; 

my $ref = <<'EOD';
3
2
EOD

use Test::More;
is ($result, $ref);
done_testing;
