#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Count_in_octal
#c# 2018-07-02 <RC, 2019-12-11 <RC
#p# OK

my($result1,$result2);

use strict;
use warnings;
no warnings 'uninitialized'; # $1 capture sometimes empty

# Since task says "system register", I take it to mean "no larger than machine native integer limit":

# DH: ha ha ha
#use POSIX;
#use bigint;
#printf "%o\n", $_ for (0 .. POSIX::UINT_MAX);

#Otherwise:

my $i = 0;
$result1 .= sprintf "%o\n", $i++ until $i == 17;

print $result1;

$_ = 0;
{ (s/([^7])?(7*)$/ $1 + 1 . $2 =~ tr!7!0!r /e and $_ > 20 and last) while $result2 .= "$_\n" } # curlies give a block to exit with 'last'

#(s/([^7])?(7*)$/ $1 + 1 . $2 =~ tr!7!0!r /e and $_ > 20 and goto DONE) while $result2 .= "$_\n"; DONE: # I considered 'goto'...

#s/([^7])?(7*)$/ $1 + 1 . $2 =~ tr!7!0!r /e while print "$_\n"; # this is on RC (never terminates)

my $ref = <<'EOD';
0
1
2
3
4
5
6
7
10
11
12
13
14
15
16
17
20
EOD

use Test::More;
is ($result1, $ref);
is ($result2, $ref);
done_testing;
