#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Cousin_primes
#c# 2021-03-xx >RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

use ntheory 'is_prime';

my @cp;
map { push @cp, [$_,$_+4] if is_prime($_) and is_prime($_+4) } 2..199;
print '(' . join(' ', @$_) . ') ' for @cp; print "\n";

is_prime($_) and is_prime($_+4) and print "($_ @{[$_+4]}) " for 2..999; # for RC?
is_prime($_) and is_prime($_+4) and $result .= "($_ @{[$_+4]}) " for 2..999;

my $ref = <<'END';
(3 7) (7 11) (13 17) (19 23) (37 41) (43 47) (67 71) (79 83) (97 101) (103 107) (109 113) (127 131) (163 167) (193 197) (223 227) (229 233) (277 281) (307 311) (313 317) (349 353) (379 383) (397 401) (439 443) (457 461) (463 467) (487 491) (499 503) (613 617) (643 647) (673 677) (739 743) (757 761) (769 773) (823 827) (853 857) (859 863) (877 881) (883 887) (907 911) (937 941) (967 971) 
END

use Test::More;
chomp $ref;
is($result, $ref);
done_testing();

__END__

=={{header|Perl}}==
{{libheader|ntheory}}
<lang perl></lang>
{{out}}
<pre></pre>
