#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Cullen_and_Woodall_numbers
#c# 2022-01-15 >RC
#p# OK

my @res;

use strict;
use warnings;
use feature 'say';

use bigint;
use ntheory 'is_prime';
use constant Inf  => 1e10;

sub cullen {
    my($n,$c) = @_;
    ($n * 2**$n) + $c;
}

my($m,$n,$b);

$m = 20; ($n,$b) = (0,'');
push @res, "First $m Cullen numbers:";
$b .= do { $n < $m ? (++$n and cullen($_,1) . ' ') : last } for 1 .. Inf;
push @res, "$b\n";

$m = 20; ($n,$b) = (0,'');
push @res, "First $m Woodall numbers:";
$b .= do { $n < $m ? (++$n and cullen($_,-1) . ' ') : last } for 1 .. Inf;
push @res, "$b\n";

$m = 5; ($n,$b) = (0,'');
push @res, "First $m Cullen primes: (in terms of n)";
$b .= do { $n < $m ? (!!is_prime(cullen $_,1) and ++$n and "$_ ") : last } for 1 .. Inf;
push @res, "$b\n";

$m = 12; ($n,$b) = (0,'');
push @res, "First $m Woodall primes: (in terms of n)";
$b .= do { $n < $m ? (!!is_prime(cullen $_,-1) and ++$n and "$_ ") : last } for 1 .. Inf;
push @res, "$b\n";

say my $result = join "\n", @res;

my $ref = <<'END';
First 20 Cullen numbers:
3 9 25 65 161 385 897 2049 4609 10241 22529 49153 106497 229377 491521 1048577 2228225 4718593 9961473 20971521 

First 20 Woodall numbers:
1 7 23 63 159 383 895 2047 4607 10239 22527 49151 106495 229375 491519 1048575 2228223 4718591 9961471 20971519 

First 5 Cullen primes: (in terms of n)
1 141 4713 5795 6611 

First 12 Woodall primes: (in terms of n)
2 3 6 30 75 81 115 123 249 362 384 462 
END

use Test::More;
is($result, $ref);
done_testing();
