#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Cyclotomic_Polynomial
#c# 2020-01-30 >RC, 2020-01-31 <RC
#p# OK
#n# post in haste, repent at leisure (kudos to trizen++ for cleaning up my mess)
#n# 2023-03-23 something about 5.32.1 is special -- earlier and later versions slower
#n# over 50x slower with v5.36? Now takes 30m for '<=4' (compare to old 'full' run) Do one fewer term in 2nd part...
#n# 2219.698u 4.298s 37:06.13 99.9% for '<= 9' in 2nd part

my @res;

use strict;
use warnings;
use feature 'say';

use feature 'say';
use List::Util qw(first);
use Math::Polynomial::Cyclotomic qw(cyclo_poly_iterate);

push @res, 'First 30 cyclotomic polynomials:';
my $it = cyclo_poly_iterate(1);
push @res, "$_: " . $it->() for 1 .. 30;

push @res, "\nSmallest cyclotomic polynomial with n or -n as a coefficient:";
$it = cyclo_poly_iterate(1);

for (my ($n, $k) = (1, 1) ; $n <= 3 ; ++$k) {
    my $poly = $it->();
    while (my $c = first { abs($_) == $n } $poly->coeff) {
        push @res, "CP $k has coefficient with magnitude = $n";
        say "CP $k has coefficient with magnitude = $n";
        $n++;
    }
}

say my $result = join "\n", @res;

my $ref = <<'EOD';
First 30 cyclotomic polynomials:
1: (x - 1)
2: (x + 1)
3: (x^2 + x + 1)
4: (x^2 + 1)
5: (x^4 + x^3 + x^2 + x + 1)
6: (x^2 - x + 1)
7: (x^6 + x^5 + x^4 + x^3 + x^2 + x + 1)
8: (x^4 + 1)
9: (x^6 + x^3 + 1)
10: (x^4 - x^3 + x^2 - x + 1)
11: (x^10 + x^9 + x^8 + x^7 + x^6 + x^5 + x^4 + x^3 + x^2 + x + 1)
12: (x^4 - x^2 + 1)
13: (x^12 + x^11 + x^10 + x^9 + x^8 + x^7 + x^6 + x^5 + x^4 + x^3 + x^2 + x + 1)
14: (x^6 - x^5 + x^4 - x^3 + x^2 - x + 1)
15: (x^8 - x^7 + x^5 - x^4 + x^3 - x + 1)
16: (x^8 + 1)
17: (x^16 + x^15 + x^14 + x^13 + x^12 + x^11 + x^10 + x^9 + x^8 + x^7 + x^6 + x^5 + x^4 + x^3 + x^2 + x + 1)
18: (x^6 - x^3 + 1)
19: (x^18 + x^17 + x^16 + x^15 + x^14 + x^13 + x^12 + x^11 + x^10 + x^9 + x^8 + x^7 + x^6 + x^5 + x^4 + x^3 + x^2 + x + 1)
20: (x^8 - x^6 + x^4 - x^2 + 1)
21: (x^12 - x^11 + x^9 - x^8 + x^6 - x^4 + x^3 - x + 1)
22: (x^10 - x^9 + x^8 - x^7 + x^6 - x^5 + x^4 - x^3 + x^2 - x + 1)
23: (x^22 + x^21 + x^20 + x^19 + x^18 + x^17 + x^16 + x^15 + x^14 + x^13 + x^12 + x^11 + x^10 + x^9 + x^8 + x^7 + x^6 + x^5 + x^4 + x^3 + x^2 + x + 1)
24: (x^8 - x^4 + 1)
25: (x^20 + x^15 + x^10 + x^5 + 1)
26: (x^12 - x^11 + x^10 - x^9 + x^8 - x^7 + x^6 - x^5 + x^4 - x^3 + x^2 - x + 1)
27: (x^18 + x^9 + 1)
28: (x^12 - x^10 + x^8 - x^6 + x^4 - x^2 + 1)
29: (x^28 + x^27 + x^26 + x^25 + x^24 + x^23 + x^22 + x^21 + x^20 + x^19 + x^18 + x^17 + x^16 + x^15 + x^14 + x^13 + x^12 + x^11 + x^10 + x^9 + x^8 + x^7 + x^6 + x^5 + x^4 + x^3 + x^2 + x + 1)
30: (x^8 + x^7 - x^5 - x^4 - x^3 + x + 1)

Smallest cyclotomic polynomial with n or -n as a coefficient:
CP 1 has coefficient with magnitude = 1
CP 105 has coefficient with magnitude = 2
CP 385 has coefficient with magnitude = 3
EOD
#CP 1365 has coefficient with magnitude = 4
#CP 1785 has coefficient with magnitude = 5
#CP 2805 has coefficient with magnitude = 6
#CP 3135 has coefficient with magnitude = 7
#CP 6545 has coefficient with magnitude = 8
#CP 6545 has coefficient with magnitude = 9

use Test::More;
chomp $ref;
is ($result, $ref);
done_testing();
