#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Cyclotomic_Polynomial
#c# 2020-01-30 >RC
#p# OK
#n# didn't get to 10: exponent too large at /usr/local/lib/perl5/site_perl/5.30.0/Math/Polynomial/Cyclotomic.pm line 29.
#n# slow: 8044.630u 14.225s 2:14:29.80 99.8% 

my @res;

use strict;
use warnings;
use feature 'say';

use Math::Polynomial::Cyclotomic qw(cyclo_poly_iterate);
 
push @res, 'First 30 cyclotomic polynomials:';
my $it = cyclo_poly_iterate(1);
push @res, "$_: " . $it->() for 1..30;

push @res, "\nSmallest cyclotomic polynomial with n or -n as a coefficient:";

$it = cyclo_poly_iterate(1);
$it->();
my $cnt = my $int = 1;
push @res, "CP $int has coefficient with magnitude = 1";
$int++;
while ($int <= 4) {
    $cnt++;
    my $poly = $it->();
    next unless $poly =~ / $int\*/;
    push @res, "CP $cnt has coefficient with magnitude = $int";
    $int++;
    if ($poly =~ / $int\*/) {
        push @res, "CP $cnt has coefficient with magnitude = $int";
        $int++;
    }
}
 
say my $result = join "\n", @res;

my $ref = <<'END';
First 30 cyclotomic polynomials:
1: (x - 1)
2: (x + 1)
3: (x^2 + x + 1)
4: (x^2 + 1)
5: (x^4 + x^3 + x^2 + x + 1)
6: (x^2 - x + 1)
7: (x^6 + x^5 + x^4 + x^3 + x^2 + x + 1)
8: (x^4 + 1)
9: (x^6 + x^3 + 1)
10: (x^4 - x^3 + x^2 - x + 1)
11: (x^10 + x^9 + x^8 + x^7 + x^6 + x^5 + x^4 + x^3 + x^2 + x + 1)
12: (x^4 - x^2 + 1)
13: (x^12 + x^11 + x^10 + x^9 + x^8 + x^7 + x^6 + x^5 + x^4 + x^3 + x^2 + x + 1)
14: (x^6 - x^5 + x^4 - x^3 + x^2 - x + 1)
15: (x^8 - x^7 + x^5 - x^4 + x^3 - x + 1)
16: (x^8 + 1)
17: (x^16 + x^15 + x^14 + x^13 + x^12 + x^11 + x^10 + x^9 + x^8 + x^7 + x^6 + x^5 + x^4 + x^3 + x^2 + x + 1)
18: (x^6 - x^3 + 1)
19: (x^18 + x^17 + x^16 + x^15 + x^14 + x^13 + x^12 + x^11 + x^10 + x^9 + x^8 + x^7 + x^6 + x^5 + x^4 + x^3 + x^2 + x + 1)
20: (x^8 - x^6 + x^4 - x^2 + 1)
21: (x^12 - x^11 + x^9 - x^8 + x^6 - x^4 + x^3 - x + 1)
22: (x^10 - x^9 + x^8 - x^7 + x^6 - x^5 + x^4 - x^3 + x^2 - x + 1)
23: (x^22 + x^21 + x^20 + x^19 + x^18 + x^17 + x^16 + x^15 + x^14 + x^13 + x^12 + x^11 + x^10 + x^9 + x^8 + x^7 + x^6 + x^5 + x^4 + x^3 + x^2 + x + 1)
24: (x^8 - x^4 + 1)
25: (x^20 + x^15 + x^10 + x^5 + 1)
26: (x^12 - x^11 + x^10 - x^9 + x^8 - x^7 + x^6 - x^5 + x^4 - x^3 + x^2 - x + 1)
27: (x^18 + x^9 + 1)
28: (x^12 - x^10 + x^8 - x^6 + x^4 - x^2 + 1)
29: (x^28 + x^27 + x^26 + x^25 + x^24 + x^23 + x^22 + x^21 + x^20 + x^19 + x^18 + x^17 + x^16 + x^15 + x^14 + x^13 + x^12 + x^11 + x^10 + x^9 + x^8 + x^7 + x^6 + x^5 + x^4 + x^3 + x^2 + x + 1)
30: (x^8 + x^7 - x^5 - x^4 - x^3 + x + 1)

Smallest cyclotomic polynomial with n or -n as a coefficient:
CP 1 has coefficient with magnitude = 1
CP 105 has coefficient with magnitude = 2
CP 385 has coefficient with magnitude = 3
CP 1365 has coefficient with magnitude = 4
END
#CP 1785 has coefficient with magnitude = 5
#CP 2805 has coefficient with magnitude = 6
#CP 3135 has coefficient with magnitude = 7
#CP 6545 has coefficient with magnitude = 8
#CP 6545 has coefficient with magnitude = 9
#CP 10465 has coefficient with magnitude = 10

use Test::More;
chomp $ref;
is($result, $ref);
done_testing();
