#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Juggler_sequence
#c# 2021-08-19 <RC
#p# OK
#n# GMP is vital here (no diff with Math::GMPz)

my @res;

use strict;
use warnings;
use feature 'say';

use Math::BigInt lib => 'GMP';

#print "       n  l(n) i(n)  h(n) or d(n)\n";
##print " -------  ---- ----  ------------\n";
for my $i ( 20 .. 39, 113, 173, 193, 2183, 11229, 15065, 15845, 30817, 48443, 275485, 1267909, 2264915,
          # 5812827, 7110201  # about 9min when included
) {
    my $max = my $n = Math::BigInt->new($i);
    my $at = my $count = 0;
    while( $n > 1 ) {
        $n = sqrt( $n & 1 ? $n ** 3 : $n );
        $count++;
        $n > $max and ($max, $at) = ($n, $count);
    }

    if( length $max < 27 ) {
        push @res, sprintf "%8d  %4d  %3d  %s", $i, $count, $at, $max;
    } else {
        push @res, sprintf "%8d  %4d  %3d  d(n) = %d digits", $i, $count, $at, length $max;
    }
}

say my $result = join "\n", @res;

my $ref = <<'EOD';
      20     3    0  20
      21     9    4  140
      22     3    0  22
      23     9    1  110
      24     3    0  24
      25    11    3  52214
      26     6    3  36
      27     6    1  140
      28     6    3  36
      29     9    1  156
      30     6    3  36
      31     6    1  172
      32     6    3  36
      33     8    2  2598
      34     6    3  36
      35     8    2  2978
      36     3    0  36
      37    17    8  24906114455136
      38     3    0  38
      39    14    3  233046
     113    16    9  d(n) = 27 digits
     173    32   17  d(n) = 82 digits
     193    73   47  d(n) = 271 digits
    2183    72   32  d(n) = 5929 digits
   11229   101   54  d(n) = 8201 digits
   15065    66   25  d(n) = 11723 digits
   15845   139   43  d(n) = 23889 digits
   30817    93   39  d(n) = 45391 digits
   48443   157   60  d(n) = 972463 digits
  275485   225  148  d(n) = 1909410 digits
 1267909   151   99  d(n) = 1952329 digits
 2264915   149   89  d(n) = 2855584 digits
EOD
 #5812827   135   67  d(n) = 7996276 digits
 #7110201   205  119  d(n) = 89981517 digits

use Test::More;
chomp $ref;
is ($result, $ref);
done_testing();
