#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Empty_directory
#c# 2018-07-31 <RC
#p# OK

use strict;
use warnings;

sub dir_is_empty_simple {!<$_[0]/*>}

# This version however doesn't catch 'hidden' files that start with a dot.
# May be good for quick one-liners or in some special cases when you are sure that there are no 'hidden' files or they doesn't play any role.
# Unfortunalety, BSD glob() doesn't handle inverted character class. If it did, this pattern could be used: {.[^.],}* (this works well in bash). But it doesn't, so there's a

use IO::Dir;
sub dir_is_empty { !grep !/^\.{1,2}\z/, IO::Dir->new(@_)->read }

my $r1 = dir_is_empty("ref/test");
my $r2 = dir_is_empty("ref/test/dir1");
my $r3 = dir_is_empty("ref/test/dir2");
my $r4 = dir_is_empty("ref/test/dir3");

use Test::More;
is ($r1 . $r2 . $r3, '');
is ($r4, 1);
done_testing;
