#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Entropy/Narcissist
#c# 2018-07-31 <RC
#p# OK

use v5.36;
 
sub log2 {
   my $number = shift ;
   return log( $number ) / log( 2 ) ;
}
 
open my $fh, '<', $0 || die "Can't open $0!\n";
my %frequencies ;
my $totallength = 0 ;
while ( my $line = <$fh> ) {
   chomp $line ;
   next if $line =~ /^$/ ;
   $frequencies{ $_ }++ for split '', $line;
   $totallength += length ( $line ) ;
}
close $fh ;

my $infocontent = 0 ;
for my $letter ( keys %frequencies ) {
   my $content = $frequencies{ $letter } / $totallength ;
   $infocontent += $content * log2( $content ) ;
}
$infocontent *= -1 ;
say "The information content of the source file is $infocontent !" ;

use Test::More;
like($infocontent, qr/^4\.88/);
done_testing;
