#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Environment_variables
#c# 2018-07-31 <RC
#p# OK

use feature 'say';

# The %ENV hash maps environment variables to their values:
say my $result1 = $ENV{HOME};

# The POSIXmodule also has getenv() which is the same thing as a function.
use POSIX 'getenv';
say my $result2 = getenv("HOME");

use Test::More;
is ($result1, $result2);
ok rindex($result1,'/') > 0;
done_testing();
