#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Equilibrium_index
#c# 2018-07-31 <RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

sub eq_index {
    my ( $i, $sum, %sums ) = ( 0, 0 );
 
    for (@_) {
        push @{ $sums{ $sum * 2 + $_  } }, $i++;
        $sum += $_;
    }
 
    return join ' ', @{ $sums{$sum} || [] }, "\n";
}
 
$result .= eq_index < -7  1  5  2 -4  3  0 >; # 3 6
$result .= eq_index <  2  4  6             >; # (no eq point)
$result .= eq_index <  2  9  2             >; # 1
$result .= eq_index <  1 -1  1 -1  1 -1  1 >; # 0 1 2 3 4 5 6

say $result;

my $ref = <<'EOD';
3 6 

1 
0 1 2 3 4 5 6 
EOD

use Test::More;
is ($result, $ref);
done_testing;
