#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Erdős-primes
#c# 2021-03-22 >RC
#p# OK

my @res;

use strict;
use warnings;
use feature 'say';

use utf8;
binmode(STDOUT, ':utf8');

use List::AllUtils 'before';
use ntheory qw<is_prime factorial>;

#sub comma { reverse ((reverse shift) =~ s/(.{3})/$1,/gr) =~ s/^,//r }

sub is_erdos {
    my($n) = @_; my $k; 
    return unless is_prime($n);
    while ($n > factorial($k++)) { return if is_prime $n-factorial($k) }
    'True'
}

my(@Erdős,$n);
do { push @Erdős, $n if is_erdos(++$n) } until $n >= 1e6;

@res = 'Erdős primes < ' . (my $max = 2500) . ':';
push @res, join ' ', before { $_ > 2500 } @Erdős;
push @res, "\nThe Erdős prime #" . @Erdős . ' is ' . $Erdős[-1];

say my $result = join "\n", @res;
#exit;

my $ref = <<'END';
Erdős primes < 2500:
2 101 211 367 409 419 461 557 673 709 769 937 967 1009 1201 1259 1709 1831 1889 2141 2221 2309 2351 2411 2437

The Erdős prime #7875 is 999721
END

use Test::More;
chomp $ref;
is($result, $ref);
done_testing();
