#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Euler%27s_sum_of_powers_conjecture
#c# 2018-07-31 <RC
#p# OK
#n# brute force approach

my $result;

use strict;
use warnings;
use feature 'say';

use constant MAX => 250;
my @p5 = (0,map { $_**5 } 1 .. MAX-1);
my $s = 0;
my %p5 = map { $_ => $s++ } @p5;
LOOP: 
for my $x0 (1..MAX-1) {
  for my $x1 (1..$x0-1) {
    for my $x2 (1..$x1-1) {
      for my $x3 (1..$x2-1) {
        my $sum = $p5[$x0] + $p5[$x1] + $p5[$x2] + $p5[$x3];
        if ($p5{$sum}) {
            say $result = "$x3 $x2 $x1 $x0 $p5{$sum}";
            last LOOP;
        }
      }
    }
  }
}

use Test::More;
is ($result, '27 84 110 133 144');
done_testing();
