#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Even_or_odd
#c# 2018-08-01 <RC
#p# OK

my($result1, $result2);

use strict;
use warnings;
use feature 'say';

$result1 .= "$_ is " . (<even odd>)[$_ % 2]    . "\n" for 0..10;
$result2 .= "$_ is " . ($_%2 ? 'odd' : 'even') . "\n" for 0..10;

say $result1;

my $ref = <<'EOD';
0 is even
1 is odd
2 is even
3 is odd
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is odd
10 is even
EOD

use Test::More;
is ($result1, $ref);
is ($result2, $ref);
done_testing;
