#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Executable_library
#c# 2018-08-01 <RC
#p# OK

use feature 'say';
my $result;

# Main program in file test.pl:use Hailstone;
use strict;
use warnings;

use lib 'lib';
require Hailstone;
 
my %seqs;
for (1 .. 100_000) {
    $seqs{Hailstone::len($_)}++;
}
 
my ($most_frequent) = sort {$seqs{$b} <=> $seqs{$a}} keys %seqs;
say $result = "Most frequent length: $most_frequent ($seqs{$most_frequent} occurrences)\n";

#seq of 27 - 112 elements: 27 82 41 124 62 31 94 47 142 ... 10 5 16 8 4 2 1
#Longest sequence is for 77031: 351
#Running the main program:% perl test.pl
#Most frequent length: 72 (1467 occurrences)

my $ref = <<'EOD';
Most frequent length: 72 (1467 occurrences)
EOD

use Test::More;
is ($result, $ref);
done_testing;
