#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Execute_a_system_command
#c# 2018-08-01 <RC , 2018-11-16 >RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

my @results = qx(uname);  # run command and return STDOUT as a string
 
push @results, `uname`;    # same, alternative syntax
 
push @results, system "uname";           # run command and return exit status; STDOUT of command goes program STDOUT
 
push @results, `uname`;            # same, but with back quotes
 
#exec "uname";             # replace current process with another

#http://perldoc.perl.org/perlipc.html#Using-open()-for-IPC
#http://perldoc.perl.org/IPC/Open3.html

say $result = join "\n", @results;; 

my $os = `uname`; chomp $os;
my $ref = <<"EOD";
$os

$os

0
$os
EOD

use Test::More;
is ($result, $ref);
done_testing();
