#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Factors_of_an_integer
#c# 2018-08-03 <RC
#p# OK

my($result1,$result2);

use strict;
use warnings;
use feature 'say';

use ntheory qw/divisors fordivisors/;

fordivisors { $result1 .= "$_ " } 12345678;  chop $result1;
say $result2 = join " ", divisors(12345678);

my $ref = '1 2 3 6 9 18 47 94 141 282 423 846 14593 29186 43779 87558 131337 262674 685871 1371742 2057613 4115226 6172839 12345678';

use Test::More;
is ($result1, $ref);
is ($result2, $ref);
done_testing;
