#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Factorial
#c# 2018-08-03 <RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

# recursive
sub factorial
{
  my $n = shift;
  ($n == 0)? 1 : $n*factorial($n-1);
}

say $result = factorial(5);

use Test::More;
is ($result, 120);
done_testing();
