#!/usr/local/bin/perl
#u# https://rosettacode.org/wiki/Factor-perfect_numbers
#t# inprogress
#c# 2022-xx-xx >RC
#p# OK

use Data::Printer;          # debug only
use Time::HiRes qw(sleep);  # debug only

my @res;

use v5.36;

use ntheory 'divisors';
use enum qw(False True);
use List::AllUtils <firstidx sum>;

my $n = 4;
my @fpns = (0, 1);
my %cache;

sub proper_divisors ($n) {
  return 1 if $n == 0;
  my @d = divisors($n);
  pop @d;
  @d;
}

sub erdosFactorCount ($n) {
   my @foo = proper_divisors($n); shift @foo;
   my ($sum,@divs) = (0, @foo); #(proper_divisors $n)[1..*]);
   for my $d (@divs) {
      my $t = int($n/$d);
      unless (exists $cache{$t}) { $cache{$t} = erdosFactorCount($t) }
      $sum += $cache{$t}
   }
   return $sum + 1
}

sub moreMultiples ($to, $from) {
   my @toSeq = @{$to};
   my @fromSeq = @{$from};
   my @oneMores;
   for my $j (@fromSeq) {
      push @oneMores, (@toSeq, $j) if $j > $toSeq[-1] && 0 == $j % $toSeq[-1]
   }
   return [] unless @oneMores;
   for (0 .. $#oneMores) {
      push @oneMores, moreMultiples($oneMores[$_], \@fromSeq)
   }
   return @oneMores
}

say my $result = join "\n", @res;

my $ref = <<'END';
END

use Test::More;
chomp $ref;
is($result, $ref);
#is(($result =~ s/\s//gr), ($ref =~ s/\s//gr));
done_testing();

__END__

=={{header|Perl}}==
{{trans|Raku}}
{{libheader|ntheory}}
<syntaxhighlight lang="perl" line>
</syntaxhighlight>
{{out}}
<pre>
</pre>
