#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/FASTA_format
#c# 2018-08-03 <RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

my $fasta_example = <<'END_FASTA_EXAMPLE';
>Rosetta_Example_1
THERECANBENOSPACE
>Rosetta_Example_2
THERECANBESEVERAL
LINESBUTTHEYALLMUST
BECONCATENATED
END_FASTA_EXAMPLE

my $num_newlines = 0;
while ( < $fasta_example > ) {
	if (/\A\>(.*)/) {
		$result .= ("\n" x $num_newlines). $1. ': ';
	}
	else {
		$num_newlines = 1;
		$result .= $_;
	}
}

say $result;

my $ref = <<'EOD';
Rosetta_Example_1: THERECANBENOSPACE
Rosetta_Example_2: THERECANBESEVERALLINESBUTTHEYALLMUSTBECONCATENATED
EOD

use Test::More;
chop $ref;
is ($result, $ref);
done_testing();
