#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/File_size_distribution
#c# 2018-09-28 >RC
#p# OK
#n# should update this once a year (before previous year logs are archived)
#n# switch to testing Perl results, not Raku

use strict;
use warnings;
use feature 'say';
my @res;

use File::Find;
use List::Util 'max';

my %fsize;
my $dir = 'bench/2023-01-02';
#my $dir = '/Users/dhoekman/perl5/Rosetta-Code/last/2023-01-02';
find(\&fsize, $dir);

my($max,$size,$total) = (0,0,0);
$max    = max($max,$_) for values %fsize;
$total += $size while (undef,$size) = each %fsize;

push @res, "File size distribution in bytes for directory: $dir\n";
for (0 .. max(keys %fsize)) {
    push @res, sprintf( "# files @ %4sb %8s: ", $_ ? '10e'.($_-1) : 0, ($fsize{$_} // 0)) . 
       histogram( $max, $fsize{$_} // 0, 80)
}
push @res, "$total total files.";

sub histogram {
    my($max, $value, $width) = @_;
    my @blocks = <| ▏ ▎ ▍ ▌ ▋ ▊ ▉ █>;
    my $scaled = int $value * $width / $max;
    my($end) =     $scaled % 8;
    my($bar) = int $scaled / 8;
    my $B = $blocks[8] x ($bar * 8) . ($end ? $blocks[$end] : '');
}

sub log10 { my($s) = @_; $s ? int log($s)/log(10) : 0 }
sub fsize { $fsize{ log10( (lstat($_))[7] ) }++ }

say my $result = join "\n", @res;

my $ref = <<'END';
File size distribution in bytes for directory: bench/2023-01-02

# files @    0b        0: 
# files @ 10e0b     1871: ████████████████████████████████████████████████████████████████████████████████
# files @ 10e1b     1104: ████████████████████████████████████████▉
# files @ 10e2b      172: ▉
# files @ 10e3b        3: 
# files @ 10e4b        1: 
3151 total files.
END

use Test::More;
chop $ref;
is ($result, $ref);
done_testing();
