#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Find_words_which_contains_all_the_vowels
#c# 2021-02-20 <RC
#p# OK

my @res;

use strict;
use warnings;
use feature 'say';

@ARGV = 'ref/unixdict.txt';
length > 11 and !/([aeiou]).*\1/ and tr/aeiou// == 5 and push(@res, $_) while <>;

say my $result = join "", @res;

my $ref = <<'EOD';
ambidextrous
bimolecular
cauliflower
communicable
communicate
consanguine
consultative
countervail
exclusionary
grandiloquent
importunate
incommutable
incomputable
insupportable
loudspeaking
malnourished
mensuration
oneupmanship
pandemonium
permutation
perturbation
portraiture
praseodymium
stupefaction
sulfonamide
EOD

use Test::More;
is ($result, $ref);
done_testing();
