#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Find_words_with_alternating_vowels_and_consonants
#c# 2021-01-07 >RC
#p# OK

use strict;
use warnings;
use feature 'say';

my @res;

my $vowels = 'aeiou';
my $v = qr/[ $vowels]/x;
my $c = qr/[^$vowels]/;

my @words = grep { /.{10}/ } split "\n", `cat ref/unixdict.txt`;

for (@words) { push @res, $_ if /^ ( ($c$v)+ $c? | ($v$c)+ $v? ) $/ix; }

# this is on RC:
# /^ ( ($c$v)+ $c? | ($v$c)+ $v? ) $/ix and say for grep { /.{10}/ } split "\n",  do { (@ARGV, $/) = 'unixdict.txt'; <> };

my $result = join "\n", @res;

my $ref = <<'END';
aboriginal
apologetic
bimolecular
borosilicate
calorimeter
capacitate
capacitive
capitoline
capitulate
caricature
colatitude
coloratura
colorimeter
debilitate
decelerate
decolonize
definitive
degenerate
deliberate
demodulate
denominate
denotative
deregulate
desiderata
desideratum
dilapidate
diminutive
epigenetic
facilitate
hemosiderin
heretofore
hexadecimal
homogenate
inoperative
judicature
latitudinal
legitimate
lepidolite
literature
locomotive
manipulate
metabolite
nicotinamide
oratorical
paragonite
pejorative
peridotite
peripatetic
polarimeter
recitative
recuperate
rehabilitate
rejuvenate
remunerate
repetitive
reticulate
savonarola
similitude
solicitude
tananarive
telekinesis
teratogenic
topologize
unilateral
unimodular
uninominal
verisimilitude
END

use Test::More;
chomp $ref;
is($result, $ref);
done_testing;
