#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Find_limit_of_recursion
#c# 2018-08-06 <RC
#p# OK
#n# stop at 1E6, but could easily go on

use strict;
no warnings 'recursion';
use feature 'say';

#Maximum recursion depth is memory dependent.

my $x = 0;
my $max = 1_000_000;

#sub recurse ($) {
sub recurse {
    ++$x;
#   print ++$x,"\n";
   say $x and return if $x >= $max;
   recurse($x);
}

recurse($x);

use Test::More;
is ($x, $max);
done_testing;
