#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Find_words_which_contains_more_than_3_e_vowels
#c# 2021-02-20 <RC
#p# OK

my @res;

use strict;
use warnings;
use feature 'say';

@ARGV = 'ref/unixdict.txt';
tr/e// > 3 and tr/aiou// == 0 and push @res, $_ while <>;

# my version had a *n*x-y dependency: 
# print join "\n", grep { tr/e// > 3 and not tr/aiou// } split "\n", `cat ref/unixdict.txt`

say my $result = join '', @res;

my $ref = <<'EOD';
belvedere
dereference
elsewhere
erlenmeyer
evergreen
everywhere
exegete
freewheel
nevertheless
persevere
preference
referee
seventeen
seventeenth
telemeter
tennessee
EOD

use Test::More;
is ($result, $ref);
done_testing;
