#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Five_weekends
#c# 2018-08-06 <RC
#p# OK

use strict;
use warnings;
use feature 'say';
my $result;

use DateTime ;

my @happymonths ;
my @workhardyears ;
my @longmonths = ( 1 , 3 , 5 , 7 , 8 , 10 , 12 ) ;
my @years = 1900..2100 ;
foreach my $year ( @years ) {
   my $countmonths = 0 ;
   foreach my $month ( @longmonths ) {
      my $dt = DateTime->new( year => $year ,
	                      month => $month ,
			      day   => 1 ) ;
      if ( $dt->day_of_week == 5 ) {
	 $countmonths++ ;
	 my $yearfound = $dt->year ;
	 my $monthfound = $dt->month_name ;
	 push ( @happymonths , "$yearfound  $monthfound" ) ;
      }
   }
   if ( $countmonths == 0 ) {
      push ( @workhardyears, $year ) ;
   }
}
$result .= "There are " . @happymonths . " months with 5 full weekends!\n" ;
$result .= "The first 5 and the last 5 of them are:\n" ;
foreach my $i ( 0..4 ) {
   $result .= "$happymonths[ $i ]\n" ;
}
foreach my $i ( -5..-1 ) {
   $result .= "$happymonths[ $i ]\n" ;
}
$result .= "No long weekends in the following " . @workhardyears . " years:\n" ;
map { $result .= "$_\n" } @workhardyears ;

say $result; 

my $ref = <<'EOD';
There are 201 months with 5 full weekends!
The first 5 and the last 5 of them are:
1901  March
1902  August
1903  May
1904  January
1904  July
2097  March
2098  August
2099  May
2100  January
2100  October
No long weekends in the following 29 years:
1900
1906
1917
1923
1928
1934
1945
1951
1956
1962
1973
1979
1984
1990
2001
2007
2012
2018
2029
2035
2040
2046
2057
2063
2068
2074
2085
2091
2096
EOD

use Test::More;
is ($result, $ref);
done_testing;
