#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Forward_difference
#c# 2018-08-07 <>RC
#p# OK

use strict;
use warnings;
use feature 'say';
my $result;

sub dif {
  my @s = @_;
  map { $s[$_+1] - $s[$_] } 0 .. @s-2 #$#s-1
}

# obsoleted
#sub difn {
#  my ($n, @s) = @_;
#  @s = dif @s foreach 1..$n;
#  @s
#}

my @a = <90 47 58 29 22 32 55 5 55 73>;
while (@a) {$result .= sprintf '%6d', $_ for @a = dif @a; $result .= "\n"}
#while (@a) { printf('%6d', $_) for @a = dif @a; print "\n" } # this version on RC

say $result;
my $ref = <<'EOD';
   -43    11   -29    -7    10    23   -50    50    18
    54   -40    22    17    13   -73   100   -32
   -94    62    -5    -4   -86   173  -132
   156   -67     1   -82   259  -305
  -223    68   -83   341  -564
   291  -151   424  -905
  -442   575 -1329
  1017 -1904
 -2921

EOD

use Test::More;
is ($result, $ref);
done_testing;
