#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Four_is_magic
#c# 2018-09-07 >RC, 2018-09-10 <RC
#p# OK
#n# Thundergnat fixed my bug

use strict;
use warnings;
use feature 'say';
my $result;

use bignum;

use Lingua::EN::Numbers qw(num2en);

sub cardinal {
    my($n) = @_; 
    (my $en = num2en($n)) =~ s/\ and|,//g; 
    $en;
}

sub magic {
    my($int) = @_;
    my $str;
    while () {
       $str .= cardinal($int) . " is ";
       if ($int == 4) {
           $str .= "magic.";
           last
       } else {
           $int = length cardinal($int);
           $str .= cardinal($int) . ", ";
       }
   }
   ucfirst $str;
}

$result .= magic($_) . "\n" for 0, 4, 6, 11, 13, 75, 337, -164, 9_876_543_209;

say $result;

my $ref = <<'EOD';
Zero is four, four is magic.
Four is magic.
Six is three, three is five, five is four, four is magic.
Eleven is six, six is three, three is five, five is four, four is magic.
Thirteen is eight, eight is five, five is four, four is magic.
Seventy-five is twelve, twelve is six, six is three, three is five, five is four, four is magic.
Three hundred thirty-seven is twenty-six, twenty-six is ten, ten is three, three is five, five is four, four is magic.
Negative one hundred sixty-four is thirty-one, thirty-one is ten, ten is three, three is five, five is four, four is magic.
Nine billion eight hundred seventy-six million five hundred forty-three thousand two hundred nine is ninety-seven, ninety-seven is twelve, twelve is six, six is three, three is five, five is four, four is magic.
EOD

use Test::More;
is ($result, $ref);
done_testing;
