#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/FTP
#c# 2018-07-31 <RC, 2018-11-30 >RC
#p# OK
#n# differs from what's on RC (this version easier to test)

my $result;

use strict;
use warnings;
use feature 'say';

use Net::FTP;
 
# FTP server and credentials
my $host     = 'ftp.netbsd.org';
my $user     = 'anonymous';
my $password = '';
 
# connect in passive mode
my $f = Net::FTP->new($host) or die("Can't open $host\n");
$f->login($user, $password)  or die("Can't login as $user\n");
$f->passive();
 
# change remote directory, list contents
$f->cwd('pub/NetBSD');
$result .= "$_\n" for $f->ls();
 
#Download the file and store locally. get() returns the local filename
my $local = $f->get('README', 'run/README');
print "Your file was stored as $local in the current directory.\n";

say $result;
 
use Test::More;
ok $result =~ /NetBSD-daily/;
ok -e 'run/README';
done_testing;
