#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Function_composition
#c# 2018-08-08 <RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

sub compose {
    my ($f, $g) = @_;

    sub {
        $f -> ($g -> (@_))
    };
}

use Math::Trig;
say $result = compose(sub {sin $_[0]}, \&asin)->(0.5);

use Test::More;
is ($result, 0.5);
done_testing();
