#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Function_prototype
#t# nocode
#c# 2018-08-08 <RC
#p# OK

=head 

# The perl scripting language allows prototypes to be checked during JIT compilation. 
# Prototypes should be placed before subroutine definitions, declarations, or anonymous subroutines. 
# The sigil special symbols act as argument type placeholders.

sub noargs(); # Declare a function with no arguments
sub twoargs($$); # Declare a function with two scalar arguments. The two sigils act as argument type placeholders
sub noargs :prototype(); # Using the :attribute syntax instead
sub twoargs :prototype($$);

=cut
