#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Safe_and_Sophie_Germain_primes
#c# 2021-12-10 <RC
#p# OK
#n# PITA construction for testing!


use strict;
use warnings;
use feature 'say';

use Test::More;
use ntheory qw( forprimes is_prime);

my(@want, $result);

my $ref = <<'EOD';
2 3 5 11 23 29 41 53 83 89 113 131 173 179 191 233 239 251 281 293
359 419 431 443 491 509 593 641 653 659 683 719 743 761 809 911 953
1013 1019 1031 1049 1103 1223 1229 1289 1409 1439 1451 1481 1499
EOD

LOOP: {
forprimes { is_prime(2 * $_ + 1) and (50 == push @want, $_)
  and ($result .= "@want\n" =~ s/.{65}\K /\n/gr) and is($result,$ref) and done_testing() and exit } 2, 1e9;
}
