#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Sattolo_cycle
#c# 2018-09-05 >RC
#p# OK
#n# let it be random to see if it ever fails

#srand 1;

use strict;
use warnings;
use feature 'say';

my @a = 0..30;

printf "%2d ", $_ for @a; print "\n";
sattolo_cycle(\@a);
printf "%2d ", $_ for @a; print "\n";

sub sattolo_cycle {
    my($array) = @_;
    for my $i (reverse 0 .. -1+@$array) {
        my $j = int rand $i;
        @$array[$j, $i] = @$array[$i, $j];
    }
}

use Test::More;
my $ok = 1;
$a[$_] == $_ and $ok = 0 for 0..30;
ok ( $ok );
done_testing();
