#!/usr/local/bin/perl
#u# https://www.rosettacode.org/wiki/Search_in_paragraph%27s_text
#t# skiptest
#c# 2024-06-22 <RC
#p# BROKEN
#n# translated from AWK

__END__

use strict;
use warnings;
use feature 'say';

local $/ = "";  # Set the input record separator to an empty string to read paragraph mode
local $\ = "\n----------------\n";  # Set the output record separator

# Open the file Traceback.txt for reading
open my $fh, '<', 'Traceback.txt' or die "Cannot open Traceback.txt: $!";

# Read one paragraph at a time
while (<$fh>) {
    if (/Traceback \(most recent call last\):/ && /SystemError/) {
        print substr($_, index($_, "Traceback (most recent call last):"));
    }
}


say my $result = join "\n", @res;
my $ref = <<'EOD';
EOD

use Test::More;
is ($result, $ref);
done_testing();
