#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Self_numbers
#c# 2020-12-xx >RC
#p# OK
#n# Wait a sec... Raku is *faster*?

use strict;
use warnings;
use feature 'say';

use List::Util qw(max sum);

my ( $count, $i, $pow, $digits, $offset, $lastSelf, $done, @selfs) 
 = (      0,  1,   10,       1,       9,         0,     0        );

my $final = 1000; #1000;

while () {
   my $isSelf = 1;
   my $sum = my $start = sum split //, max(($i-$offset), 0);
   for ( my $j = $start; $j < $i; $j++ ) {
      if ($j+$sum == $i) { $isSelf = 0 ; last }
      ($j+1)%10 != 0 ? $sum++ : ( $sum = sum split '', ($j+1) );
   }

   if ($isSelf) {
      $count++;
      $lastSelf = $i;
      push @selfs, $i;
      last if @selfs == $final;
   }

   $i++;
   next unless $i%$pow == 0;
   $pow *= 10;
   $offset = 9 * $digits++
}

# say "The 100 millionth self number is ", $lastSelf; # 1022727208
#say $selfs[-1]; exit;

say my $result = "The first 50 self numbers are:\n" . join ' ', @selfs;
exit;

my $ref = <<'END';
The first 50 self numbers are:
1 3 5 7 9 20 31 42 53 64 75 86 97 108 110 121 132 143 154 165 176 187 198 209 211 222 233 244 255 266 277 288 299 310 312 323 334 345 356 367 378 389 400 411 413 424 435 446 457 468
END

use Test::More;
chomp $ref;
is($result, $ref);
done_testing();

__END__

=={{header|Perl}}==
{{trans|Raku}}
<lang perl></lang>
{{out}}
<pre></pre>
