#!/usr/local/bin/perl
#u# https://rosettacode.org/wiki/SEND_+_MORE_=_MONEY
#c# 2023-03-19 >RC
#p# OK
#n# tweaks for speed not on RC
#n# 5849 + 638 == 6487 if permitted that M == 0

my @res;

use v5.36;

use enum <D E M N O R S Y>;
use Algorithm::Combinatorics <combinations permutations>;

sub solve {
  for my $p (map { permutations $_ } combinations [reverse 0..9], 8) {
    return $p if @$p[M] > 0 and @$p[S] > 7 and join('',@$p[S,E,N,D]) + join('',@$p[M,O,R,E]) == join('',@$p[M,O,N,E,Y]);
  }
}

push @res, sprintf "SEND + MORE == MONEY\n%d + %d == %d", join('',@$_[S,E,N,D]), join('',@$_[M,O,R,E]), join '',@$_[M,O,N,E,Y]
    for solve();

say my $result = join "\n", @res;

my $ref = <<'END';
SEND + MORE == MONEY
9567 + 1085 == 10652
END

use Test::More;
chomp $ref;
is($result, $ref);
done_testing();
