#!/usr/local/bin/perl
#u# https://rosettacode.org/wiki/SEND_+_MORE_=_MONEY
#c# 2023-03-19 >RC
#p# OK
#n# corresponds most closely to -3 Raku version
#n# 'grep' works like junction/List::AllUtils::any here (and short-circuits?)

my $result;

use v5.36;

my $s = 7;
while (++$s <= 9) {
    my $e = -1;
    while (++$e <= 9) {
        next if $e == $s;
        my $n = -1;
        while (++$n <= 9) {
            next if grep { $n == $_ } $s,$e;
            my $d = -1;
            while (++$d <= 9) {
                next if grep { $d == $_ } $s,$e,$n;
                my $send = $s*10**3 + $e*10**2 + $n*10 + $d;
                my ($m, $o) = (1, -1);
                while (++$o <= 9) {
                    next if grep { $o == $_ } $s,$e,$n,$d,$m;
                    my $r = -1;
                    while (++$r <= 9) {
                        next if grep { $r == $_ } $s,$e,$n,$d,$m,$o;
                        my $more = $m*10**3 + $o*10**2 + $r*10 + $e;
                        my $y = -1;
                        while (++$y <= 9) {
                            next if grep { $y == $_ } $s,$e,$n,$d,$m,$o,$r;
                            my $money = $m*10**4 + $o*10**3 + $n*10**2 + $e*10 + $y;
                            next unless $send + $more == $money;
                            $result = "SEND + MORE == MONEY\n$send + $more == $money";
                        }
                    }
                }
            }
        }
    }
}

say $result;

my $ref = <<'END';
SEND + MORE == MONEY
9567 + 1085 == 10652
END

use Test::More;
chomp $ref;
is($result, $ref);
done_testing();
