#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Sequence_of_non-squares
#c# 2018-08-18 <RC
#p# OK

use feature 'say';
my $result;

sub nonsqr { my $n = shift;  $n + int(0.5 + sqrt $n) }

say $result = join(' ', map nonsqr($_), 1..22); #, "\n";

foreach my $i (1..1_000_000) {
  my $root = sqrt nonsqr($i);
  die "Oops, nonsqr($i) is a square!" if $root == int $root;
}

use Test::More;
is ($result, '2 3 5 6 7 8 10 11 12 13 14 15 17 18 19 20 21 22 23 24 26 27');
done_testing();
