#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/SHA-256_Merkle_tree
#c# 2021-02-22 <RC
#p# OK

use strict;
use warnings;
use feature 'say';

use Crypt::Digest::SHA256 'sha256' ;

my @blocks;

open my $fh, '<:raw', 'ref/rc-title.png';

while ( read $fh, my $chunk, 1024 ) { push @blocks, sha256 $chunk }

while ( scalar @blocks > 1 ) {
   my @clone = @blocks and @blocks = ();
   while ( @_ = splice @clone, 0, 2 ) {
      push @blocks, scalar @_ == 1 ? $_[0] : sha256 $_[0].$_[1]
   }
}

say my $result = unpack ( 'H*', $blocks[0] );

my $ref = 'a4f902cf9d51fe51eda156a6792e1445dff65edf3a217a1f3334cc9cf1495c2c';

use Test::More;
is ($result, $ref);
done_testing;
