#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/SHA-1
#c# 2018-08-18 <RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

#Library: Digest::SHA
use Digest::SHA qw(sha1_hex);

$result .= sha1_hex('Rosetta Code'). "\n";

#The same in OO manner
my $sha1 = Digest::SHA->new(1);
$sha1->add('Rosetta Code');
$result .= $sha1->hexdigest. "\n";

say $result; 

my $ref = <<'EOD';
48c98f7e5a6e736d790ab740dfc3f51a61abe2b5
48c98f7e5a6e736d790ab740dfc3f51a61abe2b5
EOD

use Test::More;
is ($result, $ref);
done_testing();
