#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Shift_list_elements_to_left_by_3
#c# 2021-03-14 <RC
#p# OK

use strict;
use warnings;

my $n = 3;
my @list = 1..9;
push @list, splice @list, 0, $n;
print my $result = join ' ', @list, "\n";

use Test::More;
chomp $result;
is ($result, '4 5 6 7 8 9 1 2 3 ');
done_testing;
