#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Show_Ascii_table
#c# 2018-09-xx NOT ON RC
#p# OK
#f# RC file: ASCII_table.txt
#n# see -2, translated from Raku

my $result;

use strict;
use warnings;
use feature 'say';

use open ":encoding(utf8)";

my $N    = 16;
my $cell =  5;
my $bar = join(('-'x5), split '', '+' x ($N+1)) . "\n";

sub name {
    my($n) = @_;
    if    ($n < 33) { return chr(0x2400 + $n) }
    elsif ($n==127) { return 'DEL' }
    else            { return chr($n) }
}

# could do without nested loops, but maybe clearer this way...
for my $i (0..7) {
    $result .= $bar;
    my $l1 = my $l2 = my $l3 = '|';
    for my $j (0..$N-1) {
        my $c = $N*$i + $j;
        $l1 .= sprintf " %3x |", $c;
        $l2 .= sprintf " %3d |", $c;
        $l3 .= sprintf " %3s |", name($c);
    }
    $result .= "$l1\n$l2\n$l3\n";
}
$result .= $bar;

open F, '>run/ASCII_table.txt';
print F $result;
