#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Sieve_of_Eratosthenes
#c# 2018-08-16 <RC
#p# OK
#n# $s remains undefined throughout?

my $result;

use strict;
no warnings;
use feature 'say';

sub sieve{ 
    my ($s, $i);
	grep { not vec $s, $i  = $_, 1 and do 
		{ (vec $s, $i += $_, 1) = 1 while $i <= $_[0]; 1 }
	} 2..$_[0]
}

say $result = join ' ', sieve(100);

use Test::More;
is ($result, '2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97');
done_testing();
