#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Simple_windowed_application
#t# gui
#c# 2018-08-16 <RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

use Tk;

my $main = MainWindow->new;
my $l = $main->Label('-text' => 'There have been no clicks yet.')->pack;
my $count = 0;
$main->Button(
  -text => ' Click Me ',
  -command => sub { $l->configure(-text => 'Number of clicks: '.(++$count).'.'); },
)->pack;
MainLoop();

__END__
# Library: GTK # Works with: Perl/Gtk[edit]
use Gtk '-init';

# Window.
$window = Gtk::Window->new;
$window->signal_connect('destroy' => sub { Gtk->main_quit; });

# VBox.
$vbox = Gtk::VBox->new(0, 0);
$window->add($vbox);

# Label.
$label = Gtk::Label->new('There have been no clicks yet.');
$vbox->add($label);

# Button.
$count = 0;
$button = Gtk::Button->new(' Click Me ');
$vbox->add($button);
$button->signal_connect('clicked', sub {
  $label->set_text(++$count);
});

# Show.
$window->show_all;

# Main loop.
Gtk->main;
