#!/usr/local/bin/perl
#u# https://www.rosettacode.org/wiki/Singly-linked_list/Element_removal
#c# 2024-09-14 <RC
#p# OK

my @res;

use strict;
use warnings;
use feature 'say';

my %node3 = ( data => 'Node 3', next => undef );
my %node2 = ( data => 'Node 2', next => \%node3 );
my %node1 = ( data => 'Node 1', next => \%node2 );
my $head  = \%node1;

sub print_list {
   my ($head_ref) = @_;
   my $current = $head_ref;
   while ($current) {
      push @res, $current->{data}, " -> ";
      $current = $current->{next};
   }
   push @res, "undef\n";
}

sub remove_element {
   my ($head_ref, $value) = @_;
   my $current = $$head_ref;
   my $prev    = undef;

   while ($current) {
      if ($current->{data} eq $value) {
         if ($prev) {
            $prev->{next} = $current->{next};
         } else {
            $$head_ref = $current->{next}; 
         }
         return 1;  # Element found and removed
      }
      $prev    = $current;
      $current = $current->{next};
   }
   return 0;  # Element not found
}

push @res, "Original list:\n";
print_list($head);
remove_element(\$head, 'Node 2');
push @res, "\nList after removing 'Node 2':\n";
print_list($head);

say my $result = join "", @res;

my $ref = <<'EOD';
Original list:
Node 1 -> Node 2 -> Node 3 -> undef

List after removing 'Node 2':
Node 1 -> Node 3 -> undef
EOD

use Test::More;
is ($result, $ref);
done_testing();
