#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Singly-linked_list/Element_definition
#t# nocode
#c# 2018-08-16 <RC
#p# OK

=head

# Just use an array. You can traverse and splice it any way. Linked lists are way too low level.
# However, if all you got is an algorithm in a foreign language, you can use references to accomplish the translation.

my %node = (
    data => 'say what',
    next => \%foo_node,
);
$node{next} = \%bar_node;  # mutable

=cut
