#!/usr/bin/env perl
#u# http://rosettacode.org/wiki/Singly-linked_list/Element_removal
#c# 2022-xx-xx NOT ON RC
#p# OK
#n# ~/PWC/071/2/e-chorba.pl

use strict;
use warnings;

{   package My::PureNode;
    sub new {
        my ($class, $value) = @_;
        bless [$value, undef], $class
    }
    sub next  { $_[0][1] }
    sub value { $_[0][0] }
    sub add   {
        my $new = ref($_[0])->new($_[1]);
        $new->[1] = $_[0];
        $_[0] = $new;
    }
    sub serialise {
        my ($self) = @_;
        my @s;
        my $n = $self;
        while ($n) {
            push @s, $n->value;
            $n = $n->next;
        }
        return @s
    }
}

{   package My::Node::Trimmable;
    use parent -norequire => 'My::PureNode';
    sub trim {
        my ($self, $n) = @_;
        my @buffer;
        my $w = $self;
        while ($w) {
            push @buffer, $w;
            shift @buffer if @buffer > $n + 1;
            $w = $w->next;
        }
        if (@buffer == $n + 1) {
            $buffer[0][1] = $buffer[2];
            undef $buffer[1][1];  # no memory leak
        } else {
            $_[0] = $buffer[1];
            undef $buffer[0][1];  # no memory leak
        }
    }
}

use Test::More;

sub _fixture {
    my $n = 'My::Node::Trimmable'->new(5);
    $n->add($_) for reverse 1 .. 4;
    $n
}

my $n = _fixture();
is_deeply [$n->serialise], [1..5], 'serialise';

my $n1 = _fixture();
$n1->trim(1);
is_deeply [$n1->serialise], [1..4], 'trim 1';

my $n2 = _fixture();
$n2->trim(2);
is_deeply [$n2->serialise], [1..3, 5], 'trim 2';

done_testing();
