#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Sleep
#c# 2018-08-14 <RC
#p# OK
#=# RC pipe: 4\n4000000\n4000000000\n

use feature 'say';

say 'enter seconds:';
my $seconds = <>;
print "Sleeping...\n";
sleep $seconds; # number is in seconds
print "Awake!\n";

# microseconds and nanoseconds using the Time::HiRes module:
use Time::HiRes qw( usleep nanosleep );

say 'enter microseconds:';
my $microseconds = <>;
print "Sleeping...\n";
usleep $microseconds;
print "Awake!\n";

say 'enter nanoseconds:';
my $nanoseconds = <>;
print "Sleeping...\n";
nanosleep $nanoseconds;
print "Awake!\n";

#It's also possible to sleep for fractional seconds by abusing the select function:
say "Sleeping...";
select undef, undef, undef, 0.5;
say "Awake!";

my $elapsed = (time() - $^T);

use Test::More;
ok $elapsed >= 12;
done_testing();
