#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Sorting_algorithms/Quicksort
#c# 2018-08-15 <RC
#p# OK

use feature 'say';
my $result;

sub quick_sort {
    return @_ if @_ < 2;
    my $p = splice @_, int rand @_, 1;
    quick_sort(grep $_ < $p, @_), $p, quick_sort(grep $_ >= $p, @_);
}

use Test::More;
say 'input: ' . join ' ', @a = map+(int rand 100), 0 .. 50;
is_deeply([quick_sort(@a)], [sort { $a <=> $b } @a]);
done_testing();
