#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Sort_an_integer_array
#c# 2018-08-15 <RC
#p# OK

use strict;
use warnings;
use feature 'say';

my @nums = (2,4,3,1,2);
say my $result = join ' ', sort {$a <=> $b} @nums;

use Test::More;
is  $result, '1 2 2 3 4';
done_testing();
