#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Sort_a_list_of_object_identifiers
#c# 2018-08-15 <RC
#p# OK

my $result;

use v5.36.0;        # still works
#use strict;
#use warnings;
#use feature 'say';

my @OIDs = qw(
    1.3.6.1.4.1.11.2.17.19.3.4.0.10
    1.3.6.1.4.1.11.2.17.5.2.0.79
    1.3.6.1.4.1.11.2.17.19.3.4.0.4
    1.3.6.1.4.1.11150.3.4.0.1
    1.3.6.1.4.1.11.2.17.19.3.4.0.1
    1.3.6.1.4.1.11150.3.4.0
);

# Alternately, you can sort them as "version strings", which is a Perl syntax allowing you to specify a character 
# string in the source code with the characters' codes specified as a dot-delimited sequence of integers.

my @sorted =
    map { $_->[0] }
    sort { $a->[1] cmp $b->[1] }
    map { [$_, eval "v$_"] }
    @OIDs;

$result .= "$_\n" for @sorted;

say $result; 
my $ref = <<'EOD';
1.3.6.1.4.1.11.2.17.5.2.0.79
1.3.6.1.4.1.11.2.17.19.3.4.0.1
1.3.6.1.4.1.11.2.17.19.3.4.0.4
1.3.6.1.4.1.11.2.17.19.3.4.0.10
1.3.6.1.4.1.11150.3.4.0
1.3.6.1.4.1.11150.3.4.0.1
EOD

use Test::More;
is ($result, $ref);
done_testing;
