#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Special_neighbor_primes
#c# 2021-08-09 <RC
#p# OK

my @res;

use strict;
use warnings;
use feature 'say';

use ntheory qw( primes is_prime );

my @primes = @{ primes(100) };

for ( 1 .. $#primes ) {
  is_prime( $@ = $primes[$_-1] + $primes[$_] - 1 ) and
    push @res, sprintf "%2d + %2d - 1 = %3d", $primes[$_-1], $primes[$_], $@;
}

say my $result = join "\n", @res;

my $ref = <<'EOD';
 3 +  5 - 1 =   7
 5 +  7 - 1 =  11
 7 + 11 - 1 =  17
11 + 13 - 1 =  23
13 + 17 - 1 =  29
19 + 23 - 1 =  41
29 + 31 - 1 =  59
31 + 37 - 1 =  67
41 + 43 - 1 =  83
43 + 47 - 1 =  89
61 + 67 - 1 = 127
67 + 71 - 1 = 137
73 + 79 - 1 = 151
EOD

use Test::More;
chomp $ref;
is ($result, $ref);
done_testing;
