#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Spinning_rod_animation/Text
#c# 2018-10-01 >RC, 2021-08-22 <RC
#p# OK
#f# RC file: spinner.dat

$|= 1;

open my $F, '>', 'run/spinner.dat' || die;

for (1..3) {
    for (qw[ | / - \ ]) {
        select undef, undef, undef, 0.25;
        printf $F "\r ($_)";
    }
}

__END__

while () { 
  for (map { $_ + 1 } 0x1F310 .. 0x1F317) { 
    # creating array of sequential Unicode codepoints for the emoji; 
    # it's equal to qw[🌕 🌖 🌗 🌘 🌑 🌒 🌓 🌔 🌕  ] but comes handy for the
    # implementing the clock faces or any other codepoint ranges.
    select undef, undef, undef, 0.25;
    # all the magic of this thing; switches between three file handles every 0.25s
    print "\r @{[chr]}"
    # string/variable interpolation; 
    # (1) chr without param works on `$_`
    # (2) `[]` creates a singleton list
    # (3) `@{}` dereferences the created list.
  } 
}
