#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Start_from_a_main_routine
#c# 2018-08-13 <RC
#t# nocode
#p# OK

# Same as Perl 6.

#BEGIN {...} # as soon as parsed
#CHECK {...} # end of compile time
#INIT {...}  # beginning of run time
#END {...}   # end of run time
