#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Start_from_a_main_routine
#c# 2018-08-13 <RC
#t# nocode
#p# OK
#n# Same as Raku, imagine that...

use Test::More;
my $r;

BEGIN { $r .= '1' } # as soon as parsed
CHECK { $r .= '2' } # end of compile time
INIT  { $r .= '3' } # beginning of run time
END   { $r .= '4'; print "$r\n"; is $r, '1234'; done_testing() } # end of run time
