#!/usr/local/bin/perl
#u# https://rosettacode.org/wiki/Statistics_Chi-squared_distribution
#t# inprogress
#c# 2022-12-03 >RC
#p# OK

use v5.36;

use Data::Printer;          # debug only
use Time::HiRes qw(sleep);  # debug only

my $result;

use List::Util 'sum';
use Math::MPFR; 
Math::MPFR->import();

sub Gamma ($z) {
my $g = Math::MPFR->new();
Math::MPFR::Rmpfr_gamma($result, Math::MPFR->new($z), 0);
$g;
}

sub chi2($x,$k) { $x>0 && $k>0 ? ($x**($k/2 - 1) * exp(-$x/2)/(2**($k/2)*gamma($k / 2))) : 0}

sub gamma_cdf($k,$x) { $x**$k * exp(-$x) * sum map { $x** $_ / gamma($k+$_+1) } 0..100 }

sub cdf_chi2($x,$k) { ($x <= 0 or $k <= 0) ? 0.0 : gamma_cdf($k / 2, $x / 2) }

$result .= join(' ', map { sprintf "%.12f", Gamma($_/3) } 1 .. 10);
$result .= "\n";

say $result;# = join "\n", @res;
exit;

my $ref = <<'END';
END

use Test::More;
chomp $ref;
is($result, $ref);
#is(($result =~ s/\s//gr), ($ref =~ s/\s//gr));
done_testing();

__END__

=={{header|Perl}}==
{{trans|Raku}}
<syntaxhighlight lang="perl" line>
</syntaxhighlight>
{{out}}
<pre>
</pre>
