#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Strip_control_codes_and_extended_characters_from_a_string
#c# 2018-08-13 <RC
#p# OK

my $result;

srand 123456;

use strict;
use warnings;
use feature 'say';

my @letters ;
my @nocontrols ;
my @noextended ;
for ( 1..40 ) {
   push @letters ,  int( rand( 256 ) ) ;
}
print "before sanitation : " ;
print join( '' , map { chr( $_ ) } @letters ) ;
print "\n" ;
@nocontrols = grep { $_ > 32 && $_ != 127 } @letters ;
print "Without controls: " ; 
print join( '' , map { chr( $_ ) } @nocontrols ) ;
@noextended = grep { $_ < 127 } @nocontrols ;
print "\nWithout extended: " ;
print $result = join( '' , map { chr( $_ ) } @noextended ) ;
print "\n" ;

use Test::More;
is ($result, q[4I8E`gP+~Gx}']);
done_testing;
