#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/String_concatenation
#c# 2018-08-13 <RC
#p# OK

use feature 'say';
my $result;

my $s = 'hello';
$result .= $s . ' literal'. "\n";
my $s1 = $s . ' literal';
$result .= $s1. "\n";

#An example of destructive concatenation:

$s .= ' literal';
$result .= $s. "\n";


say $result; 
my $ref = <<'EOD';
hello literal
hello literal
hello literal
EOD

use Test::More;
is ($result, $ref);
done_testing;
