#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/String_interpolation_(included)
#c# 2018-08-13 <RC
#p# OK

use feature 'say';

my $extra = "little";
my $result = "Mary had a $extra lamb.\n";
$result .= sprintf "Mary had a %s lamb.\n", $extra;

say $result; 

my $ref = <<'EOD';
Mary had a little lamb.
Mary had a little lamb.
EOD

use Test::More;
is ($result, $ref);
done_testing;
