#!/usr/local/bin/perl
#u# https://rosettacode.org/wiki/Sub-unit_squares
#c# 2022-09-23 >RC
#p# OK
#n# like Raku, but without the laziness
#n# 8th term is slow:  854.23s user 2.16s system 99% cpu 14:18.84 total

my @res;

use v5.36;

sub U ($n) { $n>1 ? (2*$n)**2 : 1 }
sub L ($n) { $n**2 }
sub R ($n) { 1 x $n }

my($l,$u,$c) = (-1,0,0);
LOOP:
while (++$u) {
    next if U($u) =~ /0/;
    my $chars = length U($u);
    while ($l++) {
        next if U($u) - L($l)  > R($chars);
        last if U($u) - L($l)  < R($chars);
        push @res, U($u); # if U($u) - L($l) == R($chars);
        last LOOP if ++$c == 7;
    }
}

say my $result = join "\n", @res;

my $ref = <<'END';
1
36
3136
24336
5973136
71526293136
318723477136
END
#264_779_654_424_693_136

use Test::More;
chomp $ref;
is($result, $ref);
done_testing();

__END__

=={{header|Perl}}==
{{trans|Raku}}
<syntaxhighlight lang="perl" line>use v5.36;

sub U ($n) { $n>1 ? (2*$n)**2 : 1 }
sub L ($n) { $n**2 }
sub R ($n) { 1 x $n }

my($l,$u,$c) = (-1,0,0);
while (++$u) {
    next if U($u) =~ /0/;
    my $chars = length U($u);
    while ($l++) {
        next if U($u) - L($l) > R($chars);
        last if U($u) - L($l) < R($chars);
        say U($u) and ++$c == 7 and exit
    }
}</syntaxhighlight>
{{out}}
<pre>1
36
3136
24336
5973136
71526293136
318723477136</pre>
