#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Subleq
#c# 2018-08-13 <RC
#p# OK

use feature 'say';
my $result;

use strict;
use warnings;

#my $file = shift;
#my @memory = ();
#open (my $fh, $file);
#while (<$fh>) {
#  chomp;
#  push @memory, split;
#}
#close($fh);

my @memory = <15 17 -1 17 -1 -1 16 1 -1 16 3 -1 15 15 0 0 -1 72 101 108 108 111 44 32 119 111 114 108 100 33 10 0>;

my $ip = 0;
while ($ip >= 0 && $ip < @memory) {
  my ($a, $b, $c) = @memory[$ip,$ip+1,$ip+2];
 $ip += 3;
 if ($a < 0) {
    $memory[$b] = ord(getc);
 } elsif ($b < 0) {
    $result .= chr($memory[$a]);
 } else {
    if (($memory[$b] -= $memory[$a]) <= 0) {
     $ip = $c;
   } 
 }
}

say $result; 

use Test::More;
is ($result, "Hello, world!\n");
done_testing;
