#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Substring
#c# 2018-08-13 <RC
#p# OK

my @res;

use strict;
use warnings;
use feature 'say';

my $str = 'abcdefgh';
@res.push: substr($str, 2, 3);
@res.push: substr($str, 2);
@res.push: substr($str, 0, -1);
@res.push: substr($str, index($str, 'd'), 3);
@res.push: substr($str, index($str, 'de'), 3);

say my $result = @res.join("\n"); 

my $ref = <<'EOD';
cde
cdefgh
abcdefg
def
def
EOD

use Test::More;
is ($result, $ref);
done_testing();
