#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Sudoku
#c# 2018-08-13 <RC
#p# OK

use strict;
use warnings;
use feature 'say';
my $result;

use integer;

my @A = qw(
    5 3 0  0 2 4  7 0 0 
    0 0 2  0 0 0  8 0 0 
    1 0 0  7 0 3  9 0 2 

    0 0 8  0 7 2  0 4 9 
    0 2 0  9 8 0  0 7 0 
    7 9 0  0 0 0  0 8 0 

    0 0 0  0 3 0  5 0 6 
    9 6 0  0 1 0  3 0 0 
    0 5 0  6 9 0  0 1 0
);

sub solve {
    my $i;
    foreach $i ( 0 .. 80 ) {
	next if $A[$i];
	my %t = map {
		$_ / 9 == $i / 9 ||
		$_ % 9 == $i % 9 ||
		$_ / 27 == $i / 27 && $_ % 9 / 3 == $i % 9 / 3
		? $A[$_] : 0,
		1;
	    } 0 .. 80;
	solve( $A[$i] = $_ ) for grep !$t{$_}, 1 .. 9;
	return $A[$i] = 0;
    }
    $i = 0;
    foreach (@A) {
	$result .= "-----+-----+-----\n" if !($i%27) && $i;
	#print !($i%9) ? '': ($i%3 ? ' ' : '|'), $_;
	$result .= !($i%9) ? '': ($i%3 ? ' ' : '|');
    $result .= $_;
	$result .= "\n" unless ++$i%9;
    }
}
solve();

say $result; 
my $ref = <<'EOD';
5 3 9|8 2 4|7 6 1
6 7 2|1 5 9|8 3 4
1 8 4|7 6 3|9 5 2
-----+-----+-----
3 1 8|5 7 2|6 4 9
4 2 5|9 8 6|1 7 3
7 9 6|3 4 1|2 8 5
-----+-----+-----
8 4 1|2 3 7|5 9 6
9 6 7|4 1 5|3 2 8
2 5 3|6 9 8|4 1 7
EOD

use Test::More;
is ($result, $ref);
done_testing;
