#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Sum_of_the_digits_of_n_is_substring_of_n
#c# 2021-04-15 <RC
#p# OK
#n# without $sink use 'no warnings'

my $result;

use strict;
use warnings;
use feature 'say';

# perl -e 'for(0..999){my$n;s/(\d)/$n+=$1/egr;print"$_ "if/$n/}' # as one-liner ..

for (0..999) {
    my $n;
    my $sink = s/(\d)/$n+=$1/egr;
    $result .= "$_ " if /$n/
}

say $result;

my $ref = '0 1 2 3 4 5 6 7 8 9 10 20 30 40 50 60 70 80 90 100 109 119 129 139 149 159 169 179 189 199 200 300 400 500 600 700 800 900 910 911 912 913 914 915 916 917 918 919 ';

use Test::More;
is ($result, $ref);
done_testing();
