#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Sum_of_two_adjacent_numbers_are_primes
#c# 2022-01-21 >RC
#p# OK

my @res;

use strict;
use warnings;
use feature 'say';

use ntheory <is_prime nth_prime>;

# on RC:
#my($n,$c);
#while () { is_prime(1 + 2*++$n) and printf "%2d + %2d = %2d\n", $n, $n+1, 1+2*$n and ++$c == 20 and last }

# could lose boiler-plate but for strict/warnings:
#is_prime(1 + 2*++$n) and printf "%2d + %2d = %2d\n", $n, $n+1, 1+2*$n and $c++ while $c < 20;

my(@n,$n);
while (@n < 20) { is_prime(1 + 2*++$n) and push(@n,$n) }
push @res, sprintf "%2d + %2d = %2d", $_, $_+1, 2*$_+1 for @n;

say my $result = join "\n", @res;

# extra credit
my $hi = 1 + (my $lo = int((my $nth = nth_prime(1+10e6))/2) ); 
say my $result2 = "$lo + $hi = $nth";
my $ref2 = '89712345 + 89712346 = 179424691';

my $ref = <<'END';
 1 +  2 =  3
 2 +  3 =  5
 3 +  4 =  7
 5 +  6 = 11
 6 +  7 = 13
 8 +  9 = 17
 9 + 10 = 19
11 + 12 = 23
14 + 15 = 29
15 + 16 = 31
18 + 19 = 37
20 + 21 = 41
21 + 22 = 43
23 + 24 = 47
26 + 27 = 53
29 + 30 = 59
30 + 31 = 61
33 + 34 = 67
35 + 36 = 71
36 + 37 = 73
END

use Test::More;
chomp $ref;
is($result, $ref);
is($result2, $ref2);
done_testing;
