#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Sum_of_elements_below_main_diagonal_of_matrix
#c# 2021-07-22 NOT ON RC
#p# OK

use v5.36;

use List::Util 'sum';

# fails with v5.36, 'splice on scalar'
#sub lower_triangle_sum1 {
#    our @m; local *m = shift; 
#    my $total;
#    $total += sum splice @{$m[$_]}, 0, $_ for 1..$#m;
#    $total;
#}

sub lower_triangle_sum2(@m) {
    my @elems;
    push @elems, $m[$_]->@[0..$_-1] for 1..$#m;  # postfix de-ref avoids this: (@{$m[$_]})[0..$_-1]
    sum @elems;
}

my @matrix =
(
    [  1,  3,  7,  8, 10 ],
    [  2,  4, 16, 14,  4 ],
    [  3,  1,  9, 18, 11 ],
    [ 12, 14, 17, 18, 20 ],
    [  7,  1,  3,  9,  5 ]
);

#say my $result1 = lower_triangle_sum1(@matrix);
say my $result2 = lower_triangle_sum2(@matrix);

use Test::More;
#is($result1, '69');
is($result2, '69');
done_testing();
