#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Sum_of_elements_below_main_diagonal_of_matrix
#c# 2021-07-22 <RC
#p# OK
#n# tybalt++, this is the version on RC

use strict;
use warnings;

use List::Util 'sum';

my $matrix =
  [[1,3,7,8,10],
  [2,4,16,14,4],
  [3,1,9,18,11],
  [12,14,17,18,20],
  [7,1,3,9,5]];

my $lowersum = sum map @{ $matrix->[$_] }[0 .. $_ - 1], 1 .. $#$matrix;
print my $result = "lower sum = $lowersum\n";

use Test::More;
is ($result, "lower sum = 69\n");
done_testing();
