#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Variable_size/Get
#c# 2018-08-06 <>RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

use Devel::Size qw(size total_size);

my $var = 9384752;
my @arr = (1, 2, 3, 4, 5, 6);
$result .= size($var) . "\n";
$result .= total_size(\@arr) . "\n";

say $result; 

my $ref = <<'EOD';
24
256
EOD

use Test::More;
is ($result, $ref);
done_testing;
