#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Variable_size/Get
#c# 2018-08-06 <>RC
#p# OK

use feature 'say';
my $result;

# Works with: Perl version 5.x
#Library: Devel::SizeSize
use Devel::Size qw(size total_size);

my $var = 9384752;
my @arr = (1, 2, 3, 4, 5, 6);
$result .= size($var) . "\n";
$result .= total_size(\@arr) . "\n";

say $result; 
my $ref = <<'EOD';
24
256
EOD

use Test::More;
is ($result, $ref);
done_testing();
