#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Video_display_modes
#t# gui
#c# 2019-01-21 >RC
#p# OK
#n# tested on Ubuntu 18

$| = 1;

my @info = split "\n", `xrandr -q`;

$info[0] =~ /current (\d+) x (\d+)/;
my $current = "$1x$2";
 
my @resolutions;
for (@info) {
    push @resolutions, $1 if /^\s+(\d+x\d+)/ 
}

system("xrandr -s $resolutions[-1]");
print "Current resolution $resolutions[-1].\n";
for (reverse 1 .. 9) {
    print "\rChanging back in $_ seconds...";
    sleep 1;
}
system("xrandr -s $current");
print "\rResolution returned to $current.     \n";
