#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/100_doors
#c# 2018-07-09 <RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

$result .= "Door $_ is open\n" for map $_**2, 1 .. 10;

say $result;

my $ref = <<END;
Door 1 is open
Door 4 is open
Door 9 is open
Door 16 is open
Door 25 is open
Door 36 is open
Door 49 is open
Door 64 is open
Door 81 is open
Door 100 is open
END

use Test::More;
is ($result, $ref);
done_testing();
