#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Take_notes_on_the_command_line
#c# 2018-08-12 <RC
#p# OK
#r# RC prep: cp ref/take-notes.base run/take-notes.txt
#i# RC cli: "new note 1"
#f# RC file: take-notes.txt

my $NOTES;
my $file = 'run/take-notes.txt';
if ( @ARGV ) {
  open($NOTES, '>>', $file) or die "Can't append to file $file: $!";
  print $NOTES "@ARGV\n";
  #print NOTES scalar localtime, "\n\t@ARGV\n";
} else {
  open $NOTES, '<', $file or die "Can't read file $file: $!";
  print <$NOTES>;
}
close $NOTES;
