#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Temperature_conversion
#c# 2018-08-11 <RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

my %scale = (
    Celcius    => { factor => 1  , offset => -273.15 },
    Rankine    => { factor => 1.8, offset =>    0    },
    Fahrenheit => { factor => 1.8, offset => -459.67 },
);

#print "Enter a temperature in Kelvin: ";
#chomp(my $kelvin = <STDIN>);

my $kelvin = 21;
die "No such temperature!\n" unless $kelvin > 0;

foreach (sort keys %scale) {
    $result .= sprintf "%12s:%8.2f\n", $_, $kelvin * $scale{$_}{factor} + $scale{$_}{offset};
}

#Enter a temperature in Kelvin: 21
say $result; 
my $ref = <<'EOD';
     Celcius: -252.15
  Fahrenheit: -421.87
     Rankine:   37.80
EOD

use Test::More;
is ($result, $ref);
done_testing;
