#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Terminal_control_Coloured_text
#t# interactive
#c# 2018-09-04 >RC
#p# OK

my %colors = (
    red     => "\e[1;31m", 
    green   => "\e[1;32m", 
    yellow  => "\e[1;33m",
    blue    => "\e[1;34m", 
    magenta => "\e[1;35m", 
    cyan    => "\e[1;36m"
);
$clr = "\e[0m";

print "$colors{$_}$_ text $clr\n" for sort keys %colors;

# the Perl 6 code also works in Perl...
use Term::ANSIColor;

use feature 'say';
say colored('RED ON WHITE', 'bold red on_white');
say colored('GREEN', 'bold green');
say colored('BLUE ON YELLOW', 'bold blue on_yellow');
say colored('MAGENTA', 'bold magenta');
say colored('CYAN ON RED', 'bold cyan on_red');
say colored('YELLOW', 'bold yellow');
