#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Textonyms
#c# 2018-08-10 >RC
#p# OK
#n# add some examples, someday

use strict;
use warnings;
use feature 'say';
my $result;

my $src = 'ref/unixdict.txt';
my(%h,@dials);
 
open my $fh, "<", $src;
my @words = grep { /^[a-zA-Z]+$/ } <$fh>;
map { tr/A-Z/a-z/ } @words;
map { tr/abcdefghijklmnopqrstuvwxyz/22233344455566677778889999/ } @dials = @words;
@dials = grep {!$h{$_}++} @dials;
my @textonyms = grep { $h{$_} > 1 } @dials;

#for (keys %t) { push @textonyms, $_ if $t{$_} > 1 } # not as nice

say $result = qq{There are @{[scalar @words]} words in $src which can be represented by the digit key mapping.
They require @{[scalar @dials]} digit combinations to represent them.
@{[scalar @textonyms]} digit combinations represent Textonyms.};

my $ref = <<'EOD';
There are 24978 words in ref/unixdict.txt which can be represented by the digit key mapping.
They require 22903 digit combinations to represent them.
1473 digit combinations represent Textonyms.
EOD

use Test::More;
chop $ref;
is($result,$ref);
done_testing;

__END__

say "Top 5 in ambiguity:";
say "    ",$_ for @textonyms.sort(-*.value)[^5];
 
say "\nTop 5 in length:";
say "    ",$_ for @textonyms.sort(-*.key.chars)[^5];

is( (+@words, +@dials, +@textonyms), '24978 22903 1473');
#is ~(@textonyms.sort(-*.key.chars)[^1]), "25287876746242\tclaustrophobia claustrophobic";

Top 5 in ambiguity:
    269 => amy any bmw bow box boy cow cox coy
    729 => paw pax pay paz raw ray saw sax say
    2273 => acre bard bare base cape card care case
    726 => pam pan ram ran sam san sao scm
    426 => gam gao ham han ian ibm ibn

Top 5 in length:
    25287876746242 => claustrophobia claustrophobic
    7244967473642 => schizophrenia schizophrenic
    666628676342 => onomatopoeia onomatopoeic
    49376746242 => hydrophobia hydrophobic
    2668368466 => contention convention
