#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Thiele\'s_interpolation_formula
#t# skiptest
#c# 2019-04-17 >RC
#p# OK
#n#  made default table size 12, 'invcos' converges slowly

use Data::Printer;

use strict;
use warnings;
use feature 'say';

use Math::Trig;

use constant pi => 2 * atan2(1, 0);
 
# reciprocal difference:
sub r {
    my($func, @x) = @_;

    if ($#x < 1) {
        return 0;
    } elsif ($#x == 1) {
        return &$func($x[0]);
        #return eval "$f($x[0])";
    } else {
          ($x[0] - $x[-1])        
        / (r(&$func, @x[0..$#x]  )     
        -  r(&$func, @x[1..$#x]  ) 
          )
        +  r(&$func, @x[1..$#x-2]); 
    }

}
 
# Thiele:
sub thiele {
    my($x, $hash, $ord) = @_;
    return 1 if $ord == scalar keys %$hash;

    #my $ff = sub { p @_; p %$f; say '--';p $$f{$_[0]};  $$f{$_[0]}};                # f(x) as a table lookup
    my $clos = sub { $$hash{$_[0]}};                # f(x) as a table lookup

$DB::single = 1 ;
    my $a = r($clos, (sort keys %$hash)[0 .. $ord+1]);
    my $b = r($clos, (sort keys %$hash)[0 .. $ord-1]);
 
say "x: $x";
say "ord: $ord";
say "abc: "  . join ' :: ', (sort keys %$hash)[$ord];
    my $num = $x - (sort keys %$hash)[$ord];
    my $cont = thiele($x, $hash, $ord+1);
    #my $cont = thiele($x, \%$f, $ord+1);
 
    # Thiele always takes this form:
    return $a - $b + ( $num / $cont );
}
 
sub mk_inv {
    my ($fn, $d, $lim) = @_;
    my %h;
    for (0..$lim) { $h{ eval "$fn($_ * $d)" } = $_ * $d }
    return %h;
}
 
my $tblsz = 12;
 
#my ($sin_pi, $cos_pi, $tan_pi);
my %invsin = mk_inv('sin', 0.05, $tblsz); 
$DB::single = 1 ;
my $sin_pi = 6 * thiele(0.5, \%invsin, 0);
my %invcos = mk_inv('cos', 0.05, $tblsz); #$cos_pi = 3 * thiele(0.5, %invcos, 0);
my %invtan = mk_inv('tan', 0.05, $tblsz); #$tan_pi = 4 * thiele(1.0, %invtan, 0);
 
say 'pi = ' . pi;
  say "estimations using a table of $tblsz elements:";
  #say "sin interpolation: $sin_pi";
  #say "cos interpolation: $cos_pi";
  #say "tan interpolation: $tan_pi";

use Test::More;
#is ($sin_pi), '3.1415926535896332'
#is($cos_pi, '3.138724321984095';
#is($tan_pi, '3.14163334892717';
#done_testing();

__END__

=={{header|Perl}}==
{{trans|Perl 6}}
<lang perl></lang>
{{out}}
<pre style="height:35ex"></pre>
[https://github.com/SqrtNegInf/Rosettacode-Perl5-Smoke/blob/master/ref/XXX XXX]
