#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Totient_function
#c# 2018-12-06 >RC
#p# OK
#n# but see -2 variant for ntheory/speed

use feature 'say';
use warnings;

use utf8;
binmode STDOUT, ":utf8";

my @res;

sub gcd {
  my ($u, $v) = @_;
  while ($v) {
    ($u, $v) = ($v, $u % $v);
  }
  return abs($u);
}

# Sidef
#for $t (1..10000) {
#    push @𝜑, ?? #($𝜑[0]-1) * p[0]**(p[1]-1)
#}

sub totient {
    my($n) = @_;
    $tot = $n;
    for ($i= 2; $i*$i <= $n; $i += 2) {
        if ($n%$i == 0) {
            for ($n%$i == 0) {
                $n /= $i;
            }
            $tot -= $tot / $i;
        }
        $i = 1 if $i == 2;
    }
    $tot -= $tot / $n if $n > 1;
    $tot
} 

push @𝜑, 0;
for $t (1..100) {
    push @x, totient($t);
    push @𝜑, scalar grep { 1 == gcd($_,$t) } 1..$t;
}

say join ' ', @𝜑[0..20];
say join ' ', @x[0..20];
exit;

push @res, sprintf "𝜑(%2d) = %3d%s", $_, $𝜑[$_], $_ - $𝜑[$_] - 1 ? '' : ' Prime' for 1 .. 25;
 
for $limit (100, 1000, 10000) {
    push @res, "\nCount of primes <= $limit: " . grep {$_ == $𝜑[$_] + 1} 0..$limit;
}

say $result = join "\n", @res;
exit;

my $ref = <<'EOD';
𝜑( 1) =   1
𝜑( 2) =   1 Prime
𝜑( 3) =   2 Prime
𝜑( 4) =   2
𝜑( 5) =   4 Prime
𝜑( 6) =   2
𝜑( 7) =   6 Prime
𝜑( 8) =   4
𝜑( 9) =   6
𝜑(10) =   4
𝜑(11) =  10 Prime
𝜑(12) =   4
𝜑(13) =  12 Prime
𝜑(14) =   6
𝜑(15) =   8
𝜑(16) =   8
𝜑(17) =  16 Prime
𝜑(18) =   6
𝜑(19) =  18 Prime
𝜑(20) =   8
𝜑(21) =  12
𝜑(22) =  10
𝜑(23) =  22 Prime
𝜑(24) =   8
𝜑(25) =  20

Count of primes <= 100: 25

Count of primes <= 1000: 168

Count of primes <= 10000: 1229
EOD

use Test::More;
chop $ref;
is($result, $ref);
done_testing();

__END__

=={{header|Perl}}==
{{trans|Perl 6}}
<lang perl></lang>
{{out}}
<pre style="height:35ex"></pre>
