#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Towers_of_Hanoi
#c# 2018-08-09 <RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

sub hanoi {
    my ($n, $from, $to, $via) = (@_, 1, 2, 3);

    if ($n == 1) {
        $result .= "Move disk from pole $from to pole $to.\n";
    } else {
        hanoi($n - 1, $from, $via, $to);
        hanoi(1, $from, $to, $via);
        hanoi($n - 1, $via, $to, $from);
    };
};

hanoi(4);

say $result; 
my $ref = <<'EOD';
Move disk from pole 1 to pole 3.
Move disk from pole 1 to pole 2.
Move disk from pole 3 to pole 2.
Move disk from pole 1 to pole 3.
Move disk from pole 2 to pole 1.
Move disk from pole 2 to pole 3.
Move disk from pole 1 to pole 3.
Move disk from pole 1 to pole 2.
Move disk from pole 3 to pole 2.
Move disk from pole 3 to pole 1.
Move disk from pole 2 to pole 1.
Move disk from pole 3 to pole 2.
Move disk from pole 1 to pole 3.
Move disk from pole 1 to pole 2.
Move disk from pole 3 to pole 2.
EOD

use Test::More;
is ($result, $ref);
done_testing;
