#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Truncatable_primes
#c# 2018-08-09 <RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

use ntheory ":all";

my @lprimes = my @rprimes = (2,3,5,7);

@lprimes = sort { $a <=> $b }
           map { my $p=$_; map { is_prime($_.$p) ? $_.$p : () } 1..9 } @lprimes
  for 2..6;

@rprimes = sort { $a <=> $b }
           map { my $p=$_; map { is_prime($p.$_) ? $p.$_ : () } 1..9 } @rprimes
  for 2..6;

$result = "ltrunc: $lprimes[-1]\nrtrunc: $rprimes[-1]\n";

say $result;

my $ref = <<'END';
ltrunc: 998443
rtrunc: 739399
END

use Test::More;
is ($result, $ref);
done_testing;
