#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Two%27_complement
#t# inprogress
#c# 2022-xx-xx >RC
#p# OK

my @res;

use v5.36;
#use strict; use warnings; use feature 'say';

use bigint;

sub bin2dec { unpack('Q>', pack('B64', substr('0' x 64 . shift, -64))) }
sub bin2dec32 { unpack('N', pack('B32', substr('0' x 32 . shift, -32))) }

say bin2dec32 '010000000000000000000000000000000'; 
say '--';
say '10' x 32;
say bin2dec '10' x 32;
say '--';
#say my $y = 12297829382473034410;
#printf "%064b\n",  $y;
#say -$y;
#printf "%064b\n", -$y;
#say '--';
say my $z = 6148914691236517205;
printf "%064b\n",  $z;
say -$z;
printf "%064b\n", -$z;

__END__

say my $result = join "\n", @res;
my $ref = <<'END';
END

use Test::More;
chomp $ref;
is($result, $ref);
#is(($result =~ s/\s//gr), ($ref =~ s/\s//gr));
done_testing();

__END__

=={{header|Perl}}==
{{trans|xx}}
{{libheader|ntheory}}
<syntaxhighlight lang="perl" line>
</syntaxhighlight>
{{out}}
<pre style="height:20ex">
</pre>
[[File:xx|300px|thumb|right]]
# or
[https://github.com/SqrtNegInf/Rosettacode-Perl-Smoke/blob/master/ref/xx xx]
