#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Two_Sum
#c# 2018-08-09 <RC, 2019-03-16 >RC
#p# OK

use strict;
use warnings;
use feature 'say';
my $result;

# Translation of: Python (which claims to a translation of Perl 6?)

sub two_sum{
  my($sum,@numbers) = @_;
  my $i = 0;
  my $j = $#numbers - 1;
  my @indices;
  while ($i < $j) {
    if    ($numbers[$i] + $numbers[$j] == $sum) { push @indices, ($i, $j); $i++; }
    elsif ($numbers[$i] + $numbers[$j]  < $sum) { $i++ }
    else                                { $j-- }
  }
  return @indices
}

my @numbers = <0 2 11 19 90>;
my @indices = two_sum(21, @numbers);
say join(', ', @indices) || 'No match';
$result .= join ' ', @indices;

@indices = two_sum(25, @numbers);
say join(', ', @indices) || 'No match';
$result .= join ' ', @indices;

my $ref = <<'EOD';
1 3
EOD

use Test::More;
chomp $ref;
is ($result, $ref);
done_testing;
