#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Unique_characters
#c# 2021-05-06 <RC
#p# OK

use strict;
use warnings;
use feature 'say';

use utf8;
use Unicode::Collate 'sort';

my %seen;
binmode(STDOUT, ':encoding(utf8)');
map { s/(\X)/$seen{$1}++/egr } 
   "133252abcdeeffd", "a6789798st", "yxcdfgxcyz", "AАΑSäaoö٥🤔👨‍👩‍👧‍👧";
my $uca = Unicode::Collate->new();

say my $result = join '', $uca->sort ( grep { $seen{$_} == 1 } keys %seen );

my $ref = '👨‍👩‍👧‍👧🤔15٥6AäbgoösStzΑА';

use Test::More;
is ($result, $ref);
done_testing();
