#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/URL_decoding
#c# 2018-08-07 <RC
#p# OK

use feature 'say';
my $result;

sub urldecode {
    my $s = shift;
    $s =~ tr/\+/ /;
    $s =~ s/\%([A-Fa-f0-9]{2})/pack('C', hex($1))/eg;
    return $s;
}

$result .= urldecode('http%3A%2F%2Ffoo+bar%2F')."\n";

use strict ;
use URI::Escape ;

my $encoded = "http%3A%2F%2Ffoo%20bar%2F" ;
my $unencoded = uri_unescape( $encoded ) ;
$result .= "The unencoded string is $unencoded !\n" ;


say $result; 
my $ref = <<'EOD';
http://foo bar/
The unencoded string is http://foo bar/ !
EOD

use Test::More;
is ($result, $ref);
done_testing;
