#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Halt_and_catch_fire
#c# 2021-09-12 >RC
#p# OK
#n# all these statements pass 'perl -c' but crash one way or another upon execution
#n# subroutine form works better with v5.36+

use Test::More tests => 3;
use Test::Exception;

dies_ok( sub { &a  }, 'dies_ok' );
dies_ok( sub { 1/0 }, 'dies_ok' );
dies_ok( sub { die }, 'dies_ok' );

#'dies ok' if dies_ok { &a  };
#'dies ok' if dies_ok { 1/0 };
#'dies ok' if dies_ok { die };
