#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Haversine_formula
#c# 2022-05-31 <RC
#p# OK
#n# Math::Trig is part of the Perl core distribution

use strict;
use warnings;
use feature 'say';

my $result;

use Math::Trig qw(great_circle_distance deg2rad);
 
# Notice the 90 - latitude: phi zero is at the North Pole.
# Parameter order is: LON, LAT
my @BNA = (deg2rad(-86.67), deg2rad(90 - 36.12));
my @LAX = (deg2rad(-118.4), deg2rad(90 - 33.94));
 
say $result = sprintf "Distance: %.3f km", great_circle_distance(@BNA, @LAX, 6372.8);

use Test::More;
is ($result, 'Distance: 2887.260 km');
done_testing;
