#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Hello_world/Text
#t# skiptest
#c# 2018-08-12 <RC
#p# OK

# Works with: Perl version 5.8.8
print "Hello world!\n";

# Works with: Perl version 5.10.x
# Backported from Perl 6:
use feature 'say';
say 'Hello world!';

# or:
use 5.010;
say 'Hello world!';
