#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Hello_world/Newline_omission
#t# skiptest
#c# 2018-08-12 <RC
#p# OK

my $msg = "Goodbye, World!";

print $msg;    # A newline does not occur automatically

my $result = sprintf "%s", $msg;

use Test::More;
is $result, $msg;
done_testing;
