#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Hello_world/Line_printer
#t# skiptest
#c# 2018-08-12 <RC
#p# OK
#n# Assuming that the line printer is attached to /dev/lp0 (all very silly)

open my $P, ">", "/dev/lp0";
print $P "Hello World!\n";
close $P;
