#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Hofstadter_Q_sequence
#c# 2018-08-13 <RC
#p# OK

use strict;
use warnings;
use feature 'say';
my @res;

my @Q = (0,1,1);
push @Q, $Q[-$Q[-1]] + $Q[-$Q[-2]] for 1..100_000;
push @res, "First 10 terms: [@Q[1..10]]";
push @res, "Term 1000: $Q[1000]";
push @res, "Terms less than preceding in first 100k: ".scalar(grep { $Q[$_] < $Q[$_-1] } 2..100000);

say my $result = join "\n", @res;
my $ref = <<'END';
First 10 terms: [1 1 2 3 3 4 5 5 6 6]
Term 1000: 502
Terms less than preceding in first 100k: 49798
END

use Test::More;
chop $ref;
is ($result, $ref);
done_testing;
