#!/usr/local/bin/perl
#u# https://rosettacode.org/wiki/Honaker_primes
#c# 2022-09-24 >RC
#p# OK

my @res;

use v5.36;

use ntheory 'nth_prime';
use List::Util <max sum>;

sub table ($c, @V) { my $t = $c * (my $w = 2 + max map { length } @V); ( sprintf( ('%'.$w.'s')x@V, @V) ) =~ s/.{1,$t}\K/\n/gr }
sub comma { scalar reverse join ',', unpack '(A3)*', reverse shift }

my($n,@honaker); 

while () {
    my $p = nth_prime(++$n);
    push @honaker, [$n, $p] if (sum split '', $p) == sum split '', $n;
    last if 10_000 == @honaker;
}

push @res, "First 50 Honaker primes (index, prime):";
push @res, table 5, map { sprintf "(%3d, %4d)", @$_ } @honaker[0..49];

push @res, "Ten thousandth: " . sprintf "(%s, %s)", map { comma $_ } @{$honaker[9999]};

say my $result = join "\n", @res;

my $ref = <<'END';
First 50 Honaker primes (index, prime):
  ( 32,  131)  ( 56,  263)  ( 88,  457)  (175, 1039)  (176, 1049)
  (182, 1091)  (212, 1301)  (218, 1361)  (227, 1433)  (248, 1571)
  (293, 1913)  (295, 1933)  (323, 2141)  (331, 2221)  (338, 2273)
  (362, 2441)  (377, 2591)  (386, 2663)  (394, 2707)  (397, 2719)
  (398, 2729)  (409, 2803)  (439, 3067)  (446, 3137)  (457, 3229)
  (481, 3433)  (499, 3559)  (508, 3631)  (563, 4091)  (571, 4153)
  (595, 4357)  (599, 4397)  (635, 4703)  (637, 4723)  (655, 4903)
  (671, 5009)  (728, 5507)  (751, 5701)  (752, 5711)  (755, 5741)
  (761, 5801)  (767, 5843)  (779, 5927)  (820, 6301)  (821, 6311)
  (826, 6343)  (827, 6353)  (847, 6553)  (848, 6563)  (857, 6653)

Ten thousandth: (286,069, 4,043,749)
END

use Test::More;
chomp $ref;
is($result, $ref);
done_testing();
