#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Host_introspection
#c# 2023-07-17 NOT ON RC
#p# OK
#n# 2023-07-17 goof around with 'match'

use strict;
use warnings;
use feature 'say';

use Syntax::Keyword::Match;
use Config;

my ($size, $order, $end) = @Config{qw(uvsize byteorder)};
match($order : eq) {
    case (join '', sort split '', $order)         { $end = 'little' }   # sadly, doesn't alias $_ here
    case (join '', reverse sort split '', $order) { $end = 'big'    }   #              "
    default { $end = 'mixed' }
}
say my $result = "UV size: $size, byte order: $order ($end-endian)";

use Test::More;
is ($result, 'UV size: 8, byte order: 12345678 (little-endian)');
done_testing;
