#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Host_introspection
#c# 2018-08-13 <RC
#p# OK

use strict;
use warnings;
use feature 'say';
my $result;

use Config;
say $result .= "UV size: $Config{uvsize}, byte order: $Config{byteorder}";

use Test::More;
is ($result, 'UV size: 8, byte order: 12345678');
done_testing;
