#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Hostname
#c# 2018-08-13 <RC
#p# OK

use feature 'say';
my $result;

use Sys::Hostname;

say $name = hostname;

my $line = `uname -a`;
my($ref) = $line =~ /Darwin (\S+)/;

use Test::More;
is ($name, $ref);
done_testing();
