#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Hostname
#c# 2018-08-13 <RC
#p# OK
#n# works on all platforms now

use feature 'say';
my $result;

use Sys::Hostname;

say $name = hostname;

my($ref) = `uname -a` =~ /\S+ (\S+)/;

use Test::More;
is ($name, $ref);
done_testing();
