#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/HTTP
#c# 2018-08-11 <RC
#p# OK

use feature 'say';
my $result;


# Core example[edit]
# Library: HTTP/Tiny
# Works with: Perl version 5.14
# Works with: Perl/HTTP/Tiny
# This sample is nearly identical to the LWP sample except that it uses HTTP::Tiny which was added to the core libraries in Perl/5.14.

#use strict; use warnings;
require 5.014; # check HTTP::Tiny part of core
use HTTP::Tiny;

$rc0 = ( HTTP::Tiny->new()->get( 'http://rosettacode.org')->{content} );
#Library examples[edit]
#Library: LWP[edit]
#Works with: Perl/LWP
#Classic LWP sample.

use LWP::Simple qw/get $ua/;
$ua->agent(undef) ; # cloudflare blocks default LWP agent
$rc1 = join '', get("http://www.rosettacode.org");

#or with more error-checking

#use LWP::UserAgent;

#my $url = 'http://www.rosettacode.org';
#my $rc2 = LWP::UserAgent->new->get( $url );

#$response->is_success or die "Failed to GET '$url': ", $response->status_line;
#print $response->as_string;

#say length $rc0;
#say length $rc1;

use Test::More;
ok (20000 < length $rc0);
ok (20000 < length $rc1);
done_testing();
