#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/HTTP
#c# 2018-08-11 <RC
#p# OK
#n# very minimal testing
#n# 2023-08-21 'www' prefix not currently valid [should be safe to leave it off for good]

use strict;
use warnings;
use feature 'say';

use HTTP::Tiny;
my $rc0 = ( HTTP::Tiny->new()->get( 'http://rosettacode.org')->{content} );
say length $rc0;

use LWP::Simple qw/get $ua/;
$ua->agent(undef) ; # cloudflare blocks default LWP agent
my $rc1 = join '', get("https://rosettacode.org");

#or with more error-checking
use LWP::UserAgent;
my $url = 'http://rosettacode.org';
my $rc2 = LWP::UserAgent->new->get( $url );
$rc2->is_success or die "Failed to GET '$url': ", $rc2->status_line;
#print $rc2->as_string;
say length $rc1;

use Test::More;
ok (20000 < length $rc0);
ok (20000 < length $rc1);
done_testing;
