#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/HTTPS
#c# 2018-08-11 <RC
#p# OK

use strict;
use warnings;
use feature 'say';
use LWP::UserAgent;

my $url = 'https://www.google.com';

#my $response = LWP::UserAgent->new->get( $url ); # this works too

my $ua = LWP::UserAgent->new( protocols_allowed => ['http', 'https']);
my $response = $ua->get($url);

$response->is_success or die "Failed to GET '$url': ", $response->status_line;

say my $result = $response->status_line;
#print $response->as_string;

use Test::More;
is ($result, '200 OK');
done_testing;
