#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Order_by_pair_comparisons
#c# 2021-04-15 <RC
#p# OK
#=# RC pipe: >\n<\n>\n<\n<\n>\n<\n<\n<\n<\n>\n<\n>
#n# yes, I messed the order, but the code works...

use strict;
use warnings;
use feature 'say';

sub ask {
  while (1) {
    #print "Compare $a to $b [<,=,>]: ";
    <STDIN> =~ /[<=>]/ and return +{qw( < -1 = 0 > 1 )}->{$&};
  }
}

my @sorted = sort ask qw( violet red green indigo blue yellow orange );
say my $result = "sorted: @sorted";

my $ref = 'sorted: red yellow orange green blue indigo violet';

use Test::More;
is ($result, $ref);
done_testing();

