#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Largest_difference_between_adjacent_primes
#c# 2021-11-xx >RC
#p# OK

my @res;

use strict;
use warnings;
use feature 'say';

use Primesieve qw(generate_primes);

for my $n (2..8) {
    my @primes = generate_primes (10**($n-1), 10**$n);
    my($x,$y,$d) = (0,0,0);
    map { ($d = $primes[$_] - $primes[$_-1]) > $x and ($x,$y) = ($d,$_-1) } 1..$#primes;
    push @res, sprintf "Largest prime gap up to %d: %d - between %d and %d.", 10**$n, $x, @primes[$y,$y+1];
}

say my $result = join "\n", @res;

my $ref = <<'END';
Largest prime gap up to 100: 8 - between 89 and 97.
Largest prime gap up to 1000: 20 - between 887 and 907.
Largest prime gap up to 10000: 36 - between 9551 and 9587.
Largest prime gap up to 100000: 72 - between 31397 and 31469.
Largest prime gap up to 1000000: 114 - between 492113 and 492227.
Largest prime gap up to 10000000: 154 - between 4652353 and 4652507.
Largest prime gap up to 100000000: 220 - between 47326693 and 47326913.
END

use Test::More;
chomp $ref;
is($result, $ref);
done_testing();

__END__

=={{header|Perl}}==
<lang perl>
</lang>
{{out}}
<pre>
</pre>
