#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Largest_difference_between_adjacent_primes
#c# 2021-11-19 >RC
#p# OK

my @res;

use strict;
use warnings;
use feature 'say';

use Primesieve qw(generate_primes);

for my $n (2..8) {
    my @primes = generate_primes (1, 10**$n);
    my($max,$p,$diff) = 0;
    map { ($diff = $primes[$_] - $primes[$_-1]) > $max and ($max,$p) = ($diff,$_-1) } 1..$#primes;
    push @res, sprintf "Largest prime gap up to %d: %d - between %d and %d.", 10**$n, $max, @primes[$p,$p+1];
    say "Largest prime gap up to 10**$n: $max - between " . join(' and ', @primes[$p,$p+1]);
}

my $result = join "\n", @res;

my $ref = <<'END';
Largest prime gap up to 100: 8 - between 89 and 97.
Largest prime gap up to 1000: 20 - between 887 and 907.
Largest prime gap up to 10000: 36 - between 9551 and 9587.
Largest prime gap up to 100000: 72 - between 31397 and 31469.
Largest prime gap up to 1000000: 114 - between 492113 and 492227.
Largest prime gap up to 10000000: 154 - between 4652353 and 4652507.
Largest prime gap up to 100000000: 220 - between 47326693 and 47326913.
END
# Largest prime gap up to 1000000000: 282 - between 436273009 and 436273291.

use Test::More;
chomp $ref;
is($result, $ref);
done_testing();
