#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Largest_five_adjacent_number
#c# 2021-09-27 <RC
#p# OK

srand 123456;

use strict;
use warnings;
use feature 'say';

my @n;

$_ = join '', map int rand 10, 1 .. 1e3;
$n[$1] = $1 while /(?=(\d{5}))/g;
say my $result = $n[-1];

# or...
@n[ /(?=(\d{5}))/g ] = ();
print "$#n\n";

use Test::More;
is($result, 99830);
done_testing();
