#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Last_Friday_of_each_month
#c# 2018-08-14 <RC
#p# OK
#n# cf. Find_the_last_Sunday_of_each_month

use strict;
use warnings;
use feature 'say';
my $result;

use DateTime ;

foreach my $month ( 1..12 ) {
   my $dt = DateTime->last_day_of_month( year => 2012 , month => $month ) ;
   #my $dt = DateTime->last_day_of_month( year => $ARGV[ 0 ] , month => $month ) ;
   while ( $dt->day_of_week != 5 ) {
      $dt->subtract( days => 1 ) ;
   }
   $result .= $dt->ymd . "\n";
}

say $result; 
my $ref = <<'EOD';
2012-01-27
2012-02-24
2012-03-30
2012-04-27
2012-05-25
2012-06-29
2012-07-27
2012-08-31
2012-09-28
2012-10-26
2012-11-30
2012-12-28
EOD

use Test::More;
is ($result, $ref);
done_testing;
