#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Least_square
#c# 2021-11-18 <RC
#p# OK
#n# Lordy, the mind of Calmosoft: let's get trivial!  Anyways, goof around a bit...

use strict;
use warnings;
use feature 'say';

my $n = 1;
$n++ until $n ** 2 - ($n-1) ** 2 > 1000;
say $n;

my($x, $y, $z) = (1, 3.14, 123456);
$x++ until $x ** $y - ($x-1) ** $y > $z;
say $x;

my $d = 0.01;
($x, $y, $z) = (1, 3.14, 123456);
$x += $d until $x ** $y - ($x-$d) ** $y > $z;
say $x;

($x, $y, $z) = (1, 1/3.14, 1/123456);
$x++ until $x ** $y - ($x-1) ** $y < $z;
say $x;

use Test::More;
is ($n, 501);
done_testing();
