#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Length_of_an_arc_between_two_angles
#c# 2020-03-23 >RC
#p# OK
#n# Raku modulus and POSIX 'fmod' disagree?

use strict;
use warnings;
use feature 'say';

use utf8;
binmode STDOUT, ":utf8";
use POSIX 'fmod';

my @res;

use constant π => 2 * atan2(1, 0);
use constant τ => 2 * π;

sub d2r { $_[0] * τ / 360 }

sub arc {
    my($a1, $a2, $r) = (d2r($_[0]), d2r($_[1]), $_[2]);
    my @a = map { fmod( ($_ + τ), τ) } ($a1, $a2);
    push @res, sprintf "Arc length: %8.5f  Parameters: (%9.7f, %10.7f, %10.7f)", 
       (fmod(($a[0]-$a[1] + τ), τ) * $r), $a2, $a1, $r;
}

arc(@$_) for 
    [ 10, 120,   10],
    [ 10, 120,    1],
    [120,  10,    1],
    [-90, 180, 10/π],
    [-90,   0, 10/π],
    [ 90,   0, 10/π];

say my $result = join "\n", @res;

my $ref = <<'END';
Arc length: 43.63323  Parameters: (2.0943951,  0.1745329, 10.0000000)
Arc length:  4.36332  Parameters: (2.0943951,  0.1745329,  1.0000000)
Arc length:  1.91986  Parameters: (0.1745329,  2.0943951,  1.0000000)
Arc length:  5.00000  Parameters: (3.1415927, -1.5707963,  3.1830989)
Arc length: 15.00000  Parameters: (0.0000000, -1.5707963,  3.1830989)
Arc length:  5.00000  Parameters: (0.0000000,  1.5707963,  3.1830989)
END

use Test::More;
chomp $ref;
is($result, $ref);
done_testing;
