#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Literals/Floating_point
#t# nocode
#c# 2018-08-15 <RC
#p# OK

=head 

# Standard notations:
.5;
0.5;
1.23345e10;
1.23445e-10;

# The numbers can be grouped:
100_000_000;	# equals to 100000000

=cut
