#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Loops/Continue
#c# 2018-08-17 <RC
#p# OK

my($result1,$result2);

use strict;
use warnings;
use feature 'say';

for (1..10) {
    $result1 .= $_;
    if ($_ % 5 == 0) {
        $result1 .= "\n";
        next;
    }
    $result1 .= ', ';
}

#It is also possible to use a goto statement
#to jump over the iterative code section for a particular loop:

for (1..10) {
    $result2 .= $_;
    if ($_ % 5 == 0) {
        $result2 .= "\n";
        goto MYLABEL;
    }
    $result2 .= ', ';
MYLABEL:
}

say $result1; 

my $ref = <<'EOD';
1, 2, 3, 4, 5
6, 7, 8, 9, 10
EOD

use Test::More;
is ($result1, $ref);
is ($result2, $ref);
done_testing;
