#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Loops/Break
#c# 2018-08-17 <RC
#p# OK

my $result;

srand 123456;

use strict;
use warnings;
use feature 'say';

while () {
    my $a = int(rand(20));
    $result .= "$a\n";
    if ($a == 10) {
        last;
    }
    my $b = int(rand(20));
    $result .= "$b\n";
}

say $result; 

my $ref = <<'EOD';
18
13
12
4
1
5
4
19
10
EOD

use Test::More;
is ($result, $ref);
done_testing();
