#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Loops/N_plus_one_half
#c# 2018-08-17 <RC
#p# OK

use feature 'say';
my $result;

for my $i(1..10) {
    $result .= $i;
    last if $i == 10;
    $result .= ', ';
}
$result .= "\n";

#In perl one would solve the task via join.
$result .= join(', ', 1..10). "\n";


say $result; 
my $ref = <<'EOD';
1, 2, 3, 4, 5, 6, 7, 8, 9, 10
1, 2, 3, 4, 5, 6, 7, 8, 9, 10
EOD

use Test::More;
is ($result, $ref);
done_testing();
