#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Loops/Nested
#c# 2018-08-17 <RC
#p# OK

my $result;

srand 12345;

use strict;
use warnings;
use feature 'say';

my $a = [ map [ map { int(rand(20)) + 1 } 1 .. 10 ], 1 .. 10];

Outer:
foreach (@$a) {
    foreach (@$_) {
        $result .= " $_";
        if ($_ == 20) {
            last Outer;
        }
    }
    $result .= "\n";
}
$result .= "\n";


say $result; 
my $ref = <<'EOD';
 5 19 5 15 15 19 7 18 9 4
 14 11 4 20
EOD

use Test::More;
is ($result, $ref);
done_testing();
