#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Loops/Do-while
#c# 2018-08-17 <RC
#p# OK

my($result1,$result2);

use strict;
use warnings;
use feature 'say';

my $val = 0;
do {
   $val++;
   $result1 .= "$val\n";
} while ($val % 6);

# do ... until (condition) is equivalent to do ... while (not condition).
$val = 0;
do {
   $val++;
   $result2 .= "$val\n";
} until ($val % 6 == 0);

say $result1;

my $ref = <<'EOD';
1
2
3
4
5
6
EOD

use Test::More;
is ($result1, $ref);
is ($result2, $ref);
done_testing();
