#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Lucas-Lehmer_test
#c# 2018-08-17 <RC
#p# OK

use strict;
use warnings;
use feature 'say';
my $result;

# Using Math::GMP:
use Math::GMP qw/:constant/;

sub is_prime { Math::GMP->new(shift)->probab_prime(12); }

sub is_mersenne_prime {
  my $p = shift;
  return 1 if $p == 2;
  my $mp = 2 ** $p - 1;
  my $s = 4;
  $s = ($s * $s - 2) % $mp  for 3..$p;
  $s == 0;
}

foreach my $p (2 .. 43_112_609) {
  $result .= "M$p\n" if is_prime($p) && is_mersenne_prime($p);
  last if $p == 4423;
}

say $result; 

my $ref = <<'EOD';
M2
M3
M5
M7
M13
M17
M19
M31
M61
M89
M107
M127
M521
M607
M1279
M2203
M2281
M3217
M4253
M4423
EOD

use Test::More;
is ($result, $ref);
done_testing;
