#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Date_format
#c# 2018-07-28 <RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

use POSIX;
 
$result .= strftime('%Y-%m-%d', 0, 0, 0, 10, 10, 107). "\n";
$result .= strftime('%A, %B %d, %Y', 0, 0, 0, 10, 10, 107). "\n";

say $result; 

my $ref = <<'EOD';
2007-11-10
Saturday, November 10, 2007
EOD

use Test::More;
is ($result, $ref);
done_testing();
