#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Day_of_the_week
#c# 2018-07-28 <RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

use DateTime;

foreach my $i (2008 .. 2121) {
    my $dt = DateTime->new( year   => $i,
                          month  => 12,
                          day    => 25
                        );
    if ( $dt->day_of_week == 7 ) {
        $result .= "25 Dec $i is Sunday\n";
    }
}

say $result;

my $ref = <<'END';
25 Dec 2011 is Sunday
25 Dec 2016 is Sunday
25 Dec 2022 is Sunday
25 Dec 2033 is Sunday
25 Dec 2039 is Sunday
25 Dec 2044 is Sunday
25 Dec 2050 is Sunday
25 Dec 2061 is Sunday
25 Dec 2067 is Sunday
25 Dec 2072 is Sunday
25 Dec 2078 is Sunday
25 Dec 2089 is Sunday
25 Dec 2095 is Sunday
25 Dec 2101 is Sunday
25 Dec 2107 is Sunday
25 Dec 2112 is Sunday
25 Dec 2118 is Sunday
END

use Test::More;
is ($result, $ref);
done_testing();
