#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Determine_if_only_one_instance_is_running
#t# skiptest
#c# 2018-07-28 <RC
#p# OK

# The INIT block is run just before the Perl runtime begins execution. See perlmod
# Then it tries to get a lock to its own file, from where the script was called.

use Fcntl ':flock';
 
INIT
{
die "Not able to open $0\n" unless (open my $ME, '<', $0);
	die "I'm already running !!\n" unless(flock $ME, LOCK_EX|LOCK_NB);
}
 
sleep 2; # then your code goes here
