#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Display_a_linear_combination
#c# 2020-01-24 <>RC
#p# OK
#n# oops, 'strict' compliant now (my own code, but didn't have it in my own collection for some reason...)

use strict;
use warnings;
use feature 'say';

my $result;

sub linear_combination {
    my(@coef) = @$_;
    my $e = '';
    for my $c (1..+@coef) { $e .= "$coef[$c-1]*e($c) + " if $coef[$c-1] }
    #$coef[$_-1] and $e .= "$coef[$_-1]*e($_) + " for 1 .. +@coef;  # DH obscure, not for RC
    $e =~ s/ \+ $//;
    $e =~ s/1\*//g;
    $e =~ s/\+ -/- /g;
    $e or 0;
}

$result .= linear_combination($_) . "\n" for
  [1, 2, 3], [0, 1, 2, 3], [1, 0, 3, 4], [1, 2, 0], [0, 0, 0], [0], [1, 1, 1], [-1, -1, -1], [-1, -2, 0, -3], [-1];

say $result;

my $ref = <<'EOD';
e(1) + 2*e(2) + 3*e(3)
e(2) + 2*e(3) + 3*e(4)
e(1) + 3*e(3) + 4*e(4)
e(1) + 2*e(2)
0
0
e(1) + e(2) + e(3)
-e(1) - e(2) - e(3)
-e(1) - 2*e(2) - 3*e(4)
-e(1)
EOD

use Test::More;
is ($result, $ref);
done_testing;
