#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/DNS_query
#c# 2018-07-28 <RC
#p# OK
#n# use 'orange.kame.net', like Raku
#n# code to display IP* different on RC

use strict;
use warnings;
use feature 'say';

#require 5.014; # older versions can't resolve IPv6 with just core Socket module # stale!
 
use Socket qw(getaddrinfo getnameinfo);
my ($err, @res) = getaddrinfo("orange.kame.net", 0,
                { protocol=>Socket::IPPROTO_TCP } );
die "getaddrinfo error: $err" if $err;
 
my @r1 = getnameinfo($res[0]->{addr}, Socket::NI_NUMERICHOST);
my @r2 = getnameinfo($res[1]->{addr}, Socket::NI_NUMERICHOST);
print "$r1[1]\n";
print "$r2[1]\n";

use Test::More;
is $r1[1], '203.178.141.194';
is $r2[1], '2001:200:dff:fff1:216:3eff:feb1:44d7';
done_testing();
