#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Dot_product
#c# 2018-07-28 <RC
#p# OK

use strict;
use warnings;
use feature 'say';
my $result;

sub dotprod
{
        my($vec_a, $vec_b) = @_;
        die "they must have the same size\n" unless @$vec_a == @$vec_b;
        my $sum = 0;
        $sum += $vec_a->[$_] * $vec_b->[$_] for 0..$#$vec_a;
        return $sum;
}
 
my @vec_a = (1,3,-5);
my @vec_b = (4,-2,-1);
 
$result = dotprod(\@vec_a,\@vec_b);# "\n"; # 3

use Test::More;
is ($result, 3);
done_testing;
