#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Draw_a_cuboid
#c# 2018-07-30 <RC
#p# OK

use strict;
use warnings;
srand 123456;

use feature 'say';
my $result;

sub cuboid {
 
    # Constant dimnesions of the cuboid
    my ($x, $y, $z) = map int, @_[0 .. 2];
 
    # ASCII characters
    # $c = corner point
    # $h = horizontal line
    # $v = vertical line
    # $d = diagonal line
    # $s = space (inside the cuboid)
    my ($c, $h, $v, $d, $s) = ('+', '-', '|', '/', shift(@ARGV) // q{ });

# say q{ } x ($z - $_ + 1), $d, $s x $x, $d, $s x ($_ - ($_ > $y ? ($_ - $y) : 1)),
#      $_ - 1 == $y ? $c : $_ > $y ? $d : $v for 1 .. $z;

 
    $result .= (q{ } x ($z + 1)) . $c . ($h x $x) . $c . "\n";
    $result .= (q{ } x ($z - $_ + 1)) . $d . ($s x $x) . $d . ($s x ($_ - ($_ > $y ? ($_ - $y) : 1))) .
      ($_ - 1 == $y ? $c : $_ > $y ? $d : $v) . "\n" for 1 .. $z;
    $result .= $c . ($h x $x) . $c . ($s x ($z < $y ? $z : $y)) . ($z < $y ? $v : ($z == $y ? $c : $d)) . "\n";
    $result .= $v . ($s x $x). $v . ($z > $y ? ($_ >= $z ? ($s x $x) . $c : ($s x ($y - $_)) . $d) : 
      ($y - $_ > $z ? (($s x $z) . $v) : ($s x ($y - $_)). ($y - $_ == $z ? $c : $d) ) ) . "\n" for 1 .. $y;
    $result .= $c . ($h x $x) . $c . "\n";

}
 
cuboid shift // rand 20, shift // rand 10, shift // rand 10;

my $ref = <<'EOD';
       +------------------+
      /                  /|
     /                  / |
    /                  /  |
   /                  /   |
  /                  /    |
 /                  /     |
+------------------+      +
|                  |     /
|                  |    /
|                  |   /
|                  |  /
|                  | /
|                  |/
+------------------+
EOD

say $result; 

use Test::More;
is ($result, $ref);
done_testing;
