#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Draw_a_cuboid
#c# 2018-07-30 <RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

sub cubLine :prototype($$$$) {
    my ($n, $dx, $dy, $cde) = @_;
 
    $result .= sprintf '%*s', $n + 1, substr($cde, 0, 1);
 
    for (my $d = 9 * $dx - 1 ; $d > 0 ; --$d) {
        $result .= substr($cde, 1, 1);
    }
 
    $result .= substr($cde, 0, 1);
    $result .= sprintf "%*s\n", $dy + 1, substr($cde, 2, 1);
}
 
sub cuboid :prototype($$$) {
    my ($dx, $dy, $dz) = @_;
 
    $result .= sprintf "cuboid %d %d %d:\n", $dx, $dy, $dz;
    cubLine $dy + 1, $dx, 0, '+-';
 
    for (my $i = 1 ; $i <= $dy ; ++$i) {
        cubLine $dy - $i + 1, $dx, $i - 1, '/ |';
    }
    cubLine 0, $dx, $dy, '+-|';
 
    for (my $i = 4 * $dz - $dy - 2 ; $i > 0 ; --$i) {
        cubLine 0, $dx, $dy, '| |';
    }
    cubLine 0, $dx, $dy, '| +';
 
    for (my $i = 1 ; $i <= $dy ; ++$i) {
        cubLine 0, $dx, $dy - $i, '| /';
    }
    cubLine 0, $dx, 0, "+-\n";
}
 
cuboid 2, 3, 4;
cuboid 1, 1, 1;
cuboid 6, 2, 1;

my $ref = <<'EOD';
cuboid 2 3 4:
    +-----------------+ 
   /                 /|
  /                 / |
 /                 /  |
+-----------------+   |
|                 |   |
|                 |   |
|                 |   |
|                 |   |
|                 |   |
|                 |   |
|                 |   |
|                 |   |
|                 |   |
|                 |   |
|                 |   |
|                 |   +
|                 |  /
|                 | /
|                 |/
+-----------------+

cuboid 1 1 1:
  +--------+ 
 /        /|
+--------+ |
|        | |
|        | +
|        |/
+--------+

cuboid 6 2 1:
   +-----------------------------------------------------+ 
  /                                                     /|
 /                                                     / |
+-----------------------------------------------------+  |
|                                                     |  +
|                                                     | /
|                                                     |/
+-----------------------------------------------------+

EOD

say $result; 

use Test::More;
is ($result, $ref);
done_testing();
