#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Gaussian_primes
#c# 2022-07-25 <RC, 2022-07-26 >RC
#p# OK
#n# fixed as per thundergnat's++ note

use v5.36;

use ntheory 'is_prime';

my ($plot, @primes) = gaussianprimes(10);
say my $result = "Primes within 10\n" . join(',  ', @primes) =~ s/.{94}\K  /\n/gr;
($plot, undef) = gaussianprimes(50);
my $plot50 = "Plot within 50\n$plot";

sub gaussianprimes {
    my $size = shift;
    my $plot = ( ' ' x (2 * $size + 1) . "\n" ) x (2 * $size + 1);
    my @primes;
    for my $A ( -$size .. $size ) {
        my $limit = int sqrt $size**2 - $A**2;
        for my $B ( -$limit .. $limit ) {
            my $norm = $A**2 + $B**2;
            if (is_prime( $norm ) 
            or ($A==0 && is_prime(abs $B) && (abs($B)-3)%4 == 0)      # may have zero-component fore (real part)...
            or ($B==0 && is_prime(abs $A) && (abs($A)-3)%4 == 0) ) {  #  ...or aft ('i' part)
                push @primes, sprintf("%2d%2di", $A, $B) =~ s/ (\di)/+$1/r;
                substr $plot, ($B + $size + 1) * (2 * $size + 2) + $A + $size + 1, 1, 'X';
            }
        }
    }
    return $plot, @primes;
}

my $ref1 = <<'EOD';
Primes within 10
-9-4i,  -9+4i,  -8-5i,  -8-3i,  -8+3i,  -8+5i,  -7-2i,  -7+0i,  -7+2i,  -6-5i,  -6-1i,  -6+1i,
-6+5i,  -5-8i,  -5-6i,  -5-4i,  -5-2i,  -5+2i,  -5+4i,  -5+6i,  -5+8i,  -4-9i,  -4-5i,  -4-1i,
-4+1i,  -4+5i,  -4+9i,  -3-8i,  -3-2i,  -3+0i,  -3+2i,  -3+8i,  -2-7i,  -2-5i,  -2-3i,  -2-1i,
-2+1i,  -2+3i,  -2+5i,  -2+7i,  -1-6i,  -1-4i,  -1-2i,  -1-1i,  -1+1i,  -1+2i,  -1+4i,  -1+6i,
 0-7i,   0-3i,   0+3i,   0+7i,   1-6i,   1-4i,   1-2i,   1-1i,   1+1i,   1+2i,   1+4i,   1+6i,
 2-7i,   2-5i,   2-3i,   2-1i,   2+1i,   2+3i,   2+5i,   2+7i,   3-8i,   3-2i,   3+0i,   3+2i,
 3+8i,   4-9i,   4-5i,   4-1i,   4+1i,   4+5i,   4+9i,   5-8i,   5-6i,   5-4i,   5-2i,   5+2i,
 5+4i,   5+6i,   5+8i,   6-5i,   6-1i,   6+1i,   6+5i,   7-2i,   7+0i,   7+2i,   8-5i,   8-3i,
 8+3i,   8+5i,   9-4i,   9+4i
EOD

my $ref2 = <<'EOD';
Plot within 50
                                                                                                     
                                                                                                     
                                             X X       X X                                           
                                      X                         X                                    
                                         X X     X X X     X X                                       
                                X   X   X     X         X     X   X   X                              
                                   X X     X     X   X     X     X X                                 
                              X X   X     X                 X     X   X X                            
                             X         X X X       X       X X X         X                           
                          X X     X   X       X         X       X   X     X X                        
                         X     X     X         X       X         X     X     X                       
                      X     X     X     X       X X X X       X     X     X     X                    
                                   X     X                   X     X                                 
                          X X     X X X     X   X     X   X     X X X     X X                        
                   X X X         X         X     X   X     X         X         X X X                 
                      X         X             X   X X   X             X         X                    
                 X       X X X   X X       X     X   X     X       X X   X X X       X               
                X     X       X     X   X X   X         X   X X   X     X       X     X              
                   X   X       X           X     X   X     X           X       X   X                 
              X   X     X   X       X X       X X     X X       X X       X   X     X   X            
                     X   X     X   X     X   X X   X   X X   X     X   X     X   X                   
              X     X X     X         X X                     X X         X     X X     X            
           X   X X   X             X     X   X X       X X   X     X             X   X X   X         
              X   X       X         X X       X         X       X X         X       X   X            
                   X         X X         X       X   X       X         X X         X                 
          X     X   X     X   X         X X   X   X X   X   X X         X   X     X   X     X        
         X   X         X X X X     X X X     X X       X X     X X X     X X X X         X   X       
                X         X     X             X   X X   X             X     X         X              
         X X X     X X       X X X     X   X       X       X   X     X X X       X X     X X X       
        X       X       X X X     X X X       X         X       X X X     X X X       X       X      
       X         X       X               X     X       X     X               X       X         X     
          X       X X   X   X   X     X X   X   X X X X   X   X X     X   X   X   X X       X        
     X X       X           X   X   X X   X   X     X     X   X   X X   X   X           X       X X   
              X X           X     X         X X         X X         X     X           X X            
         X X X               X   X     X X X     X   X     X X X     X   X               X X X       
      X     X   X   X X   X     X         X   X   X X   X   X         X     X   X X   X   X     X    
     X X     X   X X   X     X       X         X X   X X         X       X     X   X X   X     X X   
      X   X               X     X   X   X X       X X       X X   X   X     X               X   X    
   X     X   X     X X X     X X       X X X     X   X     X X X       X X     X X X     X   X     X 
        X                 X X     X   X     X             X     X   X     X X                 X      
     X     X     X   X   X     X     X       X X   X   X X       X     X     X   X   X     X     X   
    X   X   X       X X X     X X X   X   X X   X X X X   X X   X   X X X     X X X       X   X   X  
       X         X       X         X X   X     X       X     X   X X         X       X         X     
    X X X     X X X         X     X   X     X X X     X X X     X   X     X         X X X     X X X  
             X                 X X     X X X     X X X     X X X     X X                 X           
  X                 X X   X     X       X     X   X X   X     X       X     X   X X                 X
     X   X     X X X   X X X X   X X       X X X X   X X X X       X X   X X X X   X X X     X   X   
  X       X         X X   X   X     X   X X   X   X X   X   X X   X     X   X   X X         X       X
           X X     X           X         X X     X X X     X X         X           X     X X         
    X X       X X X     X         X X X     X X X X X X X X     X X X         X     X X X       X X  
           X   X         X X   X   X X   X   X X XX XX X X   X   X X   X   X X         X   X         
    X   X           X       X   X       X   X   X     X   X   X       X   X       X           X   X  
           X   X         X X   X   X X   X   X X XX XX X X   X   X X   X   X X         X   X         
    X X       X X X     X         X X X     X X X X X X X X     X X X         X     X X X       X X  
           X X     X           X         X X     X X X     X X         X           X     X X         
  X       X         X X   X   X     X   X X   X   X X   X   X X   X     X   X   X X         X       X
     X   X     X X X   X X X X   X X       X X X X   X X X X       X X   X X X X   X X X     X   X   
  X                 X X   X     X       X     X   X X   X     X       X     X   X X                 X
             X                 X X     X X X     X X X     X X X     X X                 X           
    X X X     X X X         X     X   X     X X X     X X X     X   X     X         X X X     X X X  
       X         X       X         X X   X     X       X     X   X X         X       X         X     
    X   X   X       X X X     X X X   X   X X   X X X X   X X   X   X X X     X X X       X   X   X  
     X     X     X   X   X     X     X       X X   X   X X       X     X     X   X   X     X     X   
        X                 X X     X   X     X             X     X   X     X X                 X      
   X     X   X     X X X     X X       X X X     X   X     X X X       X X     X X X     X   X     X 
      X   X               X     X   X   X X       X X       X X   X   X     X               X   X    
     X X     X   X X   X     X       X         X X   X X         X       X     X   X X   X     X X   
      X     X   X   X X   X     X         X   X   X X   X   X         X     X   X X   X   X     X    
         X X X               X   X     X X X     X   X     X X X     X   X               X X X       
              X X           X     X         X X         X X         X     X           X X            
     X X       X           X   X   X X   X   X     X     X   X   X X   X   X           X       X X   
          X       X X   X   X   X     X X   X   X X X X   X   X X     X   X   X   X X       X        
       X         X       X               X     X       X     X               X       X         X     
        X       X       X X X     X X X       X         X       X X X     X X X       X       X      
         X X X     X X       X X X     X   X       X       X   X     X X X       X X     X X X       
                X         X     X             X   X X   X             X     X         X              
         X   X         X X X X     X X X     X X       X X     X X X     X X X X         X   X       
          X     X   X     X   X         X X   X   X X   X   X X         X   X     X   X     X        
                   X         X X         X       X   X       X         X X         X                 
              X   X       X         X X       X         X       X X         X       X   X            
           X   X X   X             X     X   X X       X X   X     X             X   X X   X         
              X     X X     X         X X                     X X         X     X X     X            
                     X   X     X   X     X   X X   X   X X   X     X   X     X   X                   
              X   X     X   X       X X       X X     X X       X X       X   X     X   X            
                   X   X       X           X     X   X     X           X       X   X                 
                X     X       X     X   X X   X         X   X X   X     X       X     X              
                 X       X X X   X X       X     X   X     X       X X   X X X       X               
                      X         X             X   X X   X             X         X                    
                   X X X         X         X     X   X     X         X         X X X                 
                          X X     X X X     X   X     X   X     X X X     X X                        
                                   X     X                   X     X                                 
                      X     X     X     X       X X X X       X     X     X     X                    
                         X     X     X         X       X         X     X     X                       
                          X X     X   X       X         X       X   X     X X                        
                             X         X X X       X       X X X         X                           
                              X X   X     X                 X     X   X X                            
                                   X X     X     X   X     X     X X                                 
                                X   X   X     X         X     X   X   X                              
                                         X X     X X X     X X                                       
                                      X                         X                                    
                                             X X       X X                                           
EOD

use Test::More;
chomp $ref1;
is ($result, $ref1);
is(($plot50 =~ s/\s//gr), ($ref2 =~ s/\s//gr));
done_testing;
