#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Generic_swap
#c# 2018-08-10 <RC
#p# OK

use feature 'say';
my $result;

# Perl has support for swapping built-in

$x = 42;
$y = 47;

$result .= "$x $y\n";
($y, $x) = ($x, $y);
$result .= "$x $y\n";

#Here's a generic swap routine:

sub swap {@_[0, 1] = @_[1, 0]}

swap($x,$y);
$result .= "$x $y\n";

say $result; 
my $ref = <<'EOD';
42 47
47 42
42 47
EOD

use Test::More;
is ($result, $ref);
done_testing();
