#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Generalised_floating_point_addition
#c# 2019-10-03 >RC
#p# OK
#n# works with upper limit of 9999 (and almost certainly well beyond)
#n# Math::BigFloat extension also provides an arbitrary-precision decimal calculations

my @res;

use strict;
use warnings;
use feature 'say';

use Math::Decimal qw(dec_add dec_mul_pow10);

my $e = 63;

for my $n (-7..21) {
    my $num = '12345679' . '012345679' x ($n+7);
    my $sum = dec_mul_pow10(1, $e);
    $sum = dec_add($sum, dec_mul_pow10($num,$e)) for 1..81;
    push @res, "$n:" . (10**72 == $sum ? 'Y ' : 'N ');
    $e -= 9;
}

say my $result = join '', @res;

use Test::More;
is($result, '-7:Y -6:Y -5:Y -4:Y -3:Y -2:Y -1:Y 0:Y 1:Y 2:Y 3:Y 4:Y 5:Y 6:Y 7:Y 8:Y 9:Y 10:Y 11:Y 12:Y 13:Y 14:Y 15:Y 16:Y 17:Y 18:Y 19:Y 20:Y 21:Y ');
done_testing;
