#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Giuga_numbers
#c# 2022-07-01 <RC
#p# OK

my @res;

use strict;
use warnings;
use feature 'say';

use ntheory qw( factor forcomposites );
use List::Util qw( all );

# Tybalt89++
forcomposites {
    my $n = $_;
    all { ($n / $_ - 1) % $_ == 0 } factor $n and push @res, $n;
} 4, 67000;

# following Raku, a little faster than the above
for my $n (map { 6 * $_ } 1..11167) {
    push @res, $n if all { ($n / $_ - 1) % $_ == 0 } factor $n
}

say my $result = join "\n", @res;

my $ref = <<'EOD';
30
858
1722
66198
30
858
1722
66198
EOD

use Test::More;
chomp $ref;
is ($result, $ref);
done_testing();
