#!/usr/local/bin/perl
#u# https://rosettacode.org/wiki/Golden_ratio/Convergence
#c# 2023-06-05 >RC
#p# OK

my $result;

use v5.36;

use constant phi => (1 + sqrt 5) / 2;

sub GR ($n) { $n == 1 ? 2 : 1 + 1 / GR($n - 1) }

my $i;
while (++$i) {
    my $dev = abs phi - GR $i;
    (say $result = sprintf "%d iterations: %8.6f vs %8.6f (%8.6f)", $i, phi, GR($i), $dev and last) if $dev < 1e-5;
}

use Test::More;
is($result, '12 iterations: 1.618034 vs 1.618026 (0.000008)');
done_testing;

__END__

# run as Perl or Raku
my $oldPhi = 1;
my ($phi, $iters);
my $limit = 1e-5;
while (++$iters) {
    $phi = 1 + 1 / $oldPhi;
    last if abs($phi - $oldPhi) <= $limit;
    $oldPhi = $phi;
}

printf "Final value of phi : %.14f\n", $phi;
printf "Number of iterations : %d\n", $iters;
printf "Error (approx) : %16.14f\n", $phi - (1 + sqrt 5) / 2;
