#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Greatest_common_divisor
#c# 2018-08-11 <RC
#p# OK

use strict;
use warnings;
use feature 'say';

sub gcd1 {
  my ($u, $v) = @_;
  if ($v) {
    return gcd1($v, $u % $v);
  } else {
    return abs($u);
  }
}

# same idea, more succinct
sub gcd2 {
    my ($u, $v) = @_;
    $v ? gcd2($v, $u % $v) : abs($u);
}

say my $result1 = gcd1(49865, 69811);
say my $result2 = gcd2(49865, 69811);

use Test::More;
is ($result1, 9973);
is ($result2, 9973);
done_testing();
