#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Greatest_subsequential_sum
#c# 2018-08-11 <RC
#p# OK
#n# noodling, not worth RC update

use strict;
use warnings;

my @a = <-1 -2 3 5 6 -2 -1 4 -4 2 -1>;

my @maxsubarray;
my $maxsum = 0;

for my $begin (0..$#a) {
    for my $end ($begin..$#a) {
        my $sum = 0;
        $sum += $_ for @a[$begin..$end];
        if ($sum > $maxsum) {
            $maxsum = $sum;
            @maxsubarray = @a[$begin..$end];
        }
    }
}

print "@maxsubarray\n";

use Test::More;
is ("@maxsubarray", '3 5 6 -2 -1 4');
done_testing;
