#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Greatest_element_of_a_list
#c# 2018-08-11 <RC
#p# OK

use strict;
use warnings;
use feature 'say';

sub my_max {
    my $max = shift;
    for (@_) { $max = $_ if $_ > $max }
    return $max;
}

say my $result = my_max(<1 -1 01 1e0 1.1>);

# but in practice I always reach for
use List::Util 'max';
say List::Util::max(<1 -1 01 1e0 1.1>);

use Test::More;
is ($result, 1.1);
done_testing();
