#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Greatest_common_divisor
#c# 2018-08-11 <RC
#p# OK

use strict;
use warnings;
use feature 'say';

sub gcd_iter :prototype($$) {
  my ($u, $v) = @_;
  while ($v) {
    ($u, $v) = ($v, $u % $v);
  }
  return abs($u);
}

say my $result = gcd_iter(49865, 69811);
my $ref = <<'END';
END

use Test::More;
is ($result, 9973);
done_testing;
