#!/usr/local/bin/perl
#u# https://www.rosettacode.org/wiki/Greatest_prime_dividing_the_n-th_cubefree_number
#c# 2024-09-18 <RC
#p# OK

my @res;

use strict;
use warnings;
use feature 'say';

use Math::Prime::Util qw(factor);

my ($count, $i, $lim1, $lim2, $max, @result) = (1, 2, 100, 1000, 1e7, (1));

while ($count < $max) {
   my ($cubeFree, @factors) = (1, factor($i));
   if (scalar @factors >= 3) {
      for my $j (2..$#factors) {
         if ($factors[$j-2]==$factors[$j-1] && $factors[$j-1]==$factors[$j]) {
            $cubeFree = 0;
            last;
         }
      }
   }
   if ($cubeFree) {
      if ($count < $lim1) { push @result, $factors[-1] }
      $count++;
      if ($count == $lim1) {
         push @res, "The first terms of A370833 are:";
         for (my $k = 0; $k < @result; $k += 10) {
            push @res, sprintf "%3d " x 10, @result[$k..$k+9];
         }
         push @res, '';
      }
      if ($count == $lim2) {
         push @res, sprintf "The %8dth term of A370833 is %7d", $count, $factors[-1];
         $lim2 *= 10;
      }
   }
   $i++;
}

say my $result = join "\n", @res;

my $ref = <<'EOD';
The first terms of A370833 are:
  1   2   3   2   5   3   7   3   5  11 
  3  13   7   5  17   3  19   5   7  11 
 23   5  13   7  29   5  31  11  17   7 
  3  37  19  13  41   7  43  11   5  23 
 47   7   5  17  13  53  11  19  29  59 
  5  61  31   7  13  11  67  17  23   7 
 71  73  37   5  19  11  13  79  41  83 
  7  17  43  29  89   5  13  23  31  47 
 19  97   7  11   5 101  17 103   7  53 
107 109  11  37 113  19  23  29  13  59 

The     1000th term of A370833 is     109
The    10000th term of A370833 is     101
The   100000th term of A370833 is    1693
The  1000000th term of A370833 is 1202057
The 10000000th term of A370833 is 1202057
EOD

chomp $ref;
use Test::More;
is ($result, $ref);
done_testing();
