#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Guess_the_number/With_feedback_%28player%29
#c# 2018-08-11 <RC
#p# OK

use feature 'say';
my $result;



say $result; 
my $ref = <<'EOD';
EOD

use Test::More;
#is ($result, $ref);
#done_testing();
