#!/usr/local/bin/perl
#u# https://rosettacode.org/wiki/Radical_of_an_integer
#t# inprogress
#c# 2023-06-21 >RC
#p# OK

use Data::Printer;          # debug only
use Time::HiRes qw(sleep);  # debug only

my @res;

use v5.36;
#use strict; use warnings; use feature 'say';

use List::Util 'uniq';
use ntheory <primes vecprod factor>;

sub comma      { reverse ((reverse shift) =~ s/.{3}\K/,/gr) =~ s/^,//r }
sub table (@V) { ( sprintf( ('%3d')x@V, @V) ) =~ s/.{1,30}\K/\n/gr }

sub radical ($n) { vecprod uniq factor $n }

push @res, 'First fifty radicals:';
push @res, table map { radical $_ } 1..50;

push @res, sprintf "Radical for %7s => %7s", comma($_), comma radical($_) for 99999, 499999, 999999;

my $rad{1} = 1; 
my $limit = 1e6;

my $primes = primes(1,$limit);
say 0+@$primes;

say my $result = join "\n", @res;

my $ref = <<'END';
First fifty radicals:
  1  2  3  2  5  6  7  2  3 10
 11  6 13 14 15  2 17  6 19 10
 21 22 23  6  5 26  3 14 29 30
 31  2 33 34 35  6 37 38 39 10
 41 42 43 22 15 46 47  6  7 10

Radical for  99,999 =>  33,333
Radical for 499,999 =>   3,937
Radical for 999,999 => 111,111
END

use Test::More;
chomp $ref;
is($result, $ref);
#is(($result =~ s/\s//gr), ($ref =~ s/\s//gr));
done_testing();
