#!/usr/local/bin/perl
#u# https://rosettacode.org/wiki/Radical_of_an_integer
#t# inprogress
#c# 2023-0x-xx >RC
#p# OK

use Data::Printer;          # debug only
use Time::HiRes qw(sleep);  # debug only

my @res;

use v5.36;
#use strict; use warnings; use feature 'say';

use List::Util 'uniq';
use ntheory <vecprod factor>;

sub table ($c, @V) { my $t = $c * (my $w = 3); ( sprintf( ('%'.$w.'d')x@V, @V) ) =~ s/.{1,$t}\K/\n/gr }

sub radical ($n) { vecprod uniq factor $n }

push @res, 'First fifty radicals:';
push @res, table 10, map { radical $_ } 1..50;

say my $result = join "\n", @res;
my $ref = <<'END';
First fifty radicals:
  1  2  3  2  5  6  7  2  3 10
 11  6 13 14 15  2 17  6 19 10
 21 22 23  6  5 26  3 14 29 30
 31  2 33 34 35  6 37 38 39 10
 41 42 43 22 15 46 47  6  7 10
END

use Test::More;
#chomp $ref;
is($result, $ref);
#is(($result =~ s/\s//gr), ($ref =~ s/\s//gr));
done_testing();
