#!/usr/local/bin/perl
#u# https://www.rosettacode.org/wiki/Rainbow
#c# 2023-11-07 <RC
#p# OK
#f# RC file:: rainbow.dat

use strict;
use warnings;
use feature 'say';

use List::AllUtils qw( zip_by );

print zip_by { "\e[38;2;$_[1]m$_[0]\e[m" } [ split //, 'RAINBOW' ],
  [qw( 255;0;0 255;128;0 255;255;0 0;255;0 0;0;255 75;0;130 128;0;255 )];
print "\n";

open my $fh, '>', 'run/rainbow.dat';
print $fh zip_by { "\e[38;2;$_[1]m$_[0]\e[m" } [ split //, 'RAINBOW' ],
  [qw( 255;0;0 255;128;0 255;255;0 0;255;0 0;0;255 75;0;130 128;0;255 )];
close $fh;
