#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Ramsey's_theorem
#c# 2018-09-22 >RC
#p# OK

use strict;
use warnings;
use feature 'say';
my $result;

use ntheory qw(forcomb);
use Math::Cartesian::Product;

my @a;
my $n = 17;
push @a, [(0) x $n] for 0..$n-1;
$a[$_][$_] = '-' for 0..$n-1;

for my $x (cartesian {@_} [(0..$n-1)], [(1,2,4,8)]) {
    my $i = @$x[0];
    my $k = @$x[1];
    my $j = ($i + $k) % $n;
    $a[$i][$j] = $a[$j][$i] = 1;
}

forcomb {
    my $l = 0;
    my @i = @_;
    forcomb { $l += $a[ $i[$_[0]] ][ $i[$_[1]] ]; } (4,2);
    die "Bogus!" unless 0 < $l < 6;
} ($n,4);

$result .= join(' ' ,@$_) . "\n" for @a;
say $result;

my $ref = <<'EOD';
- 1 1 0 1 0 0 0 1 1 0 0 0 1 0 1 1
1 - 1 1 0 1 0 0 0 1 1 0 0 0 1 0 1
1 1 - 1 1 0 1 0 0 0 1 1 0 0 0 1 0
0 1 1 - 1 1 0 1 0 0 0 1 1 0 0 0 1
1 0 1 1 - 1 1 0 1 0 0 0 1 1 0 0 0
0 1 0 1 1 - 1 1 0 1 0 0 0 1 1 0 0
0 0 1 0 1 1 - 1 1 0 1 0 0 0 1 1 0
0 0 0 1 0 1 1 - 1 1 0 1 0 0 0 1 1
1 0 0 0 1 0 1 1 - 1 1 0 1 0 0 0 1
1 1 0 0 0 1 0 1 1 - 1 1 0 1 0 0 0
0 1 1 0 0 0 1 0 1 1 - 1 1 0 1 0 0
0 0 1 1 0 0 0 1 0 1 1 - 1 1 0 1 0
0 0 0 1 1 0 0 0 1 0 1 1 - 1 1 0 1
1 0 0 0 1 1 0 0 0 1 0 1 1 - 1 1 0
0 1 0 0 0 1 1 0 0 0 1 0 1 1 - 1 1
1 0 1 0 0 0 1 1 0 0 0 1 0 1 1 - 1
1 1 0 1 0 0 0 1 1 0 0 0 1 0 1 1 -
EOD

use Test::More;
is ($result, $ref);
done_testing;
