#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Rate_counter
#c# 2018-08-19 <RC
#p# OK
#n# just test that results look vaguely reasonable

use strict;
use warnings;
use feature 'say';

use Benchmark qw<timethese cmpthese>;

my $PI = 22/7; # pretty close!

my $data = timethese -1,{ 'Job1' => &job1, 'Job2' => &job2 };
my $dref = cmpthese( $data );
say '--';
say my $results = join ' ', @{$$dref[1]};

sub job1 { my $num = 1 + 0.5 * sqrt(-2 * log rand) * cos(2 * $PI * rand) }
sub job2 { my $num = 1 + 0.5 * sqrt(-2 * log rand) * cos(2 * $PI * rand) }

use Test::More;
ok $results =~ m#Job1\s+\d+/s.*%#; # Job1 73400320/s -- -19%
done_testing();
