#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Read_a_file_character_by_character/UTF8
#c# 2018-08-19 <RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

use utf8;
binmode STDOUT, ':utf8';  # so we can print wide chars without warning

open my $fh, "<:encoding(UTF-8)", 'ref/utf8.txt' or die "$!\n";

while (read $fh, my $char, 1) {
    last if $char eq "\n";
    $result .= sprintf("got character $char [U+%04x]", ord $char) . "\n";
}

close $fh;

say $result;

my $ref = <<'EOD';
got character a [U+0061]
got character ă [U+0103]
got character € [U+20ac]
got character ⼥ [U+2f25]
EOD

use Test::More;
is ($result, $ref);
done_testing;
