#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Reflection_List_properties
#t# skiptest
#c# 2019-03-28 >RC
#p# OK
#n# half-baked at best (and variable hash-order from Dumper prevents any testing)

no strict 'refs';
my $result;

{
     package Point;
     use Class::Spiffy -base;

     field 'x';
     field 'y';
}

{
     package Circle;
     use base qw(Point);
     field 'r';
}

package main;

my $p1 = Point->new(x => 8, y => -5);

my $c1 = Circle->new(r => 4);
my $c2 = Circle->new(x => 1, y => 2, r => 3);

use Data::Dumper;
$result .= Dumper $p1;
$result .= Dumper $c1;
$result .= Dumper $c2;

print $result; exit;

my $ref = <<'EOD';
$VAR1 = bless( {
                 'x' => 8,
                 'y' => -5
               }, 'Point' );
$VAR1 = bless( {
                 'r' => 4
               }, 'Circle' );
$VAR1 = bless( {
                 'y' => 2,
                 'r' => 3,
                 'x' => 1
               }, 'Circle' );
EOD

use Test::More;
is($result,$ref);
done_testing();
