#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Return_multiple_values
#c# 2018-08-18 <RC
#p# OK

use strict;
use warnings;
use feature 'say';

# Functions may return lists of values:

sub foo {
    my ($a, $b) = @_;
    return $a + $b, $a * $b;
}

my @res = foo(2,3);

say my $result = join "\n", @res;
my $ref = <<'EOD';
5
6
EOD

use Test::More;
chop $ref;
is ($result, $ref);
done_testing;
