#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Reverse_a_string
#c# 2018-08-18 <RC, 2018-09-08 >RC
#p# OK

my $result;

use strict;
use warnings;
use feature 'say';

use utf8;
binmode STDOUT, ':utf8';

# to reverse characters (code points):

$result .= reverse 'visor';
$result .="\n";

# to reverse graphemes:
my $string = "Jose\x{301}"; # "José" in NFD
$result .= join('', reverse $string =~ /\X/g); # becomes "ésoJ"
$result .="\n";
$string = 'ℵΑΩ 駱駝道 🤔 🇸🇧 🇺🇸 🇬🇧‍ 👨‍👩‍👧‍👦🆗🗺';
$result .= join('', reverse $string =~ /\X/g);
$result .="\n";

say $result;

my $ref = <<'EOD';
rosiv
ésoJ
🗺🆗👨‍👩‍👧‍👦 🇬🇧‍ 🇺🇸 🇸🇧 🤔 道駝駱 ΩΑℵ
EOD

use Test::More;
is ($result, $ref);
done_testing;
