#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Rosetta_Code/Count_examples
#c# 2018-08-21 <RC, 2019-04-12 >RC, 2022-08-xx >RC
#p# OK
#n# replaced non-working LWP::Simple version with HTTP::Tiny
#n# Mojo version: 'return' doesn't quit the anon. sub, so 'last' instead (thus 'no warnings')
#n# should start using 'mediawiki-query' like P6...

my (@res1,@res2);

use strict;
use warnings;
use feature 'say';

my $site = "https://rosettacode.org";
my $list_url = "/w/api.php?action=query&list=categorymembers&cmtitle=Category:Programming_Tasks&cmlimit=10&format=xml";

use HTTP::Tiny;
my $response = HTTP::Tiny->new->get("$site$list_url");
$DB::single = 1;

for ($response->{content} =~ /cm.*?title="(.*?)"/g) {
    (my $slug = $_) =~ tr/ /_/;
    my $response = HTTP::Tiny->new->get("$site/wiki/$slug");
    my $count = () = $response->{content} =~ /toclevel-1/g;
    push @res1, "$_: $count examples";
    last if $_ eq '15 puzzle solver';
}

my $result1 = join "\n", @res1;

use Mojo::UserAgent;

my $ua = Mojo::UserAgent->new;
$ua->get("$site$list_url")->res->dom->find('cm')->each(sub {
    no warnings;
    (my $slug = $_->{title}) =~ tr/ /_/;
    my $count = $ua->get("$site/wiki/$slug")->res->dom->find("#toc .toclevel-1")->size;
    push @res2, "$_->{title}: $count examples";
    last if $_->{title} =~ /15 puzzle solver/;
});

my $result2 = join "\n", @res2;

say $result1;

use Test::More;
ok $result1 =~ /100 doors: 3\d\d examples/i;
ok $result1 =~ /15 Puzzle Game: [7-9]\d examples/i;
is($result1,$result2);
done_testing();

__END__

2022-08-25
100 doors: 335 examples
100 prisoners: 78 examples
15 puzzle game: 78 examples
15 puzzle solver: 25 examples
