#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Nested_function
#c# 2018-08-20 <RC
#p# OK

use strict;
use warnings;
use feature 'say';

sub makeList {
    our $separator = shift;
    our $counter = 1;

    sub makeItem { $counter++ . $separator . shift . "\n" }

    makeItem("first") . makeItem("second") . makeItem("third")
}

say my $result = makeList(". ");

my $ref = <<'EOD';
1. first
2. second
3. third
EOD

use Test::More;
is ($result, $ref);
done_testing;
