#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Next_special_primes
#c# 2021-04-18 >RC
#p# OK

my @res;

use strict;
use warnings;
use feature <state say>;

use ntheory 'primes';

my $limit = 1050;

sub is_special {
    state $previous = 2;
    state $gap      = 0;
    state @primes = @{primes( 2*$limit )};

    shift @primes while $primes[0] <= $previous + $gap;
    $gap = $primes[0] - $previous;
    $previous = $primes[0];  
    [$previous, $gap];
}

my @specials = [2, 0];
do { push @specials, is_special() } until $specials[-1][0] >= $limit;

pop @specials;
push @res, sprintf "%4d %4d", @$_ for @specials;

say my $result = join "\n", @res;

my $ref = <<'END';
   2    0
   3    1
   5    2
  11    6
  19    8
  29   10
  41   12
  59   18
  79   20
 101   22
 127   26
 157   30
 191   34
 227   36
 269   42
 313   44
 359   46
 409   50
 461   52
 521   60
 587   66
 659   72
 733   74
 809   76
 887   78
 967   80
1049   82
END

use Test::More;
chomp $ref;
is($result, $ref);
done_testing();
