#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Number_reversal_game
#t# testok
#c# 2018-08-20 <RC
#p# OK

srand 123456;

use strict;
use warnings;
use feature 'say';
my $result;

use List::Util 'shuffle';

my $turn = 0;
my @jumble = shuffle 1..9;

while ( join('', @jumble) eq '123456789' ) {
    @jumble = shuffle 1..9;
}

my @steps = <6 4 2 8 6 4 2 4>; # DH change

until ( join('', @jumble) eq '123456789' ) {
    $turn++;
    printf "%2d: @jumble - Flip how many digits ? ", $turn;

    #my $d = <>;
    my $d = shift @steps; # DH change

    @jumble[0..$d-1] = reverse @jumble[0..$d-1];
}

print "    @jumble\n";
print "You won in $turn turns.\n";
say 'ok 1';
