#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Numbers_which_are_the_cube_roots_of_the_product_of_their_proper_divisors
#c# 2022-10-01 NOT ON RC
#p# OK
#n# and this works why? (see OEIS:A111398)

my($result1,@res);

use v5.36;
use ntheory 'divisors';

for my $num (1 .. 3e5) {
    state $c;
    next unless $num == 1 or divisors($num) == 8;
    $c++;
    if    ($c <=    50) { $result1 .= "$num "      }
    elsif ($c ==   500) { push @res, '  500 '.$num }
    elsif ($c ==  5000) { push @res, ' 5000 '.$num }
    elsif ($c == 50000) { push @res, '50000 '.$num }
}

say $result1;
say my $result2 = join "\n", @res;

my $ref1 = <<'END';
1 24 30 40 42 54 56 66 70 78 88 102 104 105 110 114 128 130 135 136 138 152 154 165 170 174 182 184 186 189 190 195 222 230 231 232 238 246 248 250 255 258 266 273 282 285 286 290 296 297 
END

my $ref2 = <<'END';
  500 2526
 5000 23118
50000 223735
END

use Test::More;
chomp $ref1;
chomp $ref2;
is($result1, $ref1);
is($result2, $ref2);
done_testing;
