#!/usr/local/bin/perl
#u# http://rosettacode.org/wiki/Number_names
#c# 2018-08-20 <RC
#p# OK

use Lingua::EN::Numbers 'num2en';

print (my $result = num2en(123456789)) . "\n";

use Test::More;
is $result, 'one hundred and twenty-three million, four hundred and fifty-six thousand, seven hundred and eighty-nine';
done_testing();
